/* <LICENSES> */
/*
 * Copyright (c) 2026 Emilio Navarrete Lineros <enavarre@outlook.com>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

/* trees.c -- output deflated data using Huffman coding
 * Copyright (C) 1995-2026 Jean-loup Gailly
 * detect_data_type() function provided freely by Cosmin Truta, 2006
 * For conditions of distribution and use, see copyright notice in zlib.h
 */

/* zlib.h -- interface of the 'zlib' general purpose compression library
  version 1.3.2, February 17th, 2026

  Copyright (C) 1995-2026 Jean-loup Gailly and Mark Adler

  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.

  Jean-loup Gailly        Mark Adler
  jloup@gzip.org          madler@alumni.caltech.edu


  The data format used by the zlib library is described by RFCs (Request for
  Comments) 1950 to 1952 at https://datatracker.ietf.org/doc/html/rfc1950
  (zlib format), rfc1951 (deflate format) and rfc1952 (gzip format).
*/
/* </LICENSES> */

/* <CODE> */
//! The Huffman half of deflate: building the literal/length, distance and bit-length trees of
//! a block, choosing between a stored, a fixed-code and a dynamic-code block, and writing the
//! block bits into the pending buffer.
//!
//! Upstream: sys/lib/libz/trees.c @ 3ce1f3f79392, sys/lib/libz/trees.h @ 3ce1f3f79392
//!
//! **This is an altered source version, not the original zlib `trees.c`/`trees.h`** (zlib
//! licence, clause 2): a Rust rewrite written for EmiBSD. The original's notice is kept above
//! in full (clause 3). `trees.h` is generated by `trees.c` (`-DGEN_TREES_H`) and carries no
//! licence text of its own; it is part of zlib and under the same notice, the zlib.h one
//! above. Do not mistake this file for the zlib distribution; bugs here are not the zlib
//! authors'.
//!
//! The algorithm: the deflation process uses several Huffman trees. The more common source
//! values are represented by shorter bit sequences. Each code tree is stored in a compressed
//! form which is itself a Huffman encoding of the lengths of all the code strings (in
//! ascending order by source values). The actual code strings are reconstructed from the
//! lengths in the inflate process, as described in the deflate specification (RFC 1951).
//! References: Deutsch, "DEFLATE Compressed Data Format Specification"; Storer, "Data
//! Compression: Methods and Theory", pp. 49-50 (Computer Science Press, 1988); Sedgewick,
//! "Algorithms", p290 (Addison-Wesley, 1983). `detect_data_type()` was provided freely by
//! Cosmin Truta, 2006.
//!
//! ## Deviations
//! - The static tables of `trees.h` (`static_ltree`, `static_dtree`, `_dist_code`,
//!   `_length_code`, `base_length`, `base_dist`) are not written out: they are computed at
//!   compile time by `tr_static_init`, the code `trees.c` uses to generate `trees.h`
//!   (`GEN_TREES_H`), so there is no run-time initialisation. The host tests compare them
//!   with `trees.h` (in full under `just test-ref`). `gen_trees_header` (which writes
//!   `trees.h` out) has no counterpart.
//! - `tree_desc.dyn_tree` is a `Tree` selector; the tree a function works on is moved out
//!   of the state (`core::mem::take` of its `Vec`, no copy) for the duration, so the rest of
//!   the state stays borrowable, the way the C reaches both through `s`.
//! - `send_bits`, `send_code`, `put_short`, `pqremove` and `smaller` are functions or a local
//!   macro instead of C macros. `send_code` copies the tree entry first, so the tree may be
//!   one of the state's own.
//! - `_tr_flush_block` takes the stream's `data_type` instead of reaching it through
//!   `s->strm`, and `buf` is an offset in the window (`None` for the C's NULL).
//! - `ZLIB_DEBUG` is not defined: `compressed_len`, `bits_sent`, the `Trace*` output and
//!   `DUMP_BL_TREE` are gone; `Assert` is `zassert!`. `FORCE_STATIC`, `FORCE_STORED` and
//!   `NO_INIT_GLOBAL_POINTERS` are not defined either.
//! - `_tr_tally` is ported but the kernel build does not call it (`deflate.c` uses the
//!   inline `_tr_tally_lit`/`_tr_tally_dist` of `deflate.h` when `ZLIB_DEBUG` is off); the
//!   host tests do.

#![allow(non_upper_case_globals)] // zlib's names (static_ltree, _dist_code, bl_order)

use crate::deflate::{
    BL_CODES, Buf_size, CtData, D_CODES, DeflateState, HEAP_SIZE, L_CODES, LENGTH_CODES, LITERALS,
    MAX_BITS, Tree, d_code, put_byte,
};
use crate::zlib::{Z_BINARY, Z_FIXED, Z_TEXT, Z_UNKNOWN};
use crate::zutil::{DYN_TREES, MAX_MATCH, MIN_MATCH, STATIC_TREES, STORED_BLOCK, zassert};

/// `MAX_BL_BITS`: bit length codes must not exceed MAX_BL_BITS bits.
const MAX_BL_BITS: usize = 7;

/// `END_BLOCK`: end of block literal code.
const END_BLOCK: usize = 256;

/// `REP_3_6`: repeat previous bit length 3-6 times (2 bits of repeat count).
const REP_3_6: usize = 16;

/// `REPZ_3_10`: repeat a zero length 3-10 times (3 bits of repeat count).
const REPZ_3_10: usize = 17;

/// `REPZ_11_138`: repeat a zero length 11-138 times (7 bits of repeat count).
const REPZ_11_138: usize = 18;

/// `extra_lbits`: extra bits for each length code.
const extra_lbits: [u32; LENGTH_CODES] = [
    0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 0,
];

/// `extra_dbits`: extra bits for each distance code.
const extra_dbits: [u32; D_CODES] = [
    0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13,
    13,
];

/// `extra_blbits`: extra bits for each bit length code.
const extra_blbits: [u32; BL_CODES] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 7];

/// `bl_order`: the lengths of the bit length codes are sent in order of decreasing
/// probability, to avoid transmitting the lengths for unused bit length codes.
const bl_order: [u8; BL_CODES] = [
    16, 17, 18, 0, 8, 7, 9, 6, 10, 5, 11, 4, 12, 3, 13, 2, 14, 1, 15,
];

/// `DIST_CODE_LEN`: see definition of array dist_code below.
const DIST_CODE_LEN: usize = 512;

/// The tables of `trees.h`, as `tr_static_init` computes them.
struct StaticTables {
    static_ltree: [CtData; L_CODES + 2],
    static_dtree: [CtData; D_CODES],
    dist_code: [u8; DIST_CODE_LEN],
    length_code: [u8; MAX_MATCH - MIN_MATCH + 1],
    base_length: [u32; LENGTH_CODES],
    base_dist: [u32; D_CODES],
}

/// `static_tree_desc`: what a dynamic tree is built against.
pub(crate) struct StaticTreeDesc {
    /// `static_tree`: static tree or NULL.
    static_tree: Option<&'static [CtData]>,
    /// `extra_bits`: extra bits for each code.
    extra_bits: &'static [u32],
    /// `extra_base`: base index for extra_bits.
    extra_base: usize,
    /// `elems`: max number of elements in the tree.
    elems: usize,
    /// `max_length`: max bit length for the codes.
    max_length: usize,
}

/// The tables, computed once at compile time.
static TABLES: StaticTables = tr_static_init();

/// `static_ltree`: the static literal tree. Since the bit lengths are imposed, there is no
/// need for the L_CODES extra codes used during heap construction. However the codes 286 and
/// 287 are needed to build a canonical tree (see `_tr_init`).
pub(crate) static static_ltree: [CtData; L_CODES + 2] = TABLES.static_ltree;

/// `static_dtree`: the static distance tree. (Actually a trivial tree since all codes use 5
/// bits.)
pub(crate) static static_dtree: [CtData; D_CODES] = TABLES.static_dtree;

/// `_dist_code`: distance codes. The first 256 values correspond to the distances 3 .. 258,
/// the last 256 values correspond to the top 8 bits of the 15 bit distances.
pub(crate) static _dist_code: [u8; DIST_CODE_LEN] = TABLES.dist_code;

/// `_length_code`: length code for each normalized match length (0 == MIN_MATCH).
pub(crate) static _length_code: [u8; MAX_MATCH - MIN_MATCH + 1] = TABLES.length_code;

/// `base_length`: first normalized length for each code (0 = MIN_MATCH).
static base_length: [u32; LENGTH_CODES] = TABLES.base_length;

/// `base_dist`: first normalized distance for each code (0 = distance of 1).
static base_dist: [u32; D_CODES] = TABLES.base_dist;

/// `static_l_desc`.
pub(crate) static static_l_desc: StaticTreeDesc = StaticTreeDesc {
    static_tree: Some(&static_ltree),
    extra_bits: &extra_lbits,
    extra_base: LITERALS + 1,
    elems: L_CODES,
    max_length: MAX_BITS,
};

/// `static_d_desc`.
pub(crate) static static_d_desc: StaticTreeDesc = StaticTreeDesc {
    static_tree: Some(&static_dtree),
    extra_bits: &extra_dbits,
    extra_base: 0,
    elems: D_CODES,
    max_length: MAX_BITS,
};

/// `static_bl_desc`.
pub(crate) static static_bl_desc: StaticTreeDesc = StaticTreeDesc {
    static_tree: None,
    extra_bits: &extra_blbits,
    extra_base: 0,
    elems: BL_CODES,
    max_length: MAX_BL_BITS,
};

/// `put_short`: output a short LSB first on the stream. IN assertion: there is enough room
/// in pendingBuf.
fn put_short(s: &mut DeflateState, w: u16) {
    put_byte(s, (w & 0xff) as u8);
    put_byte(s, (w >> 8) as u8);
}

/// `bi_reverse`: reverse the first `len` bits of a code, using straightforward code (a faster
/// method would use a table). IN assertion: 1 <= len <= 15.
const fn bi_reverse(mut code: u32, mut len: u32) -> u32 {
    let mut res = 0;
    loop {
        res |= code & 1;
        code >>= 1;
        res <<= 1;
        len -= 1;
        if len == 0 {
            break;
        }
    }
    res >> 1
}

/// `bi_flush`: flush the bit buffer, keeping at most 7 bits in it.
fn bi_flush(s: &mut DeflateState) {
    if s.bi_valid == 16 {
        put_short(s, s.bi_buf);
        s.bi_buf = 0;
        s.bi_valid = 0;
    } else if s.bi_valid >= 8 {
        put_byte(s, s.bi_buf as u8);
        s.bi_buf >>= 8;
        s.bi_valid -= 8;
    }
}

/// `bi_windup`: flush the bit buffer and align the output on a byte boundary.
fn bi_windup(s: &mut DeflateState) {
    if s.bi_valid > 8 {
        put_short(s, s.bi_buf);
    } else if s.bi_valid > 0 {
        put_byte(s, s.bi_buf as u8);
    }
    s.bi_used = ((s.bi_valid - 1) & 7) + 1;
    s.bi_buf = 0;
    s.bi_valid = 0;
}

/// `gen_codes`: generate the codes for a given tree and bit counts (which need not be
/// optimal). IN assertion: the array bl_count contains the bit length statistics for the
/// given tree and the field len is set for all tree elements. OUT assertion: the field code
/// is set for all tree elements of non zero code length. A `const fn`, so that the static
/// literal tree is built with it at compile time.
const fn gen_codes(tree: &mut [CtData], max_code: usize, bl_count: &[u16; MAX_BITS + 1]) {
    let mut next_code = [0u16; MAX_BITS + 1]; // next code value for each bit length
    let mut code: u32 = 0; // running code value

    // The distribution counts are first used to generate the code values without bit
    // reversal.
    let mut bits = 1;
    while bits <= MAX_BITS {
        code = (code + bl_count[bits - 1] as u32) << 1;
        next_code[bits] = code as u16;
        bits += 1;
    }
    // Check that the bit counts in bl_count are consistent. The last code must be all ones.
    // (Assert in the C: checked by the host tests through `build_tree`.)

    let mut n = 0;
    while n <= max_code {
        let len = tree[n].dl as usize;
        if len != 0 {
            // Now reverse the bits
            tree[n].fc = bi_reverse(next_code[len] as u32, len as u32) as u16;
            next_code[len] += 1;
        }
        n += 1;
    }
}

/// `send_code(s, c, tree)`: send a code of the given tree. The entry is copied out first, so
/// `tree` may be one of the state's own trees.
macro_rules! send_code {
    ($s:expr, $c:expr, $tree:expr) => {{
        let ct: CtData = $tree[$c];
        send_bits($s, u32::from(ct.fc), u32::from(ct.dl));
    }};
}

/// `send_bits`: send a value on a given number of bits. IN assertion: length <= 16 and value
/// fits in length bits.
fn send_bits(s: &mut DeflateState, value: u32, length: u32) {
    let len = length as i32;
    if s.bi_valid > Buf_size - len {
        let val = value & 0xffff;
        s.bi_buf |= (val << s.bi_valid) as u16;
        put_short(s, s.bi_buf);
        s.bi_buf = (val >> (Buf_size - s.bi_valid)) as u16;
        s.bi_valid += len - Buf_size;
    } else {
        s.bi_buf |= ((value & 0xffff) << s.bi_valid) as u16;
        s.bi_valid += len;
    }
}

/// `tr_static_init`: initialize the various 'constant' tables (the `GEN_TREES_H` path, run
/// by the compiler).
const fn tr_static_init() -> StaticTables {
    let mut t = StaticTables {
        static_ltree: [CtData::new(0, 0); L_CODES + 2],
        static_dtree: [CtData::new(0, 0); D_CODES],
        dist_code: [0; DIST_CODE_LEN],
        length_code: [0; MAX_MATCH - MIN_MATCH + 1],
        base_length: [0; LENGTH_CODES],
        base_dist: [0; D_CODES],
    };

    // Initialize the mapping length (0..255) -> length code (0..28)
    let mut length = 0;
    let mut code = 0;
    while code < LENGTH_CODES - 1 {
        t.base_length[code] = length as u32;
        let mut n = 0;
        while n < (1 << extra_lbits[code]) {
            t.length_code[length] = code as u8;
            length += 1;
            n += 1;
        }
        code += 1;
    }
    assert!(length == 256, "tr_static_init: length != 256");
    // Note that the length 255 (match length 258) can be represented in two different ways:
    // code 284 + 5 bits or code 285, so we overwrite length_code[255] to use the best
    // encoding:
    t.length_code[length - 1] = code as u8;

    // Initialize the mapping dist (0..32K) -> dist code (0..29)
    let mut dist = 0;
    code = 0;
    while code < 16 {
        t.base_dist[code] = dist as u32;
        let mut n = 0;
        while n < (1 << extra_dbits[code]) {
            t.dist_code[dist] = code as u8;
            dist += 1;
            n += 1;
        }
        code += 1;
    }
    assert!(dist == 256, "tr_static_init: dist != 256");
    dist >>= 7; // from now on, all distances are divided by 128
    while code < D_CODES {
        t.base_dist[code] = (dist << 7) as u32;
        let mut n = 0;
        while n < (1 << (extra_dbits[code] - 7)) {
            t.dist_code[256 + dist] = code as u8;
            dist += 1;
            n += 1;
        }
        code += 1;
    }
    assert!(dist == 256, "tr_static_init: 256 + dist != 512");

    // Construct the codes of the static literal tree
    let mut bl_count = [0u16; MAX_BITS + 1];
    let mut n = 0;
    while n <= 143 {
        t.static_ltree[n].dl = 8;
        bl_count[8] += 1;
        n += 1;
    }
    while n <= 255 {
        t.static_ltree[n].dl = 9;
        bl_count[9] += 1;
        n += 1;
    }
    while n <= 279 {
        t.static_ltree[n].dl = 7;
        bl_count[7] += 1;
        n += 1;
    }
    while n <= 287 {
        t.static_ltree[n].dl = 8;
        bl_count[8] += 1;
        n += 1;
    }
    // Codes 286 and 287 do not exist, but we must include them in the tree construction to
    // get a canonical Huffman tree (longest code all ones)
    gen_codes(&mut t.static_ltree, L_CODES + 1, &bl_count);

    // The static distance tree is trivial:
    n = 0;
    while n < D_CODES {
        t.static_dtree[n].dl = 5;
        t.static_dtree[n].fc = bi_reverse(n as u32, 5) as u16;
        n += 1;
    }
    t
}

/// `init_block`: initialize a new block.
fn init_block(s: &mut DeflateState) {
    // Initialize the trees.
    for ct in &mut s.dyn_ltree[..L_CODES] {
        ct.fc = 0;
    }
    for ct in &mut s.dyn_dtree[..D_CODES] {
        ct.fc = 0;
    }
    for ct in &mut s.bl_tree[..BL_CODES] {
        ct.fc = 0;
    }

    s.dyn_ltree[END_BLOCK].fc = 1;
    s.opt_len = 0;
    s.static_len = 0;
    s.sym_next = 0;
    s.matches = 0;
}

/// `_tr_init`: initialize the tree data structures for a new zlib stream.
pub(crate) fn _tr_init(s: &mut DeflateState) {
    // tr_static_init() ran at compile time.
    s.l_desc.stat_desc = &static_l_desc;
    s.d_desc.stat_desc = &static_d_desc;
    s.bl_desc.stat_desc = &static_bl_desc;

    s.bi_buf = 0;
    s.bi_valid = 0;
    s.bi_used = 0;

    // Initialize the first block of the first file:
    init_block(s);
}

/// `SMALLEST`: index within the heap array of least frequent node in the Huffman tree.
const SMALLEST: usize = 1;

/// `pqremove`: remove the smallest element from the heap and recreate the heap with one less
/// element. Updates heap and heap_len. Returns the removed element (`top`).
fn pqremove(s: &mut DeflateState, tree: &[CtData]) -> usize {
    let top = s.heap[SMALLEST];
    s.heap[SMALLEST] = s.heap[s.heap_len];
    s.heap_len -= 1;
    pqdownheap(s, tree, SMALLEST);
    top
}

/// `smaller`: compares to subtrees, using the tree depth as tie breaker when the subtrees
/// have equal frequency. This minimizes the worst case length.
fn smaller(tree: &[CtData], n: usize, m: usize, depth: &[u8]) -> bool {
    tree[n].fc < tree[m].fc || (tree[n].fc == tree[m].fc && depth[n] <= depth[m])
}

/// `pqdownheap`: restore the heap property by moving down the tree starting at node k,
/// exchanging a node with the smallest of its two sons if necessary, stopping when the heap
/// property is re-established (each father smaller than its two sons).
fn pqdownheap(s: &mut DeflateState, tree: &[CtData], mut k: usize) {
    let v = s.heap[k];
    let mut j = k << 1; // left son of k
    while j <= s.heap_len {
        // Set j to the smallest of the two sons:
        if j < s.heap_len && smaller(tree, s.heap[j + 1], s.heap[j], &s.depth) {
            j += 1;
        }
        // Exit if v is smaller than both sons
        if smaller(tree, v, s.heap[j], &s.depth) {
            break;
        }

        // Exchange v with the smallest son
        s.heap[k] = s.heap[j];
        k = j;

        // And continue down the tree, setting j to the left son of k
        j <<= 1;
    }
    s.heap[k] = v;
}

/// `gen_bitlen`: compute the optimal bit lengths for a tree and update the total bit length
/// for the current block. IN assertion: the fields freq and dad are set, `heap[heap_max]` and
/// above are the tree nodes sorted by increasing frequency. OUT assertions: the field len is
/// set to the optimal bit length, the array bl_count contains the frequencies for each bit
/// length. The length opt_len is updated; static_len is also updated if stree is not null.
fn gen_bitlen(s: &mut DeflateState, tree: &mut [CtData], which: Tree) {
    let max_code = s.desc(which).max_code;
    let stat_desc = s.desc(which).stat_desc;
    let stree = stat_desc.static_tree;
    let extra = stat_desc.extra_bits;
    let base = stat_desc.extra_base;
    let max_length = stat_desc.max_length;
    let mut overflow = 0i32; // number of elements with bit length too large

    s.bl_count = [0; MAX_BITS + 1];

    // In a first pass, compute the optimal bit lengths (which may overflow in the case of the
    // bit length tree).
    tree[s.heap[s.heap_max]].dl = 0; // root of the heap

    let mut h = s.heap_max + 1;
    while h < HEAP_SIZE {
        let n = s.heap[h];
        h += 1;
        let mut bits = usize::from(tree[usize::from(tree[n].dl)].dl) + 1;
        if bits > max_length {
            bits = max_length;
            overflow += 1;
        }
        tree[n].dl = bits as u16;
        // We overwrite tree[n].Dad which is no longer needed

        if n as i32 > max_code {
            continue; // not a leaf node
        }

        s.bl_count[bits] += 1;
        let xbits = if n >= base { extra[n - base] } else { 0 };
        let f = u64::from(tree[n].fc);
        s.opt_len = s.opt_len.wrapping_add(f * u64::from(bits as u32 + xbits));
        if let Some(stree) = stree {
            s.static_len = s
                .static_len
                .wrapping_add(f * u64::from(u32::from(stree[n].dl) + xbits));
        }
    }
    if overflow == 0 {
        return;
    }

    // This happens for example on obj2 and pic of the Calgary corpus

    // Find the first bit length which could increase:
    loop {
        let mut bits = max_length - 1;
        while s.bl_count[bits] == 0 {
            bits -= 1;
        }
        s.bl_count[bits] -= 1; // move one leaf down the tree
        s.bl_count[bits + 1] += 2; // move one overflow item as its brother
        s.bl_count[max_length] -= 1;
        // The brother of the overflow item also moves one step up, but this does not affect
        // bl_count[max_length]
        overflow -= 2;
        if overflow <= 0 {
            break;
        }
    }

    // Now recompute all bit lengths, scanning in increasing frequency. h is still equal to
    // HEAP_SIZE. (It is simpler to reconstruct all lengths instead of fixing only the wrong
    // ones. This idea is taken from 'ar' written by Haruhiko Okumura.)
    let mut bits = max_length;
    while bits != 0 {
        let mut n = s.bl_count[bits];
        while n != 0 {
            h -= 1;
            let m = s.heap[h];
            if m as i32 > max_code {
                continue;
            }
            if usize::from(tree[m].dl) != bits {
                s.opt_len = s.opt_len.wrapping_add(
                    (bits as u64)
                        .wrapping_sub(u64::from(tree[m].dl))
                        .wrapping_mul(u64::from(tree[m].fc)),
                );
                tree[m].dl = bits as u16;
            }
            n -= 1;
        }
        bits -= 1;
    }
}

/// `build_tree`: construct one Huffman tree and assigns the code bit strings and lengths.
/// Update the total bit length for the current block. IN assertion: the field freq is set
/// for all tree elements. OUT assertions: the fields len and code are set to the optimal bit
/// length and corresponding code. The length opt_len is updated; static_len is also updated
/// if stree is not null. The field max_code is set.
fn build_tree(s: &mut DeflateState, which: Tree) {
    let mut tree = core::mem::take(s.dyn_tree(which));
    let stree = s.desc(which).stat_desc.static_tree;
    let elems = s.desc(which).stat_desc.elems;
    let mut max_code: i32 = -1; // largest code with non zero frequency

    // Construct the initial heap, with least frequent element in heap[SMALLEST]. The sons of
    // heap[n] are heap[2*n] and heap[2*n + 1]. heap[0] is not used.
    s.heap_len = 0;
    s.heap_max = HEAP_SIZE;

    for (n, ct) in tree[..elems].iter_mut().enumerate() {
        if ct.fc != 0 {
            s.heap_len += 1;
            s.heap[s.heap_len] = n;
            max_code = n as i32;
            s.depth[n] = 0;
        } else {
            ct.dl = 0;
        }
    }

    // The pkzip format requires that at least one distance code exists, and that at least
    // one bit should be sent even if there is only one possible code. So to avoid special
    // checks later on we force at least two codes of non zero frequency.
    while s.heap_len < 2 {
        let node = if max_code < 2 {
            max_code += 1;
            max_code as usize
        } else {
            0
        };
        s.heap_len += 1;
        s.heap[s.heap_len] = node;
        tree[node].fc = 1;
        s.depth[node] = 0;
        s.opt_len = s.opt_len.wrapping_sub(1);
        if let Some(stree) = stree {
            s.static_len = s.static_len.wrapping_sub(u64::from(stree[node].dl));
        }
        // node is 0 or 1 so it does not have extra bits
    }
    s.desc(which).max_code = max_code;

    // The elements heap[heap_len/2 + 1 .. heap_len] are leaves of the tree, establish
    // sub-heaps of increasing lengths:
    for n in (1..=s.heap_len / 2).rev() {
        pqdownheap(s, &tree, n);
    }

    // Construct the Huffman tree by repeatedly combining the least two frequent nodes.
    let mut node = elems; // next internal node of the tree
    loop {
        let n = pqremove(s, &tree); // n = node of least frequency
        let m = s.heap[SMALLEST]; // m = node of next least frequency

        s.heap_max -= 1;
        s.heap[s.heap_max] = n; // keep the nodes sorted by frequency
        s.heap_max -= 1;
        s.heap[s.heap_max] = m;

        // Create a new node father of n and m
        tree[node].fc = tree[n].fc.wrapping_add(tree[m].fc);
        s.depth[node] = s.depth[n].max(s.depth[m]) + 1;
        tree[n].dl = node as u16;
        tree[m].dl = node as u16;

        // and insert the new node in the heap
        s.heap[SMALLEST] = node;
        node += 1;
        pqdownheap(s, &tree, SMALLEST);

        if s.heap_len < 2 {
            break;
        }
    }

    s.heap_max -= 1;
    s.heap[s.heap_max] = s.heap[SMALLEST];

    // At this point, the fields freq and dad are set. We can now generate the bit lengths.
    gen_bitlen(s, &mut tree, which);

    // The field len is now set, we can generate the bit codes
    zassert!(
        {
            let mut code = 0u32;
            for bits in 1..=MAX_BITS {
                code = (code + u32::from(s.bl_count[bits - 1])) << 1;
            }
            code + u32::from(s.bl_count[MAX_BITS]) == 1 << MAX_BITS
        },
        "inconsistent bit counts"
    );
    gen_codes(&mut tree, max_code as usize, &s.bl_count);
    *s.dyn_tree(which) = tree;
}

/// `scan_tree`: scan a literal or distance tree to determine the frequencies of the codes in
/// the bit length tree.
fn scan_tree(s: &mut DeflateState, tree: &mut [CtData], max_code: i32) {
    let max_code = max_code as usize;
    let mut prevlen: i32 = -1; // last emitted length
    let mut nextlen = i32::from(tree[0].dl); // length of next code
    let mut count = 0; // repeat count of the current code
    let mut max_count = 7; // max repeat count
    let mut min_count = 4; // min repeat count

    if nextlen == 0 {
        max_count = 138;
        min_count = 3;
    }
    tree[max_code + 1].dl = 0xffff; // guard

    for n in 0..=max_code {
        let curlen = nextlen;
        nextlen = i32::from(tree[n + 1].dl);
        count += 1;
        if count < max_count && curlen == nextlen {
            continue;
        } else if count < min_count {
            s.bl_tree[curlen as usize].fc += count as u16;
        } else if curlen != 0 {
            if curlen != prevlen {
                s.bl_tree[curlen as usize].fc += 1;
            }
            s.bl_tree[REP_3_6].fc += 1;
        } else if count <= 10 {
            s.bl_tree[REPZ_3_10].fc += 1;
        } else {
            s.bl_tree[REPZ_11_138].fc += 1;
        }
        count = 0;
        prevlen = curlen;
        if nextlen == 0 {
            max_count = 138;
            min_count = 3;
        } else if curlen == nextlen {
            max_count = 6;
            min_count = 3;
        } else {
            max_count = 7;
            min_count = 4;
        }
    }
}

/// `send_tree`: send a literal or distance tree in compressed form, using the codes in
/// bl_tree.
fn send_tree(s: &mut DeflateState, tree: &[CtData], max_code: usize) {
    let mut prevlen: i32 = -1; // last emitted length
    let mut nextlen = i32::from(tree[0].dl); // length of next code
    let mut count = 0; // repeat count of the current code
    let mut max_count = 7; // max repeat count
    let mut min_count = 4; // min repeat count

    // tree[max_code + 1].Len = -1; guard already set
    if nextlen == 0 {
        max_count = 138;
        min_count = 3;
    }

    for n in 0..=max_code {
        let curlen = nextlen;
        nextlen = i32::from(tree[n + 1].dl);
        count += 1;
        if count < max_count && curlen == nextlen {
            continue;
        } else if count < min_count {
            loop {
                send_code!(s, curlen as usize, s.bl_tree);
                count -= 1;
                if count == 0 {
                    break;
                }
            }
        } else if curlen != 0 {
            if curlen != prevlen {
                send_code!(s, curlen as usize, s.bl_tree);
                count -= 1;
            }
            zassert!((3..=6).contains(&count), " 3_6?");
            send_code!(s, REP_3_6, s.bl_tree);
            send_bits(s, count - 3, 2);
        } else if count <= 10 {
            send_code!(s, REPZ_3_10, s.bl_tree);
            send_bits(s, count - 3, 3);
        } else {
            send_code!(s, REPZ_11_138, s.bl_tree);
            send_bits(s, count - 11, 7);
        }
        count = 0;
        prevlen = curlen;
        if nextlen == 0 {
            max_count = 138;
            min_count = 3;
        } else if curlen == nextlen {
            max_count = 6;
            min_count = 3;
        } else {
            max_count = 7;
            min_count = 4;
        }
    }
}

/// `build_bl_tree`: construct the Huffman tree for the bit lengths and return the index in
/// bl_order of the last bit length code to send.
fn build_bl_tree(s: &mut DeflateState) -> usize {
    // Determine the bit length frequencies for literal and distance trees
    let mut ltree = core::mem::take(&mut s.dyn_ltree);
    scan_tree(s, &mut ltree, s.l_desc.max_code);
    s.dyn_ltree = ltree;
    let mut dtree = core::mem::take(&mut s.dyn_dtree);
    scan_tree(s, &mut dtree, s.d_desc.max_code);
    s.dyn_dtree = dtree;

    // Build the bit length tree:
    build_tree(s, Tree::Bl);
    // opt_len now includes the length of the tree representations, except the lengths of
    // the bit lengths codes and the 5 + 5 + 4 bits for the counts.

    // Determine the number of bit length codes to send. The pkzip format requires that at
    // least 4 bit length codes be sent. (appnote.txt says 3 but the actual value used is 4.)
    let mut max_blindex = BL_CODES - 1;
    while max_blindex >= 3 {
        if s.bl_tree[usize::from(bl_order[max_blindex])].dl != 0 {
            break;
        }
        max_blindex -= 1;
    }
    // Update opt_len to include the bit length tree and counts
    s.opt_len = s
        .opt_len
        .wrapping_add(3 * (max_blindex as u64 + 1) + 5 + 5 + 4);

    max_blindex
}

/// `send_all_trees`: send the header for a block using dynamic Huffman trees: the counts,
/// the lengths of the bit length codes, the literal tree and the distance tree. IN
/// assertion: lcodes >= 257, dcodes >= 1, blcodes >= 4.
fn send_all_trees(s: &mut DeflateState, lcodes: usize, dcodes: usize, blcodes: usize) {
    zassert!(
        lcodes >= 257 && dcodes >= 1 && blcodes >= 4,
        "not enough codes"
    );
    zassert!(
        lcodes <= L_CODES && dcodes <= D_CODES && blcodes <= BL_CODES,
        "too many codes"
    );
    send_bits(s, lcodes as u32 - 257, 5); // not +255 as stated in appnote.txt
    send_bits(s, dcodes as u32 - 1, 5);
    send_bits(s, blcodes as u32 - 4, 4); // not -3 as stated in appnote.txt
    for &order in &bl_order[..blcodes] {
        let len = s.bl_tree[usize::from(order)].dl;
        send_bits(s, u32::from(len), 3);
    }

    let ltree = core::mem::take(&mut s.dyn_ltree);
    send_tree(s, &ltree, lcodes - 1); // literal tree
    s.dyn_ltree = ltree;

    let dtree = core::mem::take(&mut s.dyn_dtree);
    send_tree(s, &dtree, dcodes - 1); // distance tree
    s.dyn_dtree = dtree;
}

/// `_tr_stored_block`: send a stored block of `stored_len` bytes of the window from offset
/// `buf` (`None`, the C's NULL, only with `stored_len == 0`).
pub(crate) fn _tr_stored_block(
    s: &mut DeflateState,
    buf: Option<usize>,
    stored_len: usize,
    last: bool,
) {
    send_bits(s, ((STORED_BLOCK as u32) << 1) + u32::from(last), 3); // send block type
    bi_windup(s); // align on byte boundary
    put_short(s, stored_len as u16);
    put_short(s, !stored_len as u16);
    if let Some(buf) = buf
        && stored_len != 0
    {
        let p = s.pending;
        s.pending_buf[p..p + stored_len].copy_from_slice(&s.window[buf..buf + stored_len]);
    }
    s.pending += stored_len;
}

/// `_tr_flush_bits`: flush the bits in the bit buffer to pending output (leaves at most 7
/// bits).
pub(crate) fn _tr_flush_bits(s: &mut DeflateState) {
    bi_flush(s);
}

/// `_tr_align`: send one empty static block to give enough lookahead for inflate. This takes
/// 10 bits, of which 7 may remain in the bit buffer.
pub(crate) fn _tr_align(s: &mut DeflateState) {
    send_bits(s, (STATIC_TREES as u32) << 1, 3);
    send_code!(s, END_BLOCK, static_ltree);
    bi_flush(s);
}

/// `compress_block`: send the block data compressed using the given Huffman trees.
fn compress_block(s: &mut DeflateState, ltree: &[CtData], dtree: &[CtData]) {
    let mut sx = 0; // running index in symbol buffers

    if s.sym_next != 0 {
        loop {
            let sb = s.sym_buf;
            let mut dist = usize::from(s.pending_buf[sb + sx]); // distance of matched string
            dist += usize::from(s.pending_buf[sb + sx + 1]) << 8;
            let mut lc = usize::from(s.pending_buf[sb + sx + 2]); // match length or unmatched char
            sx += 3;
            if dist == 0 {
                send_code!(s, lc, ltree); // send a literal byte
            } else {
                // Here, lc is the match length - MIN_MATCH
                let mut code = usize::from(_length_code[lc]); // the code to send
                send_code!(s, code + LITERALS + 1, ltree); // send length code
                let mut extra = extra_lbits[code]; // number of extra bits to send
                if extra != 0 {
                    lc -= base_length[code] as usize;
                    send_bits(s, lc as u32, extra); // send the extra length bits
                }
                dist -= 1; // dist is now the match distance - 1
                code = d_code(dist);
                zassert!(code < D_CODES, "bad d_code");

                send_code!(s, code, dtree); // send the distance code
                extra = extra_dbits[code];
                if extra != 0 {
                    dist -= base_dist[code] as usize;
                    send_bits(s, dist as u32, extra); // send the extra bits
                }
            } // literal or match pair ?

            // Check for no overlay of pending_buf on needed symbols
            zassert!(s.pending < s.lit_bufsize + sx, "pendingBuf overflow");

            if sx >= s.sym_next {
                break;
            }
        }
    }

    send_code!(s, END_BLOCK, ltree);
}

/// `detect_data_type`: check if the data type is TEXT or BINARY, using the following
/// algorithm:
/// - TEXT if the two conditions below are satisfied:
///   a) There are no non-portable control characters belonging to the "block list" (0..6,
///   14..25, 28..31).
///   b) There is at least one printable character belonging to the "allow list" (9 {TAB},
///   10 {LF}, 13 {CR}, 32..255).
/// - BINARY otherwise.
/// - The following partially-portable control characters form a "gray list" that is ignored
///   in this detection algorithm: (7 {BEL}, 8 {BS}, 11 {VT}, 12 {FF}, 26 {SUB}, 27 {ESC}).
///
/// IN assertion: the fields Freq of dyn_ltree are set.
fn detect_data_type(s: &DeflateState) -> i32 {
    // block_mask is the bit mask of block-listed bytes set bits 0..6, 14..25, and 28..31
    // 0xf3ffc07f = binary 11110011111111111100000001111111
    let mut block_mask: u32 = 0xf3ff_c07f;

    // Check for non-textual ("block-listed") bytes.
    for n in 0..=31 {
        if (block_mask & 1) != 0 && s.dyn_ltree[n].fc != 0 {
            return Z_BINARY;
        }
        block_mask >>= 1;
    }

    // Check for textual ("allow-listed") bytes.
    if s.dyn_ltree[9].fc != 0 || s.dyn_ltree[10].fc != 0 || s.dyn_ltree[13].fc != 0 {
        return Z_TEXT;
    }
    if s.dyn_ltree[32..LITERALS].iter().any(|ct| ct.fc != 0) {
        return Z_TEXT;
    }

    // There are no "block-listed" or "allow-listed" bytes: this stream either is empty or
    // has tolerated ("gray-listed") bytes only.
    Z_BINARY
}

/// `_tr_flush_block`: determine the best encoding for the current block: dynamic trees,
/// static trees or store, and write out the encoded block. `buf` is the window offset of the
/// block's input (`None`: no longer in the window), `data_type` the stream's.
pub(crate) fn _tr_flush_block(
    s: &mut DeflateState,
    data_type: &mut i32,
    buf: Option<usize>,
    stored_len: u64,
    last: bool,
) {
    let mut opt_lenb; // opt_len in bytes
    let static_lenb; // static_len in bytes
    let mut max_blindex = 0; // index of last bit length code of non zero freq

    // Build the Huffman trees unless a stored block is forced
    if s.level > 0 {
        // Check if the file is binary or text
        if *data_type == Z_UNKNOWN {
            *data_type = detect_data_type(s);
        }

        // Construct the literal and distance trees
        build_tree(s, Tree::L);
        build_tree(s, Tree::D);
        // At this point, opt_len and static_len are the total bit lengths of the compressed
        // block data, excluding the tree representations.

        // Build the bit length tree for the above two trees, and get the index in bl_order of
        // the last bit length code to send.
        max_blindex = build_bl_tree(s);

        // Determine the best encoding. Compute the block lengths in bytes.
        opt_lenb = s.opt_len.wrapping_add(3 + 7) >> 3;
        static_lenb = s.static_len.wrapping_add(3 + 7) >> 3;

        if static_lenb <= opt_lenb || s.strategy == Z_FIXED {
            opt_lenb = static_lenb;
        }
    } else {
        zassert!(buf.is_some(), "lost buf");
        opt_lenb = stored_len + 5; // force a stored block
        static_lenb = opt_lenb;
    }

    if stored_len + 4 <= opt_lenb && buf.is_some() {
        // 4: two words for the lengths
        // The test buf != NULL is only necessary if LIT_BUFSIZE > WSIZE. Otherwise we can't
        // have processed more than WSIZE input bytes since the last block flush, because
        // compression would have been successful. If LIT_BUFSIZE <= WSIZE, it is never too
        // late to transform a block into a stored block.
        _tr_stored_block(s, buf, stored_len as usize, last);
    } else if static_lenb == opt_lenb {
        send_bits(s, ((STATIC_TREES as u32) << 1) + u32::from(last), 3);
        compress_block(s, &static_ltree, &static_dtree);
    } else {
        send_bits(s, ((DYN_TREES as u32) << 1) + u32::from(last), 3);
        send_all_trees(
            s,
            (s.l_desc.max_code + 1) as usize,
            (s.d_desc.max_code + 1) as usize,
            max_blindex + 1,
        );
        let ltree = core::mem::take(&mut s.dyn_ltree);
        let dtree = core::mem::take(&mut s.dyn_dtree);
        compress_block(s, &ltree, &dtree);
        s.dyn_ltree = ltree;
        s.dyn_dtree = dtree;
    }
    init_block(s);

    if last {
        bi_windup(s);
    }
}

/// `_tr_tally`: save the match info and tally the frequency counts. Return true if the
/// current block must be flushed. `dist` is the distance of the matched string (0 for a
/// literal), `lc` the match length - MIN_MATCH or the unmatched char.
#[cfg_attr(not(test), allow(dead_code))] // the kernel build uses _tr_tally_lit/_tr_tally_dist
pub(crate) fn _tr_tally(s: &mut DeflateState, dist: usize, lc: usize) -> bool {
    let sb = s.sym_buf;
    s.pending_buf[sb + s.sym_next] = dist as u8;
    s.pending_buf[sb + s.sym_next + 1] = (dist >> 8) as u8;
    s.pending_buf[sb + s.sym_next + 2] = lc as u8;
    s.sym_next += 3;
    if dist == 0 {
        // lc is the unmatched char
        s.dyn_ltree[lc].fc += 1;
    } else {
        s.matches += 1;
        // Here, lc is the match length - MIN_MATCH
        let dist = dist - 1; // dist = match distance - 1
        zassert!(
            dist < crate::deflate::MAX_DIST(s)
                && lc <= MAX_MATCH - MIN_MATCH
                && d_code(dist) < D_CODES,
            "_tr_tally: bad match"
        );

        s.dyn_ltree[usize::from(_length_code[lc]) + LITERALS + 1].fc += 1;
        s.dyn_dtree[d_code(dist)].fc += 1;
    }
    s.sym_next == s.sym_end
}
/* </CODE> */

/* <TESTS> */
#[cfg(test)]
mod tests {
    // Tests of the Huffman half of deflate. The table values are those of zlib's `trees.h`; the
    // `#[ignore]` test (`just test-ref`) compares every table with the header in the reference
    // tree. Expected bit streams were checked against Python's zlib 1.2.12
    // (`zlib.compressobj(1, zlib.DEFLATED, -15)`).

    use super::*;
    use std::vec::Vec;

    /// A fresh state as `deflateInit2_` allocates it (32K window, memLevel 8), trees initialised.
    fn state(level: i32) -> std::boxed::Box<DeflateState> {
        let mut s = std::boxed::Box::new(DeflateState::alloc(15, 15, 1 << 14).unwrap());
        s.level = level;
        _tr_init(&mut s);
        s
    }

    #[test]
    fn static_ltree_matches_trees_h() {
        // first entries, the 9-bit range, the 7-bit range and the last entries of trees.h
        assert_eq!(static_ltree[0], CtData::new(12, 8));
        assert_eq!(static_ltree[1], CtData::new(140, 8));
        assert_eq!(static_ltree[143], CtData::new(253, 8));
        assert_eq!(static_ltree[144], CtData::new(19, 9));
        assert_eq!(static_ltree[255], CtData::new(511, 9));
        assert_eq!(static_ltree[256], CtData::new(0, 7));
        assert_eq!(static_ltree[279], CtData::new(116, 7));
        assert_eq!(static_ltree[280], CtData::new(3, 8));
        assert_eq!(static_ltree[287], CtData::new(227, 8));
    }

    #[test]
    fn static_dtree_matches_trees_h() {
        let codes = [
            0, 16, 8, 24, 4, 20, 12, 28, 2, 18, 10, 26, 6, 22, 14, 30, 1, 17, 9, 25, 5, 21, 13, 29,
            3, 19, 11, 27, 7, 23,
        ];
        for (n, &c) in codes.iter().enumerate() {
            assert_eq!(static_dtree[n], CtData::new(c, 5), "static_dtree[{n}]");
        }
    }

    #[test]
    fn code_tables_match_trees_h() {
        assert_eq!(
            &_dist_code[..20],
            &[0, 1, 2, 3, 4, 4, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8]
        );
        assert_eq!(&_dist_code[255..260], &[15, 0, 0, 16, 17]);
        assert_eq!(_dist_code[511], 29);
        assert_eq!(&_length_code[..12], &[0, 1, 2, 3, 4, 5, 6, 7, 8, 8, 9, 9]);
        assert_eq!(&_length_code[252..], &[27, 27, 27, 28]);
        assert_eq!(
            base_length,
            [
                0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 14, 16, 20, 24, 28, 32, 40, 48, 56, 64, 80, 96,
                112, 128, 160, 192, 224, 0
            ]
        );
        assert_eq!(
            base_dist,
            [
                0, 1, 2, 3, 4, 6, 8, 12, 16, 24, 32, 48, 64, 96, 128, 192, 256, 384, 512, 768,
                1024, 1536, 2048, 3072, 4096, 6144, 8192, 12288, 16384, 24576
            ]
        );
    }

    /// The numbers of one table of `trees.h`: everything between `<name>[...] = {` and `};`.
    fn trees_h_table(text: &str, name: &str) -> Vec<u32> {
        let start = text.find(name).unwrap();
        let body = &text[start..];
        let open = body.find("= {").unwrap() + 3;
        let close = body.find("};").unwrap();
        body[open..close]
            .split(|c: char| !c.is_ascii_digit())
            .filter(|t| !t.is_empty())
            .map(|t| t.parse().unwrap())
            .collect()
    }

    #[test]
    #[ignore = "reads trees.h from $OPENBSD_SRC (just test-ref)"]
    fn every_table_matches_trees_h() {
        let root = match std::env::var_os("OPENBSD_SRC") {
            Some(dir) => std::path::PathBuf::from(dir),
            None => panic!("OPENBSD_SRC is not set; run `just test-ref`"),
        };
        let root = if root.is_absolute() {
            root
        } else {
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../..")
                .join(root)
        };
        let text = std::fs::read_to_string(root.join("sys/lib/libz/trees.h")).unwrap();

        let flat = |t: &[CtData]| -> Vec<u32> {
            t.iter()
                .flat_map(|ct| [u32::from(ct.fc), u32::from(ct.dl)])
                .collect()
        };
        assert_eq!(trees_h_table(&text, "static_ltree"), flat(&static_ltree));
        assert_eq!(trees_h_table(&text, "static_dtree"), flat(&static_dtree));
        let bytes = |t: &[u8]| -> Vec<u32> { t.iter().map(|&b| u32::from(b)).collect() };
        assert_eq!(trees_h_table(&text, "_dist_code"), bytes(&_dist_code));
        assert_eq!(trees_h_table(&text, "_length_code"), bytes(&_length_code));
        assert_eq!(trees_h_table(&text, "base_length"), base_length.to_vec());
        assert_eq!(trees_h_table(&text, "base_dist"), base_dist.to_vec());
    }

    #[test]
    fn bi_reverse_reverses_the_low_bits() {
        assert_eq!(bi_reverse(0b1, 1), 0b1);
        assert_eq!(bi_reverse(0b110, 3), 0b011);
        assert_eq!(bi_reverse(0b10011, 5), 0b11001);
        assert_eq!(bi_reverse(0x7fff, 15), 0x7fff);
        assert_eq!(bi_reverse(1, 15), 0x4000);
    }

    #[test]
    fn send_bits_packs_lsb_first() {
        let mut s = state(6);
        send_bits(&mut s, 0b101, 3);
        send_bits(&mut s, 0x1fff, 13); // exactly fills bi_buf
        assert_eq!(s.bi_valid, 16);
        assert_eq!(s.pending, 0);
        send_bits(&mut s, 0b11, 2); // spills: put_short, keep 2 bits
        assert_eq!(&s.pending_buf[..2], &[0xfd, 0xff]);
        assert_eq!((s.bi_buf, s.bi_valid), (0b11, 2));
        bi_windup(&mut s);
        assert_eq!(s.pending_buf[2], 0b11);
        assert_eq!((s.bi_valid, s.bi_used), (0, 2));
    }

    #[test]
    fn align_sends_an_empty_static_block() {
        let mut s = state(6);
        _tr_align(&mut s);
        // 3 bits of block type (010) and the 7-bit END_BLOCK code (0000000): one byte out, two
        // bits kept.
        assert_eq!(s.pending, 1);
        assert_eq!(s.pending_buf[0], 0x02);
        assert_eq!(s.bi_valid, 2);
    }

    #[test]
    fn one_literal_makes_a_fixed_block() {
        // Python: zlib.compressobj(1, zlib.DEFLATED, -15).compress(b"a") + flush() == 4b 04 00
        let mut s = state(1);
        s.window[0] = b'a';
        assert!(!_tr_tally(&mut s, 0, usize::from(b'a')));
        let mut data_type = Z_UNKNOWN;
        _tr_flush_block(&mut s, &mut data_type, Some(0), 1, true);
        assert_eq!(&s.pending_buf[..s.pending], &[0x4b, 0x04, 0x00]);
        assert_eq!(data_type, Z_TEXT);
        assert_eq!(s.sym_next, 0); // init_block ran
    }

    #[test]
    fn incompressible_block_is_stored() {
        // 16 distinct 9-bit literals cost as much as storing them.
        let mut s = state(6);
        for n in 0..16u8 {
            s.window[usize::from(n)] = 200 + n;
            _tr_tally(&mut s, 0, usize::from(200 + n));
        }
        let mut data_type = Z_UNKNOWN;
        _tr_flush_block(&mut s, &mut data_type, Some(0), 16, true);
        assert_eq!(data_type, Z_TEXT); // 32..255 are allow-listed
        // Python: zlib.compressobj(6, zlib.DEFLATED, -15) gives the same stored block:
        // header byte 01, LEN 16, NLEN, then the bytes: header byte 01, LEN 16, NLEN, then the bytes
        assert_eq!(&s.pending_buf[..5], &[0x01, 0x10, 0x00, 0xef, 0xff]);
        assert_eq!(&s.pending_buf[5..s.pending], &s.window[..16]);
        // without the window bytes (buf NULL), it is compressed instead
        let mut s = state(6);
        for n in 0..16u8 {
            _tr_tally(&mut s, 0, usize::from(200 + n));
        }
        let mut data_type = Z_UNKNOWN;
        s.dyn_ltree[1].fc = 1; // a block-listed byte makes it binary
        _tr_flush_block(&mut s, &mut data_type, None, 16, true);
        assert_eq!(data_type, Z_BINARY);
        assert_ne!(s.pending_buf[0] & 0x06, 0);
    }

    #[test]
    fn tally_counts_matches_and_reports_a_full_buffer() {
        let mut s = state(6);
        s.sym_end = 6;
        assert!(!_tr_tally(&mut s, 0, 7));
        assert!(_tr_tally(&mut s, 1, 0)); // a match of MIN_MATCH at distance 1
        assert_eq!(s.matches, 1);
        assert_eq!(s.dyn_ltree[7].fc, 1);
        assert_eq!(s.dyn_ltree[LITERALS + 1].fc, 1);
        assert_eq!(s.dyn_dtree[0].fc, 1);
        let sb = s.sym_buf;
        assert_eq!(&s.pending_buf[sb..sb + 6], &[0, 0, 7, 1, 0, 0]);
    }

    #[test]
    fn overflowing_bit_lengths_are_limited() {
        // Fibonacci frequencies would need 18-bit codes; the bit length tree allows 7.
        let mut s = state(6);
        let (mut a, mut b) = (1u16, 1u16);
        for n in 0..BL_CODES {
            s.bl_tree[n].fc = a;
            (a, b) = (b, a + b);
        }
        build_tree(&mut s, Tree::Bl);
        let lens: Vec<u16> = s.bl_tree[..BL_CODES].iter().map(|ct| ct.dl).collect();
        assert!(lens.iter().all(|&l| (1..=7).contains(&l)), "{lens:?}");
        let kraft: u32 = lens.iter().map(|&l| 1u32 << (7 - l)).sum();
        assert_eq!(kraft, 1 << 7, "the code is complete");
        assert_eq!(s.bl_desc.max_code, BL_CODES as i32 - 1);
        // the codes are a prefix code: no code is a prefix of another (codes are bit-reversed)
        for i in 0..BL_CODES {
            for j in 0..BL_CODES {
                if i != j && lens[i] <= lens[j] {
                    let mask = (1u16 << lens[i]) - 1;
                    assert_ne!(s.bl_tree[i].fc, s.bl_tree[j].fc & mask, "{i} prefixes {j}");
                }
            }
        }
    }

    #[test]
    fn a_single_symbol_still_gets_two_codes() {
        let mut s = state(6);
        s.dyn_dtree[5].fc = 3;
        build_tree(&mut s, Tree::D);
        assert_eq!(s.d_desc.max_code, 5);
        assert_eq!(s.dyn_dtree[5].dl, 1);
        assert_eq!(s.dyn_dtree[0].dl, 1); // forced second code
    }
}
/* </TESTS> */
