/*	$OpenBSD: syscall.h,v 1.286 2026/08/12 15:05:21 naddy Exp $	*/

/* <LICENSES> */
/*
 * Copyright (c) 2026 Emilio Navarrete Lineros <enavarre@outlook.com>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
/* </LICENSES> */

/* <CODE> */
//! `<sys/syscall.h>`: system call numbers.
//!
//! DO NOT EDIT: this file is automatically generated by `cargo xtask gen-syscalls`
//! (`tools/xtask/src/syscalls.rs`, what `kern/makesyscalls.sh` does for the C tree)
//! from `sys/kern/syscalls.master`.
//! created from; OpenBSD: syscalls.master,v 1.273 2026/08/12 15:04:45 naddy Exp
//!
//! Upstream: sys/sys/syscall.h @ 3ce1f3f79392

#![allow(non_upper_case_globals)] // the C names: SYS_write

/// syscall: "exit" ret: "void" args: "int"
pub const SYS_exit: i32 = 1;

/// syscall: "fork" ret: "int" args:
pub const SYS_fork: i32 = 2;

/// syscall: "read" ret: "ssize_t" args: "int" "void *" "size_t"
pub const SYS_read: i32 = 3;

/// syscall: "write" ret: "ssize_t" args: "int" "const void *" "size_t"
pub const SYS_write: i32 = 4;

/// syscall: "open" ret: "int" args: "const char *" "int" "..." "mode_t"
pub const SYS_open: i32 = 5;

/// syscall: "close" ret: "int" args: "int"
pub const SYS_close: i32 = 6;

/// syscall: "getentropy" ret: "int" args: "void *" "size_t"
pub const SYS_getentropy: i32 = 7;

/// syscall: "__tfork" ret: "int" args: "const struct __tfork *" "size_t"
pub const SYS___tfork: i32 = 8;

/// syscall: "link" ret: "int" args: "const char *" "const char *"
pub const SYS_link: i32 = 9;

/// syscall: "unlink" ret: "int" args: "const char *"
pub const SYS_unlink: i32 = 10;

/// syscall: "wait4" ret: "pid_t" args: "pid_t" "int *" "int" "struct rusage *"
pub const SYS_wait4: i32 = 11;

/// syscall: "chdir" ret: "int" args: "const char *"
pub const SYS_chdir: i32 = 12;

/// syscall: "fchdir" ret: "int" args: "int"
pub const SYS_fchdir: i32 = 13;

/// syscall: "mknod" ret: "int" args: "const char *" "mode_t" "dev_t"
pub const SYS_mknod: i32 = 14;

/// syscall: "chmod" ret: "int" args: "const char *" "mode_t"
pub const SYS_chmod: i32 = 15;

/// syscall: "chown" ret: "int" args: "const char *" "uid_t" "gid_t"
pub const SYS_chown: i32 = 16;

/// syscall: "break" ret: "int" args: "char *"
pub const SYS_break: i32 = 17;

/// syscall: "getdtablecount" ret: "int" args:
pub const SYS_getdtablecount: i32 = 18;

/// syscall: "getrusage" ret: "int" args: "int" "struct rusage *"
pub const SYS_getrusage: i32 = 19;

/// syscall: "getpid" ret: "pid_t" args:
pub const SYS_getpid: i32 = 20;

/// syscall: "mount" ret: "int" args: "const char *" "const char *" "int" "void *"
pub const SYS_mount: i32 = 21;

/// syscall: "unmount" ret: "int" args: "const char *" "int"
pub const SYS_unmount: i32 = 22;

/// syscall: "setuid" ret: "int" args: "uid_t"
pub const SYS_setuid: i32 = 23;

/// syscall: "getuid" ret: "uid_t" args:
pub const SYS_getuid: i32 = 24;

/// syscall: "geteuid" ret: "uid_t" args:
pub const SYS_geteuid: i32 = 25;

/// syscall: "recvmsg" ret: "ssize_t" args: "int" "struct msghdr *" "int"
pub const SYS_recvmsg: i32 = 27;

/// syscall: "sendmsg" ret: "ssize_t" args: "int" "const struct msghdr *" "int"
pub const SYS_sendmsg: i32 = 28;

/// syscall: "recvfrom" ret: "ssize_t" args: "int" "void *" "size_t" "int" "struct sockaddr *" "socklen_t *"
pub const SYS_recvfrom: i32 = 29;

/// syscall: "accept" ret: "int" args: "int" "struct sockaddr *" "socklen_t *"
pub const SYS_accept: i32 = 30;

/// syscall: "getpeername" ret: "int" args: "int" "struct sockaddr *" "socklen_t *"
pub const SYS_getpeername: i32 = 31;

/// syscall: "getsockname" ret: "int" args: "int" "struct sockaddr *" "socklen_t *"
pub const SYS_getsockname: i32 = 32;

/// syscall: "access" ret: "int" args: "const char *" "int"
pub const SYS_access: i32 = 33;

/// syscall: "chflags" ret: "int" args: "const char *" "u_int"
pub const SYS_chflags: i32 = 34;

/// syscall: "fchflags" ret: "int" args: "int" "u_int"
pub const SYS_fchflags: i32 = 35;

/// syscall: "sync" ret: "void" args:
pub const SYS_sync: i32 = 36;

// 37 is obsolete msyscall

/// syscall: "stat" ret: "int" args: "const char *" "struct stat *"
pub const SYS_stat: i32 = 38;

/// syscall: "getppid" ret: "pid_t" args:
pub const SYS_getppid: i32 = 39;

/// syscall: "lstat" ret: "int" args: "const char *" "struct stat *"
pub const SYS_lstat: i32 = 40;

/// syscall: "dup" ret: "int" args: "int"
pub const SYS_dup: i32 = 41;

/// syscall: "fstatat" ret: "int" args: "int" "const char *" "struct stat *" "int"
pub const SYS_fstatat: i32 = 42;

/// syscall: "getegid" ret: "gid_t" args:
pub const SYS_getegid: i32 = 43;

/// syscall: "sigaction" ret: "int" args: "int" "const struct sigaction *" "struct sigaction *"
pub const SYS_sigaction: i32 = 46;

/// syscall: "getgid" ret: "gid_t" args:
pub const SYS_getgid: i32 = 47;

/// syscall: "sigprocmask" ret: "int" args: "int" "sigset_t"
pub const SYS_sigprocmask: i32 = 48;

/// syscall: "mmap" ret: "void *" args: "void *" "size_t" "int" "int" "int" "off_t"
pub const SYS_mmap: i32 = 49;

/// syscall: "setlogin" ret: "int" args: "const char *"
pub const SYS_setlogin: i32 = 50;

/// syscall: "acct" ret: "int" args: "const char *"
pub const SYS_acct: i32 = 51;

/// syscall: "sigpending" ret: "int" args:
pub const SYS_sigpending: i32 = 52;

/// syscall: "fstat" ret: "int" args: "int" "struct stat *"
pub const SYS_fstat: i32 = 53;

/// syscall: "ioctl" ret: "int" args: "int" "u_long" "..." "void *"
pub const SYS_ioctl: i32 = 54;

/// syscall: "reboot" ret: "int" args: "int"
pub const SYS_reboot: i32 = 55;

/// syscall: "revoke" ret: "int" args: "const char *"
pub const SYS_revoke: i32 = 56;

/// syscall: "symlink" ret: "int" args: "const char *" "const char *"
pub const SYS_symlink: i32 = 57;

/// syscall: "readlink" ret: "ssize_t" args: "const char *" "char *" "size_t"
pub const SYS_readlink: i32 = 58;

/// syscall: "execve" ret: "int" args: "const char *" "char *const *" "char *const *"
pub const SYS_execve: i32 = 59;

/// syscall: "umask" ret: "mode_t" args: "mode_t"
pub const SYS_umask: i32 = 60;

/// syscall: "chroot" ret: "int" args: "const char *"
pub const SYS_chroot: i32 = 61;

/// syscall: "getfsstat" ret: "int" args: "struct statfs *" "size_t" "int"
pub const SYS_getfsstat: i32 = 62;

/// syscall: "statfs" ret: "int" args: "const char *" "struct statfs *"
pub const SYS_statfs: i32 = 63;

/// syscall: "fstatfs" ret: "int" args: "int" "struct statfs *"
pub const SYS_fstatfs: i32 = 64;

/// syscall: "fhstatfs" ret: "int" args: "const fhandle_t *" "struct statfs *"
pub const SYS_fhstatfs: i32 = 65;

/// syscall: "vfork" ret: "int" args:
pub const SYS_vfork: i32 = 66;

/// syscall: "gettimeofday" ret: "int" args: "struct timeval *" "struct timezone *"
pub const SYS_gettimeofday: i32 = 67;

/// syscall: "settimeofday" ret: "int" args: "const struct timeval *" "const struct timezone *"
pub const SYS_settimeofday: i32 = 68;

/// syscall: "setitimer" ret: "int" args: "int" "const struct itimerval *" "struct itimerval *"
pub const SYS_setitimer: i32 = 69;

/// syscall: "getitimer" ret: "int" args: "int" "struct itimerval *"
pub const SYS_getitimer: i32 = 70;

/// syscall: "select" ret: "int" args: "int" "fd_set *" "fd_set *" "fd_set *" "struct timeval *"
pub const SYS_select: i32 = 71;

/// syscall: "kevent" ret: "int" args: "int" "const struct kevent *" "int" "struct kevent *" "int" "const struct timespec *"
pub const SYS_kevent: i32 = 72;

/// syscall: "munmap" ret: "int" args: "void *" "size_t"
pub const SYS_munmap: i32 = 73;

/// syscall: "mprotect" ret: "int" args: "void *" "size_t" "int"
pub const SYS_mprotect: i32 = 74;

/// syscall: "madvise" ret: "int" args: "void *" "size_t" "int"
pub const SYS_madvise: i32 = 75;

/// syscall: "utimes" ret: "int" args: "const char *" "const struct timeval *"
pub const SYS_utimes: i32 = 76;

/// syscall: "futimes" ret: "int" args: "int" "const struct timeval *"
pub const SYS_futimes: i32 = 77;

/// syscall: "mquery" ret: "void *" args: "void *" "size_t" "int" "int" "int" "off_t"
pub const SYS_mquery: i32 = 78;

/// syscall: "getgroups" ret: "int" args: "int" "gid_t *"
pub const SYS_getgroups: i32 = 79;

/// syscall: "setgroups" ret: "int" args: "int" "const gid_t *"
pub const SYS_setgroups: i32 = 80;

/// syscall: "getpgrp" ret: "int" args:
pub const SYS_getpgrp: i32 = 81;

/// syscall: "setpgid" ret: "int" args: "pid_t" "pid_t"
pub const SYS_setpgid: i32 = 82;

/// syscall: "futex" ret: "int" args: "uint32_t *" "int" "int" "const struct timespec *" "uint32_t *"
pub const SYS_futex: i32 = 83;

/// syscall: "utimensat" ret: "int" args: "int" "const char *" "const struct timespec *" "int"
pub const SYS_utimensat: i32 = 84;

/// syscall: "futimens" ret: "int" args: "int" "const struct timespec *"
pub const SYS_futimens: i32 = 85;

/// syscall: "kbind" ret: "int" args: "const struct __kbind *" "size_t" "int64_t"
pub const SYS_kbind: i32 = 86;

/// syscall: "clock_gettime" ret: "int" args: "clockid_t" "struct timespec *"
pub const SYS_clock_gettime: i32 = 87;

/// syscall: "clock_settime" ret: "int" args: "clockid_t" "const struct timespec *"
pub const SYS_clock_settime: i32 = 88;

/// syscall: "clock_getres" ret: "int" args: "clockid_t" "struct timespec *"
pub const SYS_clock_getres: i32 = 89;

/// syscall: "dup2" ret: "int" args: "int" "int"
pub const SYS_dup2: i32 = 90;

/// syscall: "nanosleep" ret: "int" args: "const struct timespec *" "struct timespec *"
pub const SYS_nanosleep: i32 = 91;

/// syscall: "fcntl" ret: "int" args: "int" "int" "..." "void *"
pub const SYS_fcntl: i32 = 92;

/// syscall: "accept4" ret: "int" args: "int" "struct sockaddr *" "socklen_t *" "int"
pub const SYS_accept4: i32 = 93;

/// syscall: "__thrsleep" ret: "int" args: "const volatile void *" "clockid_t" "const struct timespec *" "void *" "const int *"
pub const SYS___thrsleep: i32 = 94;

/// syscall: "fsync" ret: "int" args: "int"
pub const SYS_fsync: i32 = 95;

/// syscall: "setpriority" ret: "int" args: "int" "id_t" "int"
pub const SYS_setpriority: i32 = 96;

/// syscall: "socket" ret: "int" args: "int" "int" "int"
pub const SYS_socket: i32 = 97;

/// syscall: "connect" ret: "int" args: "int" "const struct sockaddr *" "socklen_t"
pub const SYS_connect: i32 = 98;

/// syscall: "getdents" ret: "int" args: "int" "void *" "size_t"
pub const SYS_getdents: i32 = 99;

/// syscall: "getpriority" ret: "int" args: "int" "id_t"
pub const SYS_getpriority: i32 = 100;

/// syscall: "pipe2" ret: "int" args: "int *" "int"
pub const SYS_pipe2: i32 = 101;

/// syscall: "dup3" ret: "int" args: "int" "int" "int"
pub const SYS_dup3: i32 = 102;

/// syscall: "sigreturn" ret: "int" args: "struct sigcontext *"
pub const SYS_sigreturn: i32 = 103;

/// syscall: "bind" ret: "int" args: "int" "const struct sockaddr *" "socklen_t"
pub const SYS_bind: i32 = 104;

/// syscall: "setsockopt" ret: "int" args: "int" "int" "int" "const void *" "socklen_t"
pub const SYS_setsockopt: i32 = 105;

/// syscall: "listen" ret: "int" args: "int" "int"
pub const SYS_listen: i32 = 106;

/// syscall: "chflagsat" ret: "int" args: "int" "const char *" "u_int" "int"
pub const SYS_chflagsat: i32 = 107;

/// syscall: "pledge" ret: "int" args: "const char *" "const char *"
pub const SYS_pledge: i32 = 108;

/// syscall: "ppoll" ret: "int" args: "struct pollfd *" "u_int" "const struct timespec *" "const sigset_t *"
pub const SYS_ppoll: i32 = 109;

/// syscall: "pselect" ret: "int" args: "int" "fd_set *" "fd_set *" "fd_set *" "const struct timespec *" "const sigset_t *"
pub const SYS_pselect: i32 = 110;

/// syscall: "sigsuspend" ret: "int" args: "int"
pub const SYS_sigsuspend: i32 = 111;

/// syscall: "sendsyslog" ret: "int" args: "const char *" "size_t" "int"
pub const SYS_sendsyslog: i32 = 112;

/// syscall: "unveil" ret: "int" args: "const char *" "const char *"
pub const SYS_unveil: i32 = 114;

/// syscall: "__realpath" ret: "int" args: "const char *" "char *"
pub const SYS___realpath: i32 = 115;

/// syscall: "recvmmsg" ret: "int" args: "int" "struct mmsghdr *" "unsigned int" "int" "struct timespec *"
pub const SYS_recvmmsg: i32 = 116;

/// syscall: "sendmmsg" ret: "int" args: "int" "struct mmsghdr *" "unsigned int" "int"
pub const SYS_sendmmsg: i32 = 117;

/// syscall: "getsockopt" ret: "int" args: "int" "int" "int" "void *" "socklen_t *"
pub const SYS_getsockopt: i32 = 118;

/// syscall: "thrkill" ret: "int" args: "pid_t" "int" "void *"
pub const SYS_thrkill: i32 = 119;

/// syscall: "readv" ret: "ssize_t" args: "int" "const struct iovec *" "int"
pub const SYS_readv: i32 = 120;

/// syscall: "writev" ret: "ssize_t" args: "int" "const struct iovec *" "int"
pub const SYS_writev: i32 = 121;

/// syscall: "kill" ret: "int" args: "int" "int"
pub const SYS_kill: i32 = 122;

/// syscall: "fchown" ret: "int" args: "int" "uid_t" "gid_t"
pub const SYS_fchown: i32 = 123;

/// syscall: "fchmod" ret: "int" args: "int" "mode_t"
pub const SYS_fchmod: i32 = 124;

/// syscall: "__pledge_open" ret: "int" args: "const char *" "int" "..." "mode_t"
pub const SYS___pledge_open: i32 = 125;

/// syscall: "setreuid" ret: "int" args: "uid_t" "uid_t"
pub const SYS_setreuid: i32 = 126;

/// syscall: "setregid" ret: "int" args: "gid_t" "gid_t"
pub const SYS_setregid: i32 = 127;

/// syscall: "rename" ret: "int" args: "const char *" "const char *"
pub const SYS_rename: i32 = 128;

// 129 is obsolete otruncate

// 130 is obsolete oftruncate

/// syscall: "flock" ret: "int" args: "int" "int"
pub const SYS_flock: i32 = 131;

/// syscall: "mkfifo" ret: "int" args: "const char *" "mode_t"
pub const SYS_mkfifo: i32 = 132;

/// syscall: "sendto" ret: "ssize_t" args: "int" "const void *" "size_t" "int" "const struct sockaddr *" "socklen_t"
pub const SYS_sendto: i32 = 133;

/// syscall: "shutdown" ret: "int" args: "int" "int"
pub const SYS_shutdown: i32 = 134;

/// syscall: "socketpair" ret: "int" args: "int" "int" "int" "int *"
pub const SYS_socketpair: i32 = 135;

/// syscall: "mkdir" ret: "int" args: "const char *" "mode_t"
pub const SYS_mkdir: i32 = 136;

/// syscall: "rmdir" ret: "int" args: "const char *"
pub const SYS_rmdir: i32 = 137;

// 138 is obsolete t32_utimes

// 139 is obsolete 4.2 sigreturn

/// syscall: "adjtime" ret: "int" args: "const struct timeval *" "struct timeval *"
pub const SYS_adjtime: i32 = 140;

/// syscall: "getlogin_r" ret: "int" args: "char *" "size_t"
pub const SYS_getlogin_r: i32 = 141;

/// syscall: "getthrname" ret: "int" args: "pid_t" "char *" "size_t"
pub const SYS_getthrname: i32 = 142;

/// syscall: "setthrname" ret: "int" args: "pid_t" "const char *"
pub const SYS_setthrname: i32 = 143;

// 144 is obsolete ogetrlimit

// 145 is obsolete osetrlimit

// 146 is obsolete pinsyscall

/// syscall: "setsid" ret: "int" args:
pub const SYS_setsid: i32 = 147;

/// syscall: "quotactl" ret: "int" args: "const char *" "int" "int" "void *"
pub const SYS_quotactl: i32 = 148;

// 149 is obsolete oquota

/// syscall: "ypconnect" ret: "int" args: "int"
pub const SYS_ypconnect: i32 = 150;

/// syscall: "nfssvc" ret: "int" args: "int" "void *"
pub const SYS_nfssvc: i32 = 155;

// 156 is obsolete ogetdirentries

// 157 is obsolete statfs25

/// syscall: "pinsyscalls" ret: "int" args: "void *" "size_t" "u_int *" "int"
pub const SYS_pinsyscalls: i32 = 158;

/// syscall: "mimmutable" ret: "int" args: "void *" "size_t"
pub const SYS_mimmutable: i32 = 159;

/// syscall: "waitid" ret: "int" args: "int" "id_t" "siginfo_t *" "int"
pub const SYS_waitid: i32 = 160;

/// syscall: "getfh" ret: "int" args: "const char *" "fhandle_t *"
pub const SYS_getfh: i32 = 161;

// 162 is obsolete ogetdomainname

// 163 is obsolete osetdomainname

// 164 is obsolete __tmpfd

/// syscall: "sysarch" ret: "int" args: "int" "void *"
pub const SYS_sysarch: i32 = 165;

/// syscall: "lseek" ret: "off_t" args: "int" "off_t" "int"
pub const SYS_lseek: i32 = 166;

/// syscall: "truncate" ret: "int" args: "const char *" "off_t"
pub const SYS_truncate: i32 = 167;

/// syscall: "ftruncate" ret: "int" args: "int" "off_t"
pub const SYS_ftruncate: i32 = 168;

/// syscall: "pread" ret: "ssize_t" args: "int" "void *" "size_t" "off_t"
pub const SYS_pread: i32 = 169;

/// syscall: "pwrite" ret: "ssize_t" args: "int" "const void *" "size_t" "off_t"
pub const SYS_pwrite: i32 = 170;

/// syscall: "preadv" ret: "ssize_t" args: "int" "const struct iovec *" "int" "off_t"
pub const SYS_preadv: i32 = 171;

/// syscall: "pwritev" ret: "ssize_t" args: "int" "const struct iovec *" "int" "off_t"
pub const SYS_pwritev: i32 = 172;

// 173 is obsolete pad_pread

// 174 is obsolete pad_pwrite

/// syscall: "profil" ret: "int" args: "void *" "size_t" "size_t" "u_long" "u_int" "int"
pub const SYS_profil: i32 = 175;

/// syscall: "setgid" ret: "int" args: "gid_t"
pub const SYS_setgid: i32 = 181;

/// syscall: "setegid" ret: "int" args: "gid_t"
pub const SYS_setegid: i32 = 182;

/// syscall: "seteuid" ret: "int" args: "uid_t"
pub const SYS_seteuid: i32 = 183;

// 184 is obsolete lfs_bmapv

// 185 is obsolete lfs_markv

// 186 is obsolete lfs_segclean

// 187 is obsolete lfs_segwait

// 188 is obsolete stat35

// 189 is obsolete fstat35

/// syscall: "pathconfat" ret: "long" args: "int" "const char *" "int" "int"
pub const SYS_pathconfat: i32 = 190;

/// syscall: "pathconf" ret: "long" args: "const char *" "int"
pub const SYS_pathconf: i32 = 191;

/// syscall: "fpathconf" ret: "long" args: "int" "int"
pub const SYS_fpathconf: i32 = 192;

/// syscall: "swapctl" ret: "int" args: "int" "const void *" "int"
pub const SYS_swapctl: i32 = 193;

/// syscall: "getrlimit" ret: "int" args: "int" "struct rlimit *"
pub const SYS_getrlimit: i32 = 194;

/// syscall: "setrlimit" ret: "int" args: "int" "const struct rlimit *"
pub const SYS_setrlimit: i32 = 195;

// 196 is obsolete ogetdirentries48

// 197 is obsolete pad_mmap

// 198 is obsolete __syscall

// 199 is obsolete pad_lseek

// 200 is obsolete pad_truncate

// 201 is obsolete pad_ftruncate

/// syscall: "sysctl" ret: "int" args: "const int *" "u_int" "void *" "size_t *" "void *" "size_t"
pub const SYS_sysctl: i32 = 202;

/// syscall: "mlock" ret: "int" args: "const void *" "size_t"
pub const SYS_mlock: i32 = 203;

/// syscall: "munlock" ret: "int" args: "const void *" "size_t"
pub const SYS_munlock: i32 = 204;

// 206 is obsolete t32_futimes

/// syscall: "getpgid" ret: "pid_t" args: "pid_t"
pub const SYS_getpgid: i32 = 207;

// 208 is obsolete nnpfspioctl

/// syscall: "utrace" ret: "int" args: "const char *" "const void *" "size_t"
pub const SYS_utrace: i32 = 209;

// 222 is obsolete semop35

// 223 is obsolete semconfig35

// 231 is obsolete shmget35

// 232 is obsolete t32_clock_gettime

// 233 is obsolete t32_clock_settime

// 234 is obsolete t32_clock_getres

// 240 is obsolete t32_nanosleep

/// syscall: "minherit" ret: "int" args: "void *" "size_t" "int"
pub const SYS_minherit: i32 = 250;

// 251 is obsolete rfork

/// syscall: "poll" ret: "int" args: "struct pollfd *" "u_int" "int"
pub const SYS_poll: i32 = 252;

/// syscall: "issetugid" ret: "int" args:
pub const SYS_issetugid: i32 = 253;

/// syscall: "lchown" ret: "int" args: "const char *" "uid_t" "gid_t"
pub const SYS_lchown: i32 = 254;

/// syscall: "getsid" ret: "pid_t" args: "pid_t"
pub const SYS_getsid: i32 = 255;

/// syscall: "msync" ret: "int" args: "void *" "size_t" "int"
pub const SYS_msync: i32 = 256;

// 257 is obsolete semctl35

// 258 is obsolete shmctl35

// 259 is obsolete msgctl35

/// syscall: "pipe" ret: "int" args: "int *"
pub const SYS_pipe: i32 = 263;

/// syscall: "fhopen" ret: "int" args: "const fhandle_t *" "int"
pub const SYS_fhopen: i32 = 264;

// 267 is obsolete pad_preadv

// 268 is obsolete pad_pwritev

/// syscall: "kqueue" ret: "int" args:
pub const SYS_kqueue: i32 = 269;

/// syscall: "kqueue1" ret: "int" args: "int"
pub const SYS_kqueue1: i32 = 270;

/// syscall: "mlockall" ret: "int" args: "int"
pub const SYS_mlockall: i32 = 271;

/// syscall: "munlockall" ret: "int" args:
pub const SYS_munlockall: i32 = 272;

/// syscall: "getresuid" ret: "int" args: "uid_t *" "uid_t *" "uid_t *"
pub const SYS_getresuid: i32 = 281;

/// syscall: "setresuid" ret: "int" args: "uid_t" "uid_t" "uid_t"
pub const SYS_setresuid: i32 = 282;

/// syscall: "getresgid" ret: "int" args: "gid_t *" "gid_t *" "gid_t *"
pub const SYS_getresgid: i32 = 283;

/// syscall: "setresgid" ret: "int" args: "gid_t" "gid_t" "gid_t"
pub const SYS_setresgid: i32 = 284;

// 285 is obsolete sys_omquery

// 286 is obsolete pad_mquery

/// syscall: "closefrom" ret: "int" args: "int"
pub const SYS_closefrom: i32 = 287;

/// syscall: "sigaltstack" ret: "int" args: "const struct sigaltstack *" "struct sigaltstack *"
pub const SYS_sigaltstack: i32 = 288;

// 291 is obsolete t32_stat

// 292 is obsolete t32_fstat

// 293 is obsolete t32_lstat

/// syscall: "fhstat" ret: "int" args: "const fhandle_t *" "struct stat *"
pub const SYS_fhstat: i32 = 294;

/// syscall: "sched_yield" ret: "int" args:
pub const SYS_sched_yield: i32 = 298;

/// syscall: "getthrid" ret: "pid_t" args:
pub const SYS_getthrid: i32 = 299;

// 300 is obsolete t32___thrsleep

/// syscall: "__thrwakeup" ret: "int" args: "const volatile void *" "int"
pub const SYS___thrwakeup: i32 = 301;

/// syscall: "__threxit" ret: "void" args: "pid_t *"
pub const SYS___threxit: i32 = 302;

/// syscall: "__thrsigdivert" ret: "int" args: "sigset_t" "siginfo_t *" "const struct timespec *"
pub const SYS___thrsigdivert: i32 = 303;

/// syscall: "__getcwd" ret: "int" args: "char *" "size_t"
pub const SYS___getcwd: i32 = 304;

/// syscall: "adjfreq" ret: "int" args: "const int64_t *" "int64_t *"
pub const SYS_adjfreq: i32 = 305;

// 306 is obsolete getfsstat53

// 307 is obsolete statfs53

// 308 is obsolete fstatfs53

// 309 is obsolete fhstatfs53

/// syscall: "setrtable" ret: "int" args: "int"
pub const SYS_setrtable: i32 = 310;

/// syscall: "getrtable" ret: "int" args:
pub const SYS_getrtable: i32 = 311;

// 312 is obsolete t32_getdirentries

/// syscall: "faccessat" ret: "int" args: "int" "const char *" "int" "int"
pub const SYS_faccessat: i32 = 313;

/// syscall: "fchmodat" ret: "int" args: "int" "const char *" "mode_t" "int"
pub const SYS_fchmodat: i32 = 314;

/// syscall: "fchownat" ret: "int" args: "int" "const char *" "uid_t" "gid_t" "int"
pub const SYS_fchownat: i32 = 315;

// 316 is obsolete t32_fstatat

/// syscall: "linkat" ret: "int" args: "int" "const char *" "int" "const char *" "int"
pub const SYS_linkat: i32 = 317;

/// syscall: "mkdirat" ret: "int" args: "int" "const char *" "mode_t"
pub const SYS_mkdirat: i32 = 318;

/// syscall: "mkfifoat" ret: "int" args: "int" "const char *" "mode_t"
pub const SYS_mkfifoat: i32 = 319;

/// syscall: "mknodat" ret: "int" args: "int" "const char *" "mode_t" "dev_t"
pub const SYS_mknodat: i32 = 320;

/// syscall: "openat" ret: "int" args: "int" "const char *" "int" "..." "mode_t"
pub const SYS_openat: i32 = 321;

/// syscall: "readlinkat" ret: "ssize_t" args: "int" "const char *" "char *" "size_t"
pub const SYS_readlinkat: i32 = 322;

/// syscall: "renameat" ret: "int" args: "int" "const char *" "int" "const char *"
pub const SYS_renameat: i32 = 323;

/// syscall: "symlinkat" ret: "int" args: "const char *" "int" "const char *"
pub const SYS_symlinkat: i32 = 324;

/// syscall: "unlinkat" ret: "int" args: "int" "const char *" "int"
pub const SYS_unlinkat: i32 = 325;

// 326 is obsolete t32_utimensat

// 327 is obsolete t32_futimens

// 328 is obsolete __tfork51

/// syscall: "__set_tcb" ret: "void" args: "void *"
pub const SYS___set_tcb: i32 = 329;

/// syscall: "__get_tcb" ret: "void *" args:
pub const SYS___get_tcb: i32 = 330;

/// `SYS_MAXSYSCALL`: one past the last system call number.
pub const SYS_MAXSYSCALL: usize = 331;
/* </CODE> */
