/*	$OpenBSD: syscallargs.h,v 1.289 2026/08/12 15:05:21 naddy Exp $	*/

/* <LICENSES> */
/*
 * Copyright (c) 2026 Emilio Navarrete Lineros <enavarre@outlook.com>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
/* </LICENSES> */

/* <CODE> */
//! `<sys/syscallargs.h>`: system call argument lists.
//!
//! DO NOT EDIT: this file is automatically generated by `cargo xtask gen-syscalls`
//! (`tools/xtask/src/syscalls.rs`, what `kern/makesyscalls.sh` does for the C tree)
//! from `sys/kern/syscalls.master`.
//! created from; OpenBSD: syscalls.master,v 1.273 2026/08/12 15:04:45 naddy Exp
//!
//! Upstream: sys/sys/syscallargs.h @ 3ce1f3f79392
//!
//! ## Deviations
//! - `syscallarg(x)` is the `Syscallarg<T>` union: one `register_t` slot per argument with
//!   the datum in the low bytes (the C's little-endian arm); `SCARG(uap, k)` is `uap.k.get()`.
//! - Pointers to structures the kernel does not define yet are `*mut c_void`/`*const c_void`;
//!   the C type is in the field's doc comment.

use core::ffi::c_void;

use crate::sys::types::{Clockid, Dev, Gid, Id, Mode, Off, Pid, Register, Socklen, Uid};

/// `syscallarg(x)`: one system call argument slot, `register_t` wide.
#[repr(C)]
#[derive(Clone, Copy)]
pub union Syscallarg<T: Copy> {
    /// `pad`: the whole register.
    pub pad: Register,
    /// `datum`: the argument in the register's low bytes.
    pub datum: T,
}

impl<T: Copy> Syscallarg<T> {
    /// `SCARG(uap, k)`: the argument as its C type.
    pub fn get(self) -> T {
        // SAFETY: the slot holds a register the caller filled; every bit pattern of a
        // register is a valid `T` (an integer, a pointer or an alias of one), and on this
        // little-endian machine `T` is the register's low bytes.
        unsafe { self.datum }
    }
}

/// `struct sys_exit_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysExitArgs {
    /// `rval`: `int`.
    pub rval: Syscallarg<i32>,
}

/// `struct sys_read_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysReadArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `buf`: `void *`.
    pub buf: Syscallarg<*mut c_void>,
    /// `nbyte`: `size_t`.
    pub nbyte: Syscallarg<usize>,
}

/// `struct sys_write_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysWriteArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `buf`: `const void *`.
    pub buf: Syscallarg<*const c_void>,
    /// `nbyte`: `size_t`.
    pub nbyte: Syscallarg<usize>,
}

/// `struct sys_open_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysOpenArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `flags`: `int`.
    pub flags: Syscallarg<i32>,
    /// `mode`: `mode_t`.
    pub mode: Syscallarg<Mode>,
}

/// `struct sys_close_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysCloseArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
}

/// `struct sys_getentropy_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysGetentropyArgs {
    /// `buf`: `void *`.
    pub buf: Syscallarg<*mut c_void>,
    /// `nbyte`: `size_t`.
    pub nbyte: Syscallarg<usize>,
}

/// `struct sys___tfork_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysTforkArgs {
    /// `param`: `const struct __tfork *` (opaque until the structure is ported).
    pub param: Syscallarg<*const c_void>,
    /// `psize`: `size_t`.
    pub psize: Syscallarg<usize>,
}

/// `struct sys_link_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysLinkArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `link`: `const char *`.
    pub link: Syscallarg<*const u8>,
}

/// `struct sys_unlink_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysUnlinkArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
}

/// `struct sys_wait4_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysWait4Args {
    /// `pid`: `pid_t`.
    pub pid: Syscallarg<Pid>,
    /// `status`: `int *`.
    pub status: Syscallarg<*mut i32>,
    /// `options`: `int`.
    pub options: Syscallarg<i32>,
    /// `rusage`: `struct rusage *` (opaque until the structure is ported).
    pub rusage: Syscallarg<*mut c_void>,
}

/// `struct sys_chdir_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysChdirArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
}

/// `struct sys_fchdir_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysFchdirArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
}

/// `struct sys_mknod_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysMknodArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `mode`: `mode_t`.
    pub mode: Syscallarg<Mode>,
    /// `dev`: `dev_t`.
    pub dev: Syscallarg<Dev>,
}

/// `struct sys_chmod_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysChmodArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `mode`: `mode_t`.
    pub mode: Syscallarg<Mode>,
}

/// `struct sys_chown_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysChownArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `uid`: `uid_t`.
    pub uid: Syscallarg<Uid>,
    /// `gid`: `gid_t`.
    pub gid: Syscallarg<Gid>,
}

/// `struct sys_obreak_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysObreakArgs {
    /// `nsize`: `char *`.
    pub nsize: Syscallarg<*mut u8>,
}

/// `struct sys_getrusage_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysGetrusageArgs {
    /// `who`: `int`.
    pub who: Syscallarg<i32>,
    /// `rusage`: `struct rusage *` (opaque until the structure is ported).
    pub rusage: Syscallarg<*mut c_void>,
}

/// `struct sys_mount_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysMountArgs {
    /// `type`: `const char *`.
    pub r#type: Syscallarg<*const u8>,
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `flags`: `int`.
    pub flags: Syscallarg<i32>,
    /// `data`: `void *`.
    pub data: Syscallarg<*mut c_void>,
}

/// `struct sys_unmount_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysUnmountArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `flags`: `int`.
    pub flags: Syscallarg<i32>,
}

/// `struct sys_setuid_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSetuidArgs {
    /// `uid`: `uid_t`.
    pub uid: Syscallarg<Uid>,
}

/// `struct sys_recvmsg_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysRecvmsgArgs {
    /// `s`: `int`.
    pub s: Syscallarg<i32>,
    /// `msg`: `struct msghdr *` (opaque until the structure is ported).
    pub msg: Syscallarg<*mut c_void>,
    /// `flags`: `int`.
    pub flags: Syscallarg<i32>,
}

/// `struct sys_sendmsg_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSendmsgArgs {
    /// `s`: `int`.
    pub s: Syscallarg<i32>,
    /// `msg`: `const struct msghdr *` (opaque until the structure is ported).
    pub msg: Syscallarg<*const c_void>,
    /// `flags`: `int`.
    pub flags: Syscallarg<i32>,
}

/// `struct sys_recvfrom_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysRecvfromArgs {
    /// `s`: `int`.
    pub s: Syscallarg<i32>,
    /// `buf`: `void *`.
    pub buf: Syscallarg<*mut c_void>,
    /// `len`: `size_t`.
    pub len: Syscallarg<usize>,
    /// `flags`: `int`.
    pub flags: Syscallarg<i32>,
    /// `from`: `struct sockaddr *` (opaque until the structure is ported).
    pub from: Syscallarg<*mut c_void>,
    /// `fromlenaddr`: `socklen_t *`.
    pub fromlenaddr: Syscallarg<*mut Socklen>,
}

/// `struct sys_accept_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysAcceptArgs {
    /// `s`: `int`.
    pub s: Syscallarg<i32>,
    /// `name`: `struct sockaddr *` (opaque until the structure is ported).
    pub name: Syscallarg<*mut c_void>,
    /// `anamelen`: `socklen_t *`.
    pub anamelen: Syscallarg<*mut Socklen>,
}

/// `struct sys_getpeername_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysGetpeernameArgs {
    /// `fdes`: `int`.
    pub fdes: Syscallarg<i32>,
    /// `asa`: `struct sockaddr *` (opaque until the structure is ported).
    pub asa: Syscallarg<*mut c_void>,
    /// `alen`: `socklen_t *`.
    pub alen: Syscallarg<*mut Socklen>,
}

/// `struct sys_getsockname_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysGetsocknameArgs {
    /// `fdes`: `int`.
    pub fdes: Syscallarg<i32>,
    /// `asa`: `struct sockaddr *` (opaque until the structure is ported).
    pub asa: Syscallarg<*mut c_void>,
    /// `alen`: `socklen_t *`.
    pub alen: Syscallarg<*mut Socklen>,
}

/// `struct sys_access_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysAccessArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `amode`: `int`.
    pub amode: Syscallarg<i32>,
}

/// `struct sys_chflags_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysChflagsArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `flags`: `u_int`.
    pub flags: Syscallarg<u32>,
}

/// `struct sys_fchflags_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysFchflagsArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `flags`: `u_int`.
    pub flags: Syscallarg<u32>,
}

/// `struct sys_stat_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysStatArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `ub`: `struct stat *` (opaque until the structure is ported).
    pub ub: Syscallarg<*mut c_void>,
}

/// `struct sys_lstat_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysLstatArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `ub`: `struct stat *` (opaque until the structure is ported).
    pub ub: Syscallarg<*mut c_void>,
}

/// `struct sys_dup_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysDupArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
}

/// `struct sys_fstatat_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysFstatatArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `buf`: `struct stat *` (opaque until the structure is ported).
    pub buf: Syscallarg<*mut c_void>,
    /// `flag`: `int`.
    pub flag: Syscallarg<i32>,
}

/// `struct sys_sigaction_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSigactionArgs {
    /// `signum`: `int`.
    pub signum: Syscallarg<i32>,
    /// `nsa`: `const struct sigaction *` (opaque until the structure is ported).
    pub nsa: Syscallarg<*const c_void>,
    /// `osa`: `struct sigaction *` (opaque until the structure is ported).
    pub osa: Syscallarg<*mut c_void>,
}

/// `struct sys_sigprocmask_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSigprocmaskArgs {
    /// `how`: `int`.
    pub how: Syscallarg<i32>,
    /// `mask`: `sigset_t`.
    pub mask: Syscallarg<u32>,
}

/// `struct sys_mmap_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysMmapArgs {
    /// `addr`: `void *`.
    pub addr: Syscallarg<*mut c_void>,
    /// `len`: `size_t`.
    pub len: Syscallarg<usize>,
    /// `prot`: `int`.
    pub prot: Syscallarg<i32>,
    /// `flags`: `int`.
    pub flags: Syscallarg<i32>,
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `pos`: `off_t`.
    pub pos: Syscallarg<Off>,
}

/// `struct sys_setlogin_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSetloginArgs {
    /// `namebuf`: `const char *`.
    pub namebuf: Syscallarg<*const u8>,
}

/// `struct sys_acct_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysAcctArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
}

/// `struct sys_fstat_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysFstatArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `sb`: `struct stat *` (opaque until the structure is ported).
    pub sb: Syscallarg<*mut c_void>,
}

/// `struct sys_ioctl_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysIoctlArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `com`: `u_long`.
    pub com: Syscallarg<u64>,
    /// `data`: `void *`.
    pub data: Syscallarg<*mut c_void>,
}

/// `struct sys_reboot_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysRebootArgs {
    /// `opt`: `int`.
    pub opt: Syscallarg<i32>,
}

/// `struct sys_revoke_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysRevokeArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
}

/// `struct sys_symlink_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSymlinkArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `link`: `const char *`.
    pub link: Syscallarg<*const u8>,
}

/// `struct sys_readlink_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysReadlinkArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `buf`: `char *`.
    pub buf: Syscallarg<*mut u8>,
    /// `count`: `size_t`.
    pub count: Syscallarg<usize>,
}

/// `struct sys_execve_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysExecveArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `argp`: `char *const *`.
    pub argp: Syscallarg<*const *const u8>,
    /// `envp`: `char *const *`.
    pub envp: Syscallarg<*const *const u8>,
}

/// `struct sys_umask_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysUmaskArgs {
    /// `newmask`: `mode_t`.
    pub newmask: Syscallarg<Mode>,
}

/// `struct sys_chroot_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysChrootArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
}

/// `struct sys_getfsstat_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysGetfsstatArgs {
    /// `buf`: `struct statfs *` (opaque until the structure is ported).
    pub buf: Syscallarg<*mut c_void>,
    /// `bufsize`: `size_t`.
    pub bufsize: Syscallarg<usize>,
    /// `flags`: `int`.
    pub flags: Syscallarg<i32>,
}

/// `struct sys_statfs_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysStatfsArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `buf`: `struct statfs *` (opaque until the structure is ported).
    pub buf: Syscallarg<*mut c_void>,
}

/// `struct sys_fstatfs_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysFstatfsArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `buf`: `struct statfs *` (opaque until the structure is ported).
    pub buf: Syscallarg<*mut c_void>,
}

/// `struct sys_fhstatfs_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysFhstatfsArgs {
    /// `fhp`: `const fhandle_t *` (opaque until the structure is ported).
    pub fhp: Syscallarg<*const c_void>,
    /// `buf`: `struct statfs *` (opaque until the structure is ported).
    pub buf: Syscallarg<*mut c_void>,
}

/// `struct sys_gettimeofday_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysGettimeofdayArgs {
    /// `tp`: `struct timeval *` (opaque until the structure is ported).
    pub tp: Syscallarg<*mut c_void>,
    /// `tzp`: `struct timezone *` (opaque until the structure is ported).
    pub tzp: Syscallarg<*mut c_void>,
}

/// `struct sys_settimeofday_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSettimeofdayArgs {
    /// `tv`: `const struct timeval *` (opaque until the structure is ported).
    pub tv: Syscallarg<*const c_void>,
    /// `tzp`: `const struct timezone *` (opaque until the structure is ported).
    pub tzp: Syscallarg<*const c_void>,
}

/// `struct sys_setitimer_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSetitimerArgs {
    /// `which`: `int`.
    pub which: Syscallarg<i32>,
    /// `itv`: `const struct itimerval *` (opaque until the structure is ported).
    pub itv: Syscallarg<*const c_void>,
    /// `oitv`: `struct itimerval *` (opaque until the structure is ported).
    pub oitv: Syscallarg<*mut c_void>,
}

/// `struct sys_getitimer_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysGetitimerArgs {
    /// `which`: `int`.
    pub which: Syscallarg<i32>,
    /// `itv`: `struct itimerval *` (opaque until the structure is ported).
    pub itv: Syscallarg<*mut c_void>,
}

/// `struct sys_select_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSelectArgs {
    /// `nd`: `int`.
    pub nd: Syscallarg<i32>,
    /// `in`: `fd_set *` (opaque until the structure is ported).
    pub r#in: Syscallarg<*mut c_void>,
    /// `ou`: `fd_set *` (opaque until the structure is ported).
    pub ou: Syscallarg<*mut c_void>,
    /// `ex`: `fd_set *` (opaque until the structure is ported).
    pub ex: Syscallarg<*mut c_void>,
    /// `tv`: `struct timeval *` (opaque until the structure is ported).
    pub tv: Syscallarg<*mut c_void>,
}

/// `struct sys_kevent_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysKeventArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `changelist`: `const struct kevent *` (opaque until the structure is ported).
    pub changelist: Syscallarg<*const c_void>,
    /// `nchanges`: `int`.
    pub nchanges: Syscallarg<i32>,
    /// `eventlist`: `struct kevent *` (opaque until the structure is ported).
    pub eventlist: Syscallarg<*mut c_void>,
    /// `nevents`: `int`.
    pub nevents: Syscallarg<i32>,
    /// `timeout`: `const struct timespec *` (opaque until the structure is ported).
    pub timeout: Syscallarg<*const c_void>,
}

/// `struct sys_munmap_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysMunmapArgs {
    /// `addr`: `void *`.
    pub addr: Syscallarg<*mut c_void>,
    /// `len`: `size_t`.
    pub len: Syscallarg<usize>,
}

/// `struct sys_mprotect_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysMprotectArgs {
    /// `addr`: `void *`.
    pub addr: Syscallarg<*mut c_void>,
    /// `len`: `size_t`.
    pub len: Syscallarg<usize>,
    /// `prot`: `int`.
    pub prot: Syscallarg<i32>,
}

/// `struct sys_madvise_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysMadviseArgs {
    /// `addr`: `void *`.
    pub addr: Syscallarg<*mut c_void>,
    /// `len`: `size_t`.
    pub len: Syscallarg<usize>,
    /// `behav`: `int`.
    pub behav: Syscallarg<i32>,
}

/// `struct sys_utimes_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysUtimesArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `tptr`: `const struct timeval *` (opaque until the structure is ported).
    pub tptr: Syscallarg<*const c_void>,
}

/// `struct sys_futimes_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysFutimesArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `tptr`: `const struct timeval *` (opaque until the structure is ported).
    pub tptr: Syscallarg<*const c_void>,
}

/// `struct sys_mquery_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysMqueryArgs {
    /// `addr`: `void *`.
    pub addr: Syscallarg<*mut c_void>,
    /// `len`: `size_t`.
    pub len: Syscallarg<usize>,
    /// `prot`: `int`.
    pub prot: Syscallarg<i32>,
    /// `flags`: `int`.
    pub flags: Syscallarg<i32>,
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `pos`: `off_t`.
    pub pos: Syscallarg<Off>,
}

/// `struct sys_getgroups_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysGetgroupsArgs {
    /// `gidsetsize`: `int`.
    pub gidsetsize: Syscallarg<i32>,
    /// `gidset`: `gid_t *`.
    pub gidset: Syscallarg<*mut Gid>,
}

/// `struct sys_setgroups_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSetgroupsArgs {
    /// `gidsetsize`: `int`.
    pub gidsetsize: Syscallarg<i32>,
    /// `gidset`: `const gid_t *`.
    pub gidset: Syscallarg<*const Gid>,
}

/// `struct sys_setpgid_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSetpgidArgs {
    /// `pid`: `pid_t`.
    pub pid: Syscallarg<Pid>,
    /// `pgid`: `pid_t`.
    pub pgid: Syscallarg<Pid>,
}

/// `struct sys_futex_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysFutexArgs {
    /// `f`: `uint32_t *`.
    pub f: Syscallarg<*mut u32>,
    /// `op`: `int`.
    pub op: Syscallarg<i32>,
    /// `val`: `int`.
    pub val: Syscallarg<i32>,
    /// `timeout`: `const struct timespec *` (opaque until the structure is ported).
    pub timeout: Syscallarg<*const c_void>,
    /// `g`: `uint32_t *`.
    pub g: Syscallarg<*mut u32>,
}

/// `struct sys_utimensat_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysUtimensatArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `times`: `const struct timespec *` (opaque until the structure is ported).
    pub times: Syscallarg<*const c_void>,
    /// `flag`: `int`.
    pub flag: Syscallarg<i32>,
}

/// `struct sys_futimens_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysFutimensArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `times`: `const struct timespec *` (opaque until the structure is ported).
    pub times: Syscallarg<*const c_void>,
}

/// `struct sys_kbind_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysKbindArgs {
    /// `param`: `const struct __kbind *` (opaque until the structure is ported).
    pub param: Syscallarg<*const c_void>,
    /// `psize`: `size_t`.
    pub psize: Syscallarg<usize>,
    /// `proc_cookie`: `int64_t`.
    pub proc_cookie: Syscallarg<i64>,
}

/// `struct sys_clock_gettime_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysClockGettimeArgs {
    /// `clock_id`: `clockid_t`.
    pub clock_id: Syscallarg<Clockid>,
    /// `tp`: `struct timespec *` (opaque until the structure is ported).
    pub tp: Syscallarg<*mut c_void>,
}

/// `struct sys_clock_settime_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysClockSettimeArgs {
    /// `clock_id`: `clockid_t`.
    pub clock_id: Syscallarg<Clockid>,
    /// `tp`: `const struct timespec *` (opaque until the structure is ported).
    pub tp: Syscallarg<*const c_void>,
}

/// `struct sys_clock_getres_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysClockGetresArgs {
    /// `clock_id`: `clockid_t`.
    pub clock_id: Syscallarg<Clockid>,
    /// `tp`: `struct timespec *` (opaque until the structure is ported).
    pub tp: Syscallarg<*mut c_void>,
}

/// `struct sys_dup2_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysDup2Args {
    /// `from`: `int`.
    pub from: Syscallarg<i32>,
    /// `to`: `int`.
    pub to: Syscallarg<i32>,
}

/// `struct sys_nanosleep_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysNanosleepArgs {
    /// `rqtp`: `const struct timespec *` (opaque until the structure is ported).
    pub rqtp: Syscallarg<*const c_void>,
    /// `rmtp`: `struct timespec *` (opaque until the structure is ported).
    pub rmtp: Syscallarg<*mut c_void>,
}

/// `struct sys_fcntl_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysFcntlArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `cmd`: `int`.
    pub cmd: Syscallarg<i32>,
    /// `arg`: `void *`.
    pub arg: Syscallarg<*mut c_void>,
}

/// `struct sys_accept4_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysAccept4Args {
    /// `s`: `int`.
    pub s: Syscallarg<i32>,
    /// `name`: `struct sockaddr *` (opaque until the structure is ported).
    pub name: Syscallarg<*mut c_void>,
    /// `anamelen`: `socklen_t *`.
    pub anamelen: Syscallarg<*mut Socklen>,
    /// `flags`: `int`.
    pub flags: Syscallarg<i32>,
}

/// `struct sys___thrsleep_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysThrsleepArgs {
    /// `ident`: `const volatile void *`.
    pub ident: Syscallarg<*const c_void>,
    /// `clock_id`: `clockid_t`.
    pub clock_id: Syscallarg<Clockid>,
    /// `tp`: `const struct timespec *` (opaque until the structure is ported).
    pub tp: Syscallarg<*const c_void>,
    /// `lock`: `void *`.
    pub lock: Syscallarg<*mut c_void>,
    /// `abort`: `const int *`.
    pub abort: Syscallarg<*const i32>,
}

/// `struct sys_fsync_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysFsyncArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
}

/// `struct sys_setpriority_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSetpriorityArgs {
    /// `which`: `int`.
    pub which: Syscallarg<i32>,
    /// `who`: `id_t`.
    pub who: Syscallarg<Id>,
    /// `prio`: `int`.
    pub prio: Syscallarg<i32>,
}

/// `struct sys_socket_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSocketArgs {
    /// `domain`: `int`.
    pub domain: Syscallarg<i32>,
    /// `type`: `int`.
    pub r#type: Syscallarg<i32>,
    /// `protocol`: `int`.
    pub protocol: Syscallarg<i32>,
}

/// `struct sys_connect_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysConnectArgs {
    /// `s`: `int`.
    pub s: Syscallarg<i32>,
    /// `name`: `const struct sockaddr *` (opaque until the structure is ported).
    pub name: Syscallarg<*const c_void>,
    /// `namelen`: `socklen_t`.
    pub namelen: Syscallarg<Socklen>,
}

/// `struct sys_getdents_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysGetdentsArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `buf`: `void *`.
    pub buf: Syscallarg<*mut c_void>,
    /// `buflen`: `size_t`.
    pub buflen: Syscallarg<usize>,
}

/// `struct sys_getpriority_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysGetpriorityArgs {
    /// `which`: `int`.
    pub which: Syscallarg<i32>,
    /// `who`: `id_t`.
    pub who: Syscallarg<Id>,
}

/// `struct sys_pipe2_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysPipe2Args {
    /// `fdp`: `int *`.
    pub fdp: Syscallarg<*mut i32>,
    /// `flags`: `int`.
    pub flags: Syscallarg<i32>,
}

/// `struct sys_dup3_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysDup3Args {
    /// `from`: `int`.
    pub from: Syscallarg<i32>,
    /// `to`: `int`.
    pub to: Syscallarg<i32>,
    /// `flags`: `int`.
    pub flags: Syscallarg<i32>,
}

/// `struct sys_sigreturn_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSigreturnArgs {
    /// `sigcntxp`: `struct sigcontext *` (opaque until the structure is ported).
    pub sigcntxp: Syscallarg<*mut c_void>,
}

/// `struct sys_bind_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysBindArgs {
    /// `s`: `int`.
    pub s: Syscallarg<i32>,
    /// `name`: `const struct sockaddr *` (opaque until the structure is ported).
    pub name: Syscallarg<*const c_void>,
    /// `namelen`: `socklen_t`.
    pub namelen: Syscallarg<Socklen>,
}

/// `struct sys_setsockopt_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSetsockoptArgs {
    /// `s`: `int`.
    pub s: Syscallarg<i32>,
    /// `level`: `int`.
    pub level: Syscallarg<i32>,
    /// `name`: `int`.
    pub name: Syscallarg<i32>,
    /// `val`: `const void *`.
    pub val: Syscallarg<*const c_void>,
    /// `valsize`: `socklen_t`.
    pub valsize: Syscallarg<Socklen>,
}

/// `struct sys_listen_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysListenArgs {
    /// `s`: `int`.
    pub s: Syscallarg<i32>,
    /// `backlog`: `int`.
    pub backlog: Syscallarg<i32>,
}

/// `struct sys_chflagsat_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysChflagsatArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `flags`: `u_int`.
    pub flags: Syscallarg<u32>,
    /// `atflags`: `int`.
    pub atflags: Syscallarg<i32>,
}

/// `struct sys_pledge_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysPledgeArgs {
    /// `promises`: `const char *`.
    pub promises: Syscallarg<*const u8>,
    /// `execpromises`: `const char *`.
    pub execpromises: Syscallarg<*const u8>,
}

/// `struct sys_ppoll_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysPpollArgs {
    /// `fds`: `struct pollfd *` (opaque until the structure is ported).
    pub fds: Syscallarg<*mut c_void>,
    /// `nfds`: `u_int`.
    pub nfds: Syscallarg<u32>,
    /// `ts`: `const struct timespec *` (opaque until the structure is ported).
    pub ts: Syscallarg<*const c_void>,
    /// `mask`: `const sigset_t *`.
    pub mask: Syscallarg<*const u32>,
}

/// `struct sys_pselect_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysPselectArgs {
    /// `nd`: `int`.
    pub nd: Syscallarg<i32>,
    /// `in`: `fd_set *` (opaque until the structure is ported).
    pub r#in: Syscallarg<*mut c_void>,
    /// `ou`: `fd_set *` (opaque until the structure is ported).
    pub ou: Syscallarg<*mut c_void>,
    /// `ex`: `fd_set *` (opaque until the structure is ported).
    pub ex: Syscallarg<*mut c_void>,
    /// `ts`: `const struct timespec *` (opaque until the structure is ported).
    pub ts: Syscallarg<*const c_void>,
    /// `mask`: `const sigset_t *`.
    pub mask: Syscallarg<*const u32>,
}

/// `struct sys_sigsuspend_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSigsuspendArgs {
    /// `mask`: `int`.
    pub mask: Syscallarg<i32>,
}

/// `struct sys_sendsyslog_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSendsyslogArgs {
    /// `buf`: `const char *`.
    pub buf: Syscallarg<*const u8>,
    /// `nbyte`: `size_t`.
    pub nbyte: Syscallarg<usize>,
    /// `flags`: `int`.
    pub flags: Syscallarg<i32>,
}

/// `struct sys_unveil_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysUnveilArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `permissions`: `const char *`.
    pub permissions: Syscallarg<*const u8>,
}

/// `struct sys___realpath_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysRealpathArgs {
    /// `pathname`: `const char *`.
    pub pathname: Syscallarg<*const u8>,
    /// `resolved`: `char *`.
    pub resolved: Syscallarg<*mut u8>,
}

/// `struct sys_recvmmsg_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysRecvmmsgArgs {
    /// `s`: `int`.
    pub s: Syscallarg<i32>,
    /// `mmsg`: `struct mmsghdr *` (opaque until the structure is ported).
    pub mmsg: Syscallarg<*mut c_void>,
    /// `vlen`: `unsigned int`.
    pub vlen: Syscallarg<u32>,
    /// `flags`: `int`.
    pub flags: Syscallarg<i32>,
    /// `timeout`: `struct timespec *` (opaque until the structure is ported).
    pub timeout: Syscallarg<*mut c_void>,
}

/// `struct sys_sendmmsg_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSendmmsgArgs {
    /// `s`: `int`.
    pub s: Syscallarg<i32>,
    /// `mmsg`: `struct mmsghdr *` (opaque until the structure is ported).
    pub mmsg: Syscallarg<*mut c_void>,
    /// `vlen`: `unsigned int`.
    pub vlen: Syscallarg<u32>,
    /// `flags`: `int`.
    pub flags: Syscallarg<i32>,
}

/// `struct sys_getsockopt_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysGetsockoptArgs {
    /// `s`: `int`.
    pub s: Syscallarg<i32>,
    /// `level`: `int`.
    pub level: Syscallarg<i32>,
    /// `name`: `int`.
    pub name: Syscallarg<i32>,
    /// `val`: `void *`.
    pub val: Syscallarg<*mut c_void>,
    /// `avalsize`: `socklen_t *`.
    pub avalsize: Syscallarg<*mut Socklen>,
}

/// `struct sys_thrkill_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysThrkillArgs {
    /// `tid`: `pid_t`.
    pub tid: Syscallarg<Pid>,
    /// `signum`: `int`.
    pub signum: Syscallarg<i32>,
    /// `tcb`: `void *`.
    pub tcb: Syscallarg<*mut c_void>,
}

/// `struct sys_readv_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysReadvArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `iovp`: `const struct iovec *` (opaque until the structure is ported).
    pub iovp: Syscallarg<*const c_void>,
    /// `iovcnt`: `int`.
    pub iovcnt: Syscallarg<i32>,
}

/// `struct sys_writev_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysWritevArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `iovp`: `const struct iovec *` (opaque until the structure is ported).
    pub iovp: Syscallarg<*const c_void>,
    /// `iovcnt`: `int`.
    pub iovcnt: Syscallarg<i32>,
}

/// `struct sys_kill_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysKillArgs {
    /// `pid`: `int`.
    pub pid: Syscallarg<i32>,
    /// `signum`: `int`.
    pub signum: Syscallarg<i32>,
}

/// `struct sys_fchown_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysFchownArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `uid`: `uid_t`.
    pub uid: Syscallarg<Uid>,
    /// `gid`: `gid_t`.
    pub gid: Syscallarg<Gid>,
}

/// `struct sys_fchmod_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysFchmodArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `mode`: `mode_t`.
    pub mode: Syscallarg<Mode>,
}

/// `struct sys___pledge_open_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysPledgeOpenArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `flags`: `int`.
    pub flags: Syscallarg<i32>,
    /// `mode`: `mode_t`.
    pub mode: Syscallarg<Mode>,
}

/// `struct sys_setreuid_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSetreuidArgs {
    /// `ruid`: `uid_t`.
    pub ruid: Syscallarg<Uid>,
    /// `euid`: `uid_t`.
    pub euid: Syscallarg<Uid>,
}

/// `struct sys_setregid_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSetregidArgs {
    /// `rgid`: `gid_t`.
    pub rgid: Syscallarg<Gid>,
    /// `egid`: `gid_t`.
    pub egid: Syscallarg<Gid>,
}

/// `struct sys_rename_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysRenameArgs {
    /// `from`: `const char *`.
    pub from: Syscallarg<*const u8>,
    /// `to`: `const char *`.
    pub to: Syscallarg<*const u8>,
}

/// `struct sys_flock_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysFlockArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `how`: `int`.
    pub how: Syscallarg<i32>,
}

/// `struct sys_mkfifo_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysMkfifoArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `mode`: `mode_t`.
    pub mode: Syscallarg<Mode>,
}

/// `struct sys_sendto_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSendtoArgs {
    /// `s`: `int`.
    pub s: Syscallarg<i32>,
    /// `buf`: `const void *`.
    pub buf: Syscallarg<*const c_void>,
    /// `len`: `size_t`.
    pub len: Syscallarg<usize>,
    /// `flags`: `int`.
    pub flags: Syscallarg<i32>,
    /// `to`: `const struct sockaddr *` (opaque until the structure is ported).
    pub to: Syscallarg<*const c_void>,
    /// `tolen`: `socklen_t`.
    pub tolen: Syscallarg<Socklen>,
}

/// `struct sys_shutdown_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysShutdownArgs {
    /// `s`: `int`.
    pub s: Syscallarg<i32>,
    /// `how`: `int`.
    pub how: Syscallarg<i32>,
}

/// `struct sys_socketpair_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSocketpairArgs {
    /// `domain`: `int`.
    pub domain: Syscallarg<i32>,
    /// `type`: `int`.
    pub r#type: Syscallarg<i32>,
    /// `protocol`: `int`.
    pub protocol: Syscallarg<i32>,
    /// `rsv`: `int *`.
    pub rsv: Syscallarg<*mut i32>,
}

/// `struct sys_mkdir_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysMkdirArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `mode`: `mode_t`.
    pub mode: Syscallarg<Mode>,
}

/// `struct sys_rmdir_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysRmdirArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
}

/// `struct sys_adjtime_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysAdjtimeArgs {
    /// `delta`: `const struct timeval *` (opaque until the structure is ported).
    pub delta: Syscallarg<*const c_void>,
    /// `olddelta`: `struct timeval *` (opaque until the structure is ported).
    pub olddelta: Syscallarg<*mut c_void>,
}

/// `struct sys_getlogin_r_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysGetloginRArgs {
    /// `namebuf`: `char *`.
    pub namebuf: Syscallarg<*mut u8>,
    /// `namelen`: `size_t`.
    pub namelen: Syscallarg<usize>,
}

/// `struct sys_getthrname_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysGetthrnameArgs {
    /// `tid`: `pid_t`.
    pub tid: Syscallarg<Pid>,
    /// `name`: `char *`.
    pub name: Syscallarg<*mut u8>,
    /// `len`: `size_t`.
    pub len: Syscallarg<usize>,
}

/// `struct sys_setthrname_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSetthrnameArgs {
    /// `tid`: `pid_t`.
    pub tid: Syscallarg<Pid>,
    /// `name`: `const char *`.
    pub name: Syscallarg<*const u8>,
}

/// `struct sys_quotactl_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysQuotactlArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `cmd`: `int`.
    pub cmd: Syscallarg<i32>,
    /// `uid`: `int`.
    pub uid: Syscallarg<i32>,
    /// `arg`: `void *`.
    pub arg: Syscallarg<*mut c_void>,
}

/// `struct sys_ypconnect_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysYpconnectArgs {
    /// `type`: `int`.
    pub r#type: Syscallarg<i32>,
}

/// `struct sys_nfssvc_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysNfssvcArgs {
    /// `flag`: `int`.
    pub flag: Syscallarg<i32>,
    /// `argp`: `void *`.
    pub argp: Syscallarg<*mut c_void>,
}

/// `struct sys_pinsyscalls_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysPinsyscallsArgs {
    /// `base`: `void *`.
    pub base: Syscallarg<*mut c_void>,
    /// `len`: `size_t`.
    pub len: Syscallarg<usize>,
    /// `pins`: `u_int *`.
    pub pins: Syscallarg<*mut u32>,
    /// `npins`: `int`.
    pub npins: Syscallarg<i32>,
}

/// `struct sys_mimmutable_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysMimmutableArgs {
    /// `addr`: `void *`.
    pub addr: Syscallarg<*mut c_void>,
    /// `len`: `size_t`.
    pub len: Syscallarg<usize>,
}

/// `struct sys_waitid_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysWaitidArgs {
    /// `idtype`: `int`.
    pub idtype: Syscallarg<i32>,
    /// `id`: `id_t`.
    pub id: Syscallarg<Id>,
    /// `info`: `siginfo_t *` (opaque until the structure is ported).
    pub info: Syscallarg<*mut c_void>,
    /// `options`: `int`.
    pub options: Syscallarg<i32>,
}

/// `struct sys_getfh_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysGetfhArgs {
    /// `fname`: `const char *`.
    pub fname: Syscallarg<*const u8>,
    /// `fhp`: `fhandle_t *` (opaque until the structure is ported).
    pub fhp: Syscallarg<*mut c_void>,
}

/// `struct sys_sysarch_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSysarchArgs {
    /// `op`: `int`.
    pub op: Syscallarg<i32>,
    /// `parms`: `void *`.
    pub parms: Syscallarg<*mut c_void>,
}

/// `struct sys_lseek_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysLseekArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `offset`: `off_t`.
    pub offset: Syscallarg<Off>,
    /// `whence`: `int`.
    pub whence: Syscallarg<i32>,
}

/// `struct sys_truncate_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysTruncateArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `length`: `off_t`.
    pub length: Syscallarg<Off>,
}

/// `struct sys_ftruncate_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysFtruncateArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `length`: `off_t`.
    pub length: Syscallarg<Off>,
}

/// `struct sys_pread_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysPreadArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `buf`: `void *`.
    pub buf: Syscallarg<*mut c_void>,
    /// `nbyte`: `size_t`.
    pub nbyte: Syscallarg<usize>,
    /// `offset`: `off_t`.
    pub offset: Syscallarg<Off>,
}

/// `struct sys_pwrite_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysPwriteArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `buf`: `const void *`.
    pub buf: Syscallarg<*const c_void>,
    /// `nbyte`: `size_t`.
    pub nbyte: Syscallarg<usize>,
    /// `offset`: `off_t`.
    pub offset: Syscallarg<Off>,
}

/// `struct sys_preadv_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysPreadvArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `iovp`: `const struct iovec *` (opaque until the structure is ported).
    pub iovp: Syscallarg<*const c_void>,
    /// `iovcnt`: `int`.
    pub iovcnt: Syscallarg<i32>,
    /// `offset`: `off_t`.
    pub offset: Syscallarg<Off>,
}

/// `struct sys_pwritev_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysPwritevArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `iovp`: `const struct iovec *` (opaque until the structure is ported).
    pub iovp: Syscallarg<*const c_void>,
    /// `iovcnt`: `int`.
    pub iovcnt: Syscallarg<i32>,
    /// `offset`: `off_t`.
    pub offset: Syscallarg<Off>,
}

/// `struct sys_profil_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysProfilArgs {
    /// `buf`: `void *`.
    pub buf: Syscallarg<*mut c_void>,
    /// `buflen`: `size_t`.
    pub buflen: Syscallarg<usize>,
    /// `samplesize`: `size_t`.
    pub samplesize: Syscallarg<usize>,
    /// `offset`: `u_long`.
    pub offset: Syscallarg<u64>,
    /// `scale`: `u_int`.
    pub scale: Syscallarg<u32>,
    /// `dirfd`: `int`.
    pub dirfd: Syscallarg<i32>,
}

/// `struct sys_setgid_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSetgidArgs {
    /// `gid`: `gid_t`.
    pub gid: Syscallarg<Gid>,
}

/// `struct sys_setegid_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSetegidArgs {
    /// `egid`: `gid_t`.
    pub egid: Syscallarg<Gid>,
}

/// `struct sys_seteuid_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSeteuidArgs {
    /// `euid`: `uid_t`.
    pub euid: Syscallarg<Uid>,
}

/// `struct sys_pathconfat_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysPathconfatArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `name`: `int`.
    pub name: Syscallarg<i32>,
    /// `flag`: `int`.
    pub flag: Syscallarg<i32>,
}

/// `struct sys_pathconf_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysPathconfArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `name`: `int`.
    pub name: Syscallarg<i32>,
}

/// `struct sys_fpathconf_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysFpathconfArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `name`: `int`.
    pub name: Syscallarg<i32>,
}

/// `struct sys_swapctl_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSwapctlArgs {
    /// `cmd`: `int`.
    pub cmd: Syscallarg<i32>,
    /// `arg`: `const void *`.
    pub arg: Syscallarg<*const c_void>,
    /// `misc`: `int`.
    pub misc: Syscallarg<i32>,
}

/// `struct sys_getrlimit_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysGetrlimitArgs {
    /// `which`: `int`.
    pub which: Syscallarg<i32>,
    /// `rlp`: `struct rlimit *` (opaque until the structure is ported).
    pub rlp: Syscallarg<*mut c_void>,
}

/// `struct sys_setrlimit_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSetrlimitArgs {
    /// `which`: `int`.
    pub which: Syscallarg<i32>,
    /// `rlp`: `const struct rlimit *` (opaque until the structure is ported).
    pub rlp: Syscallarg<*const c_void>,
}

/// `struct sys_sysctl_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSysctlArgs {
    /// `name`: `const int *`.
    pub name: Syscallarg<*const i32>,
    /// `namelen`: `u_int`.
    pub namelen: Syscallarg<u32>,
    /// `old`: `void *`.
    pub old: Syscallarg<*mut c_void>,
    /// `oldlenp`: `size_t *`.
    pub oldlenp: Syscallarg<*mut usize>,
    /// `new`: `void *`.
    pub new: Syscallarg<*mut c_void>,
    /// `newlen`: `size_t`.
    pub newlen: Syscallarg<usize>,
}

/// `struct sys_mlock_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysMlockArgs {
    /// `addr`: `const void *`.
    pub addr: Syscallarg<*const c_void>,
    /// `len`: `size_t`.
    pub len: Syscallarg<usize>,
}

/// `struct sys_munlock_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysMunlockArgs {
    /// `addr`: `const void *`.
    pub addr: Syscallarg<*const c_void>,
    /// `len`: `size_t`.
    pub len: Syscallarg<usize>,
}

/// `struct sys_getpgid_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysGetpgidArgs {
    /// `pid`: `pid_t`.
    pub pid: Syscallarg<Pid>,
}

/// `struct sys_utrace_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysUtraceArgs {
    /// `label`: `const char *`.
    pub label: Syscallarg<*const u8>,
    /// `addr`: `const void *`.
    pub addr: Syscallarg<*const c_void>,
    /// `len`: `size_t`.
    pub len: Syscallarg<usize>,
}

/// `struct sys_minherit_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysMinheritArgs {
    /// `addr`: `void *`.
    pub addr: Syscallarg<*mut c_void>,
    /// `len`: `size_t`.
    pub len: Syscallarg<usize>,
    /// `inherit`: `int`.
    pub inherit: Syscallarg<i32>,
}

/// `struct sys_poll_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysPollArgs {
    /// `fds`: `struct pollfd *` (opaque until the structure is ported).
    pub fds: Syscallarg<*mut c_void>,
    /// `nfds`: `u_int`.
    pub nfds: Syscallarg<u32>,
    /// `timeout`: `int`.
    pub timeout: Syscallarg<i32>,
}

/// `struct sys_lchown_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysLchownArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `uid`: `uid_t`.
    pub uid: Syscallarg<Uid>,
    /// `gid`: `gid_t`.
    pub gid: Syscallarg<Gid>,
}

/// `struct sys_getsid_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysGetsidArgs {
    /// `pid`: `pid_t`.
    pub pid: Syscallarg<Pid>,
}

/// `struct sys_msync_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysMsyncArgs {
    /// `addr`: `void *`.
    pub addr: Syscallarg<*mut c_void>,
    /// `len`: `size_t`.
    pub len: Syscallarg<usize>,
    /// `flags`: `int`.
    pub flags: Syscallarg<i32>,
}

/// `struct sys_pipe_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysPipeArgs {
    /// `fdp`: `int *`.
    pub fdp: Syscallarg<*mut i32>,
}

/// `struct sys_fhopen_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysFhopenArgs {
    /// `fhp`: `const fhandle_t *` (opaque until the structure is ported).
    pub fhp: Syscallarg<*const c_void>,
    /// `flags`: `int`.
    pub flags: Syscallarg<i32>,
}

/// `struct sys_kqueue1_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysKqueue1Args {
    /// `flags`: `int`.
    pub flags: Syscallarg<i32>,
}

/// `struct sys_mlockall_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysMlockallArgs {
    /// `flags`: `int`.
    pub flags: Syscallarg<i32>,
}

/// `struct sys_getresuid_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysGetresuidArgs {
    /// `ruid`: `uid_t *`.
    pub ruid: Syscallarg<*mut Uid>,
    /// `euid`: `uid_t *`.
    pub euid: Syscallarg<*mut Uid>,
    /// `suid`: `uid_t *`.
    pub suid: Syscallarg<*mut Uid>,
}

/// `struct sys_setresuid_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSetresuidArgs {
    /// `ruid`: `uid_t`.
    pub ruid: Syscallarg<Uid>,
    /// `euid`: `uid_t`.
    pub euid: Syscallarg<Uid>,
    /// `suid`: `uid_t`.
    pub suid: Syscallarg<Uid>,
}

/// `struct sys_getresgid_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysGetresgidArgs {
    /// `rgid`: `gid_t *`.
    pub rgid: Syscallarg<*mut Gid>,
    /// `egid`: `gid_t *`.
    pub egid: Syscallarg<*mut Gid>,
    /// `sgid`: `gid_t *`.
    pub sgid: Syscallarg<*mut Gid>,
}

/// `struct sys_setresgid_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSetresgidArgs {
    /// `rgid`: `gid_t`.
    pub rgid: Syscallarg<Gid>,
    /// `egid`: `gid_t`.
    pub egid: Syscallarg<Gid>,
    /// `sgid`: `gid_t`.
    pub sgid: Syscallarg<Gid>,
}

/// `struct sys_closefrom_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysClosefromArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
}

/// `struct sys_sigaltstack_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSigaltstackArgs {
    /// `nss`: `const struct sigaltstack *` (opaque until the structure is ported).
    pub nss: Syscallarg<*const c_void>,
    /// `oss`: `struct sigaltstack *` (opaque until the structure is ported).
    pub oss: Syscallarg<*mut c_void>,
}

/// `struct sys_fhstat_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysFhstatArgs {
    /// `fhp`: `const fhandle_t *` (opaque until the structure is ported).
    pub fhp: Syscallarg<*const c_void>,
    /// `sb`: `struct stat *` (opaque until the structure is ported).
    pub sb: Syscallarg<*mut c_void>,
}

/// `struct sys___thrwakeup_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysThrwakeupArgs {
    /// `ident`: `const volatile void *`.
    pub ident: Syscallarg<*const c_void>,
    /// `n`: `int`.
    pub n: Syscallarg<i32>,
}

/// `struct sys___threxit_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysThrexitArgs {
    /// `notdead`: `pid_t *`.
    pub notdead: Syscallarg<*mut Pid>,
}

/// `struct sys___thrsigdivert_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysThrsigdivertArgs {
    /// `sigmask`: `sigset_t`.
    pub sigmask: Syscallarg<u32>,
    /// `info`: `siginfo_t *` (opaque until the structure is ported).
    pub info: Syscallarg<*mut c_void>,
    /// `timeout`: `const struct timespec *` (opaque until the structure is ported).
    pub timeout: Syscallarg<*const c_void>,
}

/// `struct sys___getcwd_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysGetcwdArgs {
    /// `buf`: `char *`.
    pub buf: Syscallarg<*mut u8>,
    /// `len`: `size_t`.
    pub len: Syscallarg<usize>,
}

/// `struct sys_adjfreq_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysAdjfreqArgs {
    /// `freq`: `const int64_t *`.
    pub freq: Syscallarg<*const i64>,
    /// `oldfreq`: `int64_t *`.
    pub oldfreq: Syscallarg<*mut i64>,
}

/// `struct sys_setrtable_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSetrtableArgs {
    /// `rtableid`: `int`.
    pub rtableid: Syscallarg<i32>,
}

/// `struct sys_faccessat_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysFaccessatArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `amode`: `int`.
    pub amode: Syscallarg<i32>,
    /// `flag`: `int`.
    pub flag: Syscallarg<i32>,
}

/// `struct sys_fchmodat_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysFchmodatArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `mode`: `mode_t`.
    pub mode: Syscallarg<Mode>,
    /// `flag`: `int`.
    pub flag: Syscallarg<i32>,
}

/// `struct sys_fchownat_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysFchownatArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `uid`: `uid_t`.
    pub uid: Syscallarg<Uid>,
    /// `gid`: `gid_t`.
    pub gid: Syscallarg<Gid>,
    /// `flag`: `int`.
    pub flag: Syscallarg<i32>,
}

/// `struct sys_linkat_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysLinkatArgs {
    /// `fd1`: `int`.
    pub fd1: Syscallarg<i32>,
    /// `path1`: `const char *`.
    pub path1: Syscallarg<*const u8>,
    /// `fd2`: `int`.
    pub fd2: Syscallarg<i32>,
    /// `path2`: `const char *`.
    pub path2: Syscallarg<*const u8>,
    /// `flag`: `int`.
    pub flag: Syscallarg<i32>,
}

/// `struct sys_mkdirat_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysMkdiratArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `mode`: `mode_t`.
    pub mode: Syscallarg<Mode>,
}

/// `struct sys_mkfifoat_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysMkfifoatArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `mode`: `mode_t`.
    pub mode: Syscallarg<Mode>,
}

/// `struct sys_mknodat_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysMknodatArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `mode`: `mode_t`.
    pub mode: Syscallarg<Mode>,
    /// `dev`: `dev_t`.
    pub dev: Syscallarg<Dev>,
}

/// `struct sys_openat_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysOpenatArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `flags`: `int`.
    pub flags: Syscallarg<i32>,
    /// `mode`: `mode_t`.
    pub mode: Syscallarg<Mode>,
}

/// `struct sys_readlinkat_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysReadlinkatArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `buf`: `char *`.
    pub buf: Syscallarg<*mut u8>,
    /// `count`: `size_t`.
    pub count: Syscallarg<usize>,
}

/// `struct sys_renameat_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysRenameatArgs {
    /// `fromfd`: `int`.
    pub fromfd: Syscallarg<i32>,
    /// `from`: `const char *`.
    pub from: Syscallarg<*const u8>,
    /// `tofd`: `int`.
    pub tofd: Syscallarg<i32>,
    /// `to`: `const char *`.
    pub to: Syscallarg<*const u8>,
}

/// `struct sys_symlinkat_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSymlinkatArgs {
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `link`: `const char *`.
    pub link: Syscallarg<*const u8>,
}

/// `struct sys_unlinkat_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysUnlinkatArgs {
    /// `fd`: `int`.
    pub fd: Syscallarg<i32>,
    /// `path`: `const char *`.
    pub path: Syscallarg<*const u8>,
    /// `flag`: `int`.
    pub flag: Syscallarg<i32>,
}

/// `struct sys___set_tcb_args`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SysSetTcbArgs {
    /// `tcb`: `void *`.
    pub tcb: Syscallarg<*mut c_void>,
}
/* </CODE> */
