/* <CODE> */
//! Bus-independent chip drivers: OpenBSD `sys/dev/ic/`.

pub mod ac97;
pub mod ahci;
pub mod ahcireg;
pub mod ahcivar;
pub mod com;
pub mod comreg;
pub mod comvar;
pub mod dcreg;
pub mod i8253reg;
pub mod mc146818reg;
pub mod mc6845reg;
pub mod ns16550reg;
pub mod nvme;
pub mod nvmeio;
pub mod nvmereg;
pub mod nvmevar;
pub mod pcdisplay;
pub mod pcdisplay_chars;
pub mod pcdisplay_subr;
pub mod pcdisplayvar;
pub mod pluart;
pub mod re;
pub mod rtl81x9reg;
pub mod siop;
pub mod siop_common;
pub mod siopreg;
pub mod siopvar;
pub mod siopvar_common;
pub mod vga;
pub mod vga_subr;
pub mod vgareg;
pub mod vgavar;
/* </CODE> */
