/* autogenerated by dtc, do not edit */
/* <LICENSES> */
/*
 * Copyright (c) 2026 Emilio Navarrete Lineros <enavarre@outlook.com>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
/* </LICENSES> */

/* <CODE> */
//! The device tree blob efiboot fills in from the ACPI tables (`efiacpi.rs`) when the
//! firmware has no device tree: `dt_blob_start`, the template of `acpi.dts` as
//! `dtc -p 16384 -H epapr -O asm` writes it (`make update-blob`), followed by 16 KB of room
//! for the nodes and properties efiboot adds.
//!
//! Upstream: sys/arch/arm64/stand/efiboot/dt_blob.S @ 3ce1f3f79392,
//! sys/arch/arm64/stand/efiboot/acpi.dts @ 3ce1f3f79392
//!
//! Neither file carries a notice: `acpi.dts` has none, `dt_blob.S` is dtc's output. The
//! source, verbatim:
//!
//! ```text
//! /dts-v1/;
//!
//! / {
//!     model = "ACPI";
//!     compatible = "openbsd,acpi";
//!     interrupt-parent = <&gic>;
//!     #address-cells = <2>;
//!     #size-cells = <2>;
//!
//!     chosen {
//!         stdout-path = "serial0:115200n8";
//!     };
//!
//!     aliases {
//!         serial0 = &uart0;
//!     };
//!
//!     cpus {
//!         #address-cells = <2>;
//!         #size-cells = <0>;
//!     };
//!
//!     psci {
//!         compatible = "arm,psci-1.0";
//!         method = "smc";
//!         status = "disabled";
//!     };
//!
//!     timer {
//!         compatible = "arm,armv8-timer";
//!         interrupts = <0 0 0>, <0 0 0>, <0 0 0>, <0 0 0>;
//!         interrupt-names = "sec-phys", "phys", "virt", "hyp-phys";
//!         status = "disabled";
//!     };
//!
//!     gic: interrupt-controller@0 {
//!         compatible = "openbsd,gic";
//!         #interrupt-cells = <3>;
//!         #address-cells = <2>;
//!         #size-cells = <2>;
//!         interrupt-controller;
//!         ranges;
//!         reg = <0x0 0x0 0x0 0x0>, <0x0 0x0 0x0 0x0>;
//!         status = "disabled";
//!     };
//!
//!     uart0: serial@0 {
//!         compatible = "openbsd,uart";
//!         reg = <0x0 0x0 0x0 0x0>;
//!         status = "disabled";
//!     };
//!
//!     acpi@0 {
//!         compatible = "openbsd,acpi-5.0";
//!         reg = <0x0 0x0 0x0 0x0>;
//!     };
//! };
//! ```
//!
//! ## Deviations
//! - The blob is built at compile time by a `const fn` from [`ROOT`], the tree above with
//!   its references written out as dtc resolves them (`<&gic>` is phandle 1, which dtc gives
//!   the node it adds a `phandle` property to; `&uart0` in `/aliases` is the path
//!   `"/serial@0"`), instead of being assembled from dtc's output. dtc's layout is kept: the
//!   header, the empty memory reservation map at 0x28, the structure block, the strings in
//!   the order of their first use (no suffix merging), then the 16384 bytes of padding
//!   (`-p 16384`). The reference test (`just test-ref`) compares the bytes with
//!   `dt_blob.S`. The labels `dt_header`, `gic`, `uart0`... which nothing reads, are not
//!   defined.

use libkern::staticcell::StaticCell;

use crate::fdt::{FDT_END, FDT_MAGIC, FDT_NODE_BEGIN, FDT_NODE_END, FDT_PROPERTY};

/// `-p 16384`: the free space after the strings.
const DT_PAD: usize = 16384;
/// The header's size, then the memory reservation map's (its terminating entry).
const DT_HEADER_SIZE: usize = 40;
const DT_RSVMAP_SIZE: usize = 16;
/// `version`, `last_comp_version` (`-H epapr`).
const DT_VERSION: u32 = 0x11;
const DT_LAST_COMP_VERSION: u32 = 0x10;

/// A property's value.
pub enum Value {
    /// No value (`interrupt-controller;`).
    Empty,
    /// Cells (`<...>`), big-endian words.
    Cells(&'static [u32]),
    /// Strings, each NUL-terminated.
    Strings(&'static [&'static str]),
}

/// A property.
pub struct Prop {
    /// Its name.
    pub name: &'static str,
    /// Its value.
    pub value: Value,
}

/// A node.
pub struct Node {
    /// Its name (with the unit address).
    pub name: &'static str,
    /// Its properties, in source order.
    pub props: &'static [Prop],
    /// Its children, in source order.
    pub children: &'static [Node],
}

/// `acpi.dts`, references resolved.
pub const ROOT: Node = Node {
    name: "",
    props: &[
        Prop {
            name: "model",
            value: Value::Strings(&["ACPI"]),
        },
        Prop {
            name: "compatible",
            value: Value::Strings(&["openbsd,acpi"]),
        },
        Prop {
            // <&gic>
            name: "interrupt-parent",
            value: Value::Cells(&[1]),
        },
        Prop {
            name: "#address-cells",
            value: Value::Cells(&[2]),
        },
        Prop {
            name: "#size-cells",
            value: Value::Cells(&[2]),
        },
    ],
    children: &[
        Node {
            name: "chosen",
            props: &[Prop {
                name: "stdout-path",
                value: Value::Strings(&["serial0:115200n8"]),
            }],
            children: &[],
        },
        Node {
            name: "aliases",
            props: &[Prop {
                // &uart0
                name: "serial0",
                value: Value::Strings(&["/serial@0"]),
            }],
            children: &[],
        },
        Node {
            name: "cpus",
            props: &[
                Prop {
                    name: "#address-cells",
                    value: Value::Cells(&[2]),
                },
                Prop {
                    name: "#size-cells",
                    value: Value::Cells(&[0]),
                },
            ],
            children: &[],
        },
        Node {
            name: "psci",
            props: &[
                Prop {
                    name: "compatible",
                    value: Value::Strings(&["arm,psci-1.0"]),
                },
                Prop {
                    name: "method",
                    value: Value::Strings(&["smc"]),
                },
                Prop {
                    name: "status",
                    value: Value::Strings(&["disabled"]),
                },
            ],
            children: &[],
        },
        Node {
            name: "timer",
            props: &[
                Prop {
                    name: "compatible",
                    value: Value::Strings(&["arm,armv8-timer"]),
                },
                Prop {
                    name: "interrupts",
                    value: Value::Cells(&[0; 12]),
                },
                Prop {
                    name: "interrupt-names",
                    value: Value::Strings(&["sec-phys", "phys", "virt", "hyp-phys"]),
                },
                Prop {
                    name: "status",
                    value: Value::Strings(&["disabled"]),
                },
            ],
            children: &[],
        },
        Node {
            // gic:
            name: "interrupt-controller@0",
            props: &[
                Prop {
                    name: "compatible",
                    value: Value::Strings(&["openbsd,gic"]),
                },
                Prop {
                    name: "#interrupt-cells",
                    value: Value::Cells(&[3]),
                },
                Prop {
                    name: "#address-cells",
                    value: Value::Cells(&[2]),
                },
                Prop {
                    name: "#size-cells",
                    value: Value::Cells(&[2]),
                },
                Prop {
                    name: "interrupt-controller",
                    value: Value::Empty,
                },
                Prop {
                    name: "ranges",
                    value: Value::Empty,
                },
                Prop {
                    name: "reg",
                    value: Value::Cells(&[0; 8]),
                },
                Prop {
                    name: "status",
                    value: Value::Strings(&["disabled"]),
                },
                Prop {
                    // dtc's, for <&gic>
                    name: "phandle",
                    value: Value::Cells(&[1]),
                },
            ],
            children: &[],
        },
        Node {
            // uart0:
            name: "serial@0",
            props: &[
                Prop {
                    name: "compatible",
                    value: Value::Strings(&["openbsd,uart"]),
                },
                Prop {
                    name: "reg",
                    value: Value::Cells(&[0; 4]),
                },
                Prop {
                    name: "status",
                    value: Value::Strings(&["disabled"]),
                },
            ],
            children: &[],
        },
        Node {
            name: "acpi@0",
            props: &[
                Prop {
                    name: "compatible",
                    value: Value::Strings(&["openbsd,acpi-5.0"]),
                },
                Prop {
                    name: "reg",
                    value: Value::Cells(&[0; 4]),
                },
            ],
            children: &[],
        },
    ],
};

/// The number of properties of the tree.
const NPROPS: usize = count_props(&ROOT);
/// The property names in the order dtc meets them (depth first, properties first).
const NAMES: [&str; NPROPS] = {
    let mut names = [""; NPROPS];
    collect_names(&ROOT, &mut names, 0);
    names
};
/// The structure block's size: the tree and `FDT_END`.
const DT_STRUCT_SIZE: usize = node_size(&ROOT) + 4;
/// The strings block's size: each name once, NUL-terminated.
const DT_STRINGS_SIZE: usize = strings_size();
/// The structure block's offset.
const DT_STRUCT_OFF: usize = DT_HEADER_SIZE + DT_RSVMAP_SIZE;
/// The strings block's offset.
const DT_STRINGS_OFF: usize = DT_STRUCT_OFF + DT_STRUCT_SIZE;
/// `_dt_blob_abs_end - _dt_blob_start`: the blob and its padding.
pub const DT_BLOB_SIZE: usize = DT_STRINGS_OFF + DT_STRINGS_SIZE + DT_PAD;

/// The blob's bytes as dtc writes them (the tests work on copies).
#[cfg(test)]
pub static DT_BLOB_TEMPLATE: [u8; DT_BLOB_SIZE] = build();

/// The blob, aligned for the word reads of the tree code.
#[repr(C, align(8))]
pub struct DtBlob(pub [u8; DT_BLOB_SIZE]);

/// A blob being written: the bytes and the write position.
struct Writer {
    buf: [u8; DT_BLOB_SIZE],
    pos: usize,
}

impl Writer {
    /// `.byte`.
    const fn byte(&mut self, b: u8) {
        self.buf[self.pos] = b;
        self.pos += 1;
    }

    /// A big-endian word.
    const fn be32(&mut self, v: u32) {
        let b = v.to_be_bytes();
        let mut i = 0;
        while i < 4 {
            self.byte(b[i]);
            i += 1;
        }
    }

    /// `.asciz`.
    const fn asciz(&mut self, s: &str) {
        let b = s.as_bytes();
        let mut i = 0;
        while i < b.len() {
            self.byte(b[i]);
            i += 1;
        }
        self.byte(0);
    }

    /// `.balign 4, 0`.
    const fn balign4(&mut self) {
        while !self.pos.is_multiple_of(4) {
            self.byte(0);
        }
    }

    /// A node, its properties and its children.
    const fn node(&mut self, n: &Node) {
        self.be32(FDT_NODE_BEGIN);
        self.asciz(n.name);
        self.balign4();
        let mut i = 0;
        while i < n.props.len() {
            let p = &n.props[i];
            self.be32(FDT_PROPERTY);
            self.be32(value_size(&p.value) as u32);
            self.be32(name_offset(p.name) as u32);
            match p.value {
                Value::Empty => {}
                Value::Cells(c) => {
                    let mut j = 0;
                    while j < c.len() {
                        self.be32(c[j]);
                        j += 1;
                    }
                }
                Value::Strings(s) => {
                    let mut j = 0;
                    while j < s.len() {
                        self.asciz(s[j]);
                        j += 1;
                    }
                }
            }
            self.balign4();
            i += 1;
        }
        let mut i = 0;
        while i < n.children.len() {
            self.node(&n.children[i]);
            i += 1;
        }
        self.be32(FDT_NODE_END);
    }
}

/// `dt_blob_start`: the blob, which `efi_acpi` edits in place.
pub static DT_BLOB: StaticCell<DtBlob> = StaticCell::new(DtBlob(build()));

/// `const` string equality.
const fn str_eq(a: &str, b: &str) -> bool {
    let (a, b) = (a.as_bytes(), b.as_bytes());
    if a.len() != b.len() {
        return false;
    }
    let mut i = 0;
    while i < a.len() {
        if a[i] != b[i] {
            return false;
        }
        i += 1;
    }
    true
}

/// The properties of `n` and its descendants.
const fn count_props(n: &Node) -> usize {
    let mut count = n.props.len();
    let mut i = 0;
    while i < n.children.len() {
        count += count_props(&n.children[i]);
        i += 1;
    }
    count
}

/// Writes the property names of `n` and its descendants into `names` from `at`; the next
/// free index.
const fn collect_names(n: &Node, names: &mut [&'static str; NPROPS], at: usize) -> usize {
    let mut at = at;
    let mut i = 0;
    while i < n.props.len() {
        names[at] = n.props[i].name;
        at += 1;
        i += 1;
    }
    let mut i = 0;
    while i < n.children.len() {
        at = collect_names(&n.children[i], names, at);
        i += 1;
    }
    at
}

/// The index of the first use of `name` in [`NAMES`].
const fn first_use(name: &str) -> usize {
    let mut i = 0;
    while i < NPROPS {
        if str_eq(NAMES[i], name) {
            return i;
        }
        i += 1;
    }
    NPROPS
}

/// The offset of `name` in the strings block.
const fn name_offset(name: &str) -> usize {
    let first = first_use(name);
    let mut off = 0;
    let mut i = 0;
    while i < first {
        if first_use(NAMES[i]) == i {
            off += NAMES[i].len() + 1;
        }
        i += 1;
    }
    off
}

/// The strings block's size.
const fn strings_size() -> usize {
    let mut size = 0;
    let mut i = 0;
    while i < NPROPS {
        if first_use(NAMES[i]) == i {
            size += NAMES[i].len() + 1;
        }
        i += 1;
    }
    size
}

/// The size of a property's value.
const fn value_size(v: &Value) -> usize {
    match v {
        Value::Empty => 0,
        Value::Cells(c) => 4 * c.len(),
        Value::Strings(s) => {
            let mut size = 0;
            let mut i = 0;
            while i < s.len() {
                size += s[i].len() + 1;
                i += 1;
            }
            size
        }
    }
}

/// `n`'s size in the structure block.
const fn node_size(n: &Node) -> usize {
    let mut size = 4 + (n.name.len() + 1).div_ceil(4) * 4;
    let mut i = 0;
    while i < n.props.len() {
        size += 12 + value_size(&n.props[i].value).div_ceil(4) * 4;
        i += 1;
    }
    let mut i = 0;
    while i < n.children.len() {
        size += node_size(&n.children[i]);
        i += 1;
    }
    size + 4
}

/// The blob, as dtc lays it out.
const fn build() -> [u8; DT_BLOB_SIZE] {
    let mut w = Writer {
        buf: [0; DT_BLOB_SIZE],
        pos: 0,
    };

    // header
    w.be32(FDT_MAGIC);
    w.be32(DT_BLOB_SIZE as u32); // totalsize
    w.be32(DT_STRUCT_OFF as u32); // off_dt_struct
    w.be32(DT_STRINGS_OFF as u32); // off_dt_strings
    w.be32(DT_HEADER_SIZE as u32); // off_mem_rsvmap
    w.be32(DT_VERSION); // version
    w.be32(DT_LAST_COMP_VERSION); // last_comp_version
    w.be32(0); // boot_cpuid_phys
    w.be32(DT_STRINGS_SIZE as u32); // size_dt_strings
    w.be32(DT_STRUCT_SIZE as u32); // size_dt_struct

    // Memory reserve map from source file: the terminating entry
    w.pos += DT_RSVMAP_SIZE;

    w.node(&ROOT);
    w.be32(FDT_END);

    let mut i = 0;
    while i < NPROPS {
        if first_use(NAMES[i]) == i {
            w.asciz(NAMES[i]);
        }
        i += 1;
    }

    // the padding stays zero
    w.buf
}

/// `dt_blob_start`.
pub fn dt_blob_start() -> *mut u8 {
    DT_BLOB.as_ptr().cast()
}

const _: () = assert!(DT_STRUCT_OFF.is_multiple_of(8));
/* </CODE> */

/* <TESTS> */
#[cfg(test)]
mod tests {
    // The blob's layout, and (reference test) its bytes against dtc's `dt_blob.S`.

    use super::*;
    use crate::fdt::Fdt;
    use std::collections::BTreeMap;
    use std::string::String;
    use std::vec::Vec;

    /// A copy of the blob, as `efi_acpi` would edit it.
    fn blob() -> Vec<u8> {
        DT_BLOB_TEMPLATE.to_vec()
    }

    #[test]
    fn header_and_blocks() {
        let b = blob();
        let w = |o: usize| u32::from_be_bytes([b[o], b[o + 1], b[o + 2], b[o + 3]]);
        assert_eq!(w(0), FDT_MAGIC);
        assert_eq!(w(4) as usize, b.len());
        assert_eq!(w(8), 0x38);
        assert_eq!(w(16), 0x28);
        assert_eq!((w(20), w(24)), (0x11, 0x10));
        assert_eq!(w(12) as usize, 0x38 + w(36) as usize);
        // the strings end where the padding starts
        assert_eq!(w(12) as usize + w(32) as usize + 16384, b.len());
        assert_eq!(&b[w(12) as usize..w(12) as usize + 6], b"model\0");
    }

    #[test]
    fn the_tree_reads_back() {
        let mut b = blob();
        let mut t = Fdt::new();
        // SAFETY: `b` is the whole blob, used by nothing else.
        assert_eq!(unsafe { t.init(b.as_mut_ptr()) }, 0x11);
        let root = t.find_node(b"/").unwrap();
        assert_eq!(t.property(root, b"model"), Some(&b"ACPI\0"[..]));
        assert_eq!(t.node_property_int(root, b"interrupt-parent"), Some(1));
        let gic = t.find_node(b"/interrupt-controller").unwrap();
        assert_eq!(t.node_name(gic), Some(&b"interrupt-controller@0"[..]));
        assert_eq!(t.node_property_int(gic, b"phandle"), Some(1));
        assert_eq!(t.node_property(gic, b"ranges").0, 0);
        let timer = t.find_node(b"/timer").unwrap();
        assert!(t.node_is_compatible(timer, b"arm,armv8-timer"));
        assert_eq!(
            t.property(timer, b"interrupt-names"),
            Some(&b"sec-phys\0phys\0virt\0hyp-phys\0"[..])
        );
        let aliases = t.find_node(b"/aliases").unwrap();
        assert_eq!(t.property(aliases, b"serial0"), Some(&b"/serial@0\0"[..]));
        let names: Vec<_> = core::iter::successors(t.child_node(root), |&n| t.next_node(Some(n)))
            .map(|n| String::from_utf8_lossy(t.node_name(n).unwrap()).into_owned())
            .collect();
        assert_eq!(
            names,
            [
                "chosen",
                "aliases",
                "cpus",
                "psci",
                "timer",
                "interrupt-controller@0",
                "serial@0",
                "acpi@0"
            ]
        );
    }

    /// `$OPENBSD_SRC` (`just test-ref`), relative paths from the workspace root.
    fn openbsd_src() -> std::path::PathBuf {
        let Some(dir) = std::env::var_os("OPENBSD_SRC") else {
            panic!("OPENBSD_SRC is not set; run `just test-ref`");
        };
        let dir = std::path::PathBuf::from(dir);
        if dir.is_absolute() {
            dir
        } else {
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../../../..")
                .join(dir)
        }
    }

    /// Assembles dtc's `-O asm` output: labels, `.byte` (a literal or a byte of the difference
    /// of two labels), `.long`, `.asciz`, `.balign`, `.space`; two passes for the labels.
    fn assemble(src: &str) -> Vec<u8> {
        let pass = |labels: &BTreeMap<String, usize>| {
            let mut out: Vec<u8> = Vec::new();
            let mut defined = BTreeMap::new();
            for line in src.lines() {
                let s = line.trim();
                if s.is_empty() || s.starts_with("/*") || s.starts_with(".globl") {
                    continue;
                }
                if let Some(label) = s.strip_suffix(':') {
                    defined.insert(String::from(label), out.len());
                } else if let Some(e) = s.strip_prefix(".byte") {
                    let e = e.trim();
                    if let Some(hex) = e.strip_prefix("0x") {
                        out.push(u8::from_str_radix(hex, 16).unwrap());
                        continue;
                    }
                    // ((a - b) >> n) & 0xff, or (a - b) & 0xff
                    let inner = &e[e.rfind('(').unwrap() + 1..e.find(')').unwrap()];
                    let (a, b) = inner.split_once(" - ").unwrap();
                    let shift = e
                        .split_once(">> ")
                        .map_or(0, |(_, r)| r.split(')').next().unwrap().parse().unwrap());
                    let v = labels.get(a).copied().unwrap_or(0) as i64
                        - labels.get(b).copied().unwrap_or(0) as i64;
                    out.push(((v >> shift) & 0xff) as u8);
                } else if let Some(e) = s.strip_prefix(".long") {
                    for x in e.split(',') {
                        let x = x.trim();
                        let v = x.strip_prefix("0x").map_or_else(
                            || x.parse::<u32>().unwrap(),
                            |h| u32::from_str_radix(h, 16).unwrap(),
                        );
                        // dtc writes only zeros here, whose byte order does not matter
                        out.extend_from_slice(&v.to_le_bytes());
                    }
                } else if let Some(e) = s.strip_prefix(".asciz") {
                    out.extend_from_slice(e.trim().trim_matches('"').as_bytes());
                    out.push(0);
                } else if let Some(e) = s.strip_prefix(".balign") {
                    let n: usize = e.split(',').next().unwrap().trim().parse().unwrap();
                    while !out.len().is_multiple_of(n) {
                        out.push(0);
                    }
                } else if let Some(e) = s.strip_prefix(".space") {
                    let n: usize = e.split(',').next().unwrap().trim().parse().unwrap();
                    out.resize(out.len() + n, 0);
                } else {
                    panic!("dt_blob.S: unexpected line {s:?}");
                }
            }
            (out, defined)
        };
        let (_, labels) = pass(&BTreeMap::new());
        pass(&labels).0
    }

    #[test]
    #[ignore = "reads the C reference tree (just test-ref)"]
    fn same_bytes_as_dt_blob_s() {
        let path = openbsd_src().join("sys/arch/arm64/stand/efiboot/dt_blob.S");
        let src =
            std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
        let reference = assemble(&src);
        assert_eq!(reference.len(), DT_BLOB_SIZE);
        assert_eq!(blob(), reference);
    }
}
/* </TESTS> */
