/*	$OpenBSD: rijndael.h,v 1.13 2008/06/09 07:49:45 djm Exp $ */
/*	$OpenBSD: rijndael.c,v 1.20 2014/11/17 12:27:47 mikeb Exp $ */
/* <LICENSES> */
/*
 * Copyright (c) 2026 Emilio Navarrete Lineros <enavarre@outlook.com>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

/* *
 * rijndael-alg-fst.h
 *
 * @version 3.0 (December 2000)
 *
 * Optimised ANSI C code for the Rijndael cipher (now AES)
 *
 * @author Vincent Rijmen <vincent.rijmen@esat.kuleuven.ac.be>
 * @author Antoon Bosselaers <antoon.bosselaers@esat.kuleuven.ac.be>
 * @author Paulo Barreto <paulo.barreto@terra.com.br>
 *
 * This code is hereby placed in the public domain.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHORS ''AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* *
 * rijndael-alg-fst.c
 *
 * @version 3.0 (December 2000)
 *
 * Optimised ANSI C code for the Rijndael cipher (now AES)
 *
 * @author Vincent Rijmen <vincent.rijmen@esat.kuleuven.ac.be>
 * @author Antoon Bosselaers <antoon.bosselaers@esat.kuleuven.ac.be>
 * @author Paulo Barreto <paulo.barreto@terra.com.br>
 *
 * This code is hereby placed in the public domain.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHORS ''AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/* </LICENSES> */

/* <CODE> */
//! Rijndael (AES) in the table-driven form of Rijmen, Bosselaers and Barreto's
//! `rijndael-alg-fst`: the cipher `enc_xform_aes_xts` uses for XTS. (`aes.c` is the
//! constant-time implementation the rest of the crypto framework uses.)
//!
//! Upstream: sys/crypto/rijndael.h @ 3ce1f3f79392, sys/crypto/rijndael.c @ 3ce1f3f79392
//!
//! ## Deviations
//! - The header and the file share this module; `rijndael_ctx` is [`RijndaelCtx`] (its `Nr`
//!   field keeps its C spelling).
//! - The eight 1 KiB lookup tables `Te0` to `Te3`, `Td0` to `Td3` and `Td4` are computed at
//!   compile time by `const fn`s from their definition (the comment above them in the C:
//!   `Te0[x] = S[x].[02, 01, 01, 03]` and so on, with `S` the AES S-box generated by the
//!   inversion in GF(2^8) and the affine map); the FIPS 197 vectors in the tests exercise
//!   them.
//! - `rijndaelKeySetupEnc` computes the round function of the key schedule with the S-box
//!   (`SubWord(RotWord(w)) ^ Rcon`) where the C reads the S-box out of masked `Te` words and
//!   unrolls one loop per key size; the schedule is the same. The key setup functions return
//!   `Result` (`EINVAL` for a size other than 128, 192 or 256 bits) instead of a round count
//!   or 0, and `rijndael_set_key*` `Result<(), Errno>` instead of 0 or -1.
//! - `FULL_UNROLL` is not ported: the C leaves it undefined, so the looped rounds are the code
//!   that runs. `rijndaelDecrypt` stays private (`static` in the C).
//! - The block functions take 16-byte arrays; the in-place calls (`rijndael_encrypt(ctx, t, t)`
//!   in `xform.c`) copy the block first.

use crate::sys::errno::Errno;

/// `AES_MAXKEYBITS`.
pub const AES_MAXKEYBITS: usize = 256;
/// `AES_MAXKEYBYTES`.
pub const AES_MAXKEYBYTES: usize = AES_MAXKEYBITS / 8;
/// `AES_MAXROUNDS`: for 256-bit keys, fewer for less.
pub const AES_MAXROUNDS: usize = 14;

/// `rcon`: for 128-bit blocks, Rijndael never uses more than 10 rcon values.
const RCON: [u32; 10] = [
    0x01000000, 0x02000000, 0x04000000, 0x08000000, 0x10000000, 0x20000000, 0x40000000, 0x80000000,
    0x1B000000, 0x36000000,
];

/// Multiplication by x in GF(2^8) modulo x^8 + x^4 + x^3 + x + 1.
const fn xtime(x: u8) -> u8 {
    (x << 1) ^ if x & 0x80 != 0 { 0x1b } else { 0 }
}

/// Multiplication in GF(2^8).
const fn gmul(a: u8, b: u8) -> u8 {
    let mut a = a;
    let mut b = b;
    let mut p = 0u8;
    while b != 0 {
        if b & 1 != 0 {
            p ^= a;
        }
        a = xtime(a);
        b >>= 1;
    }
    p
}

/// The S-box and its inverse: the multiplicative inverse in GF(2^8) followed by the affine
/// transformation, found by walking the powers of 3 (`p`) and their inverses (`q`).
const fn gen_sboxes() -> ([u8; 256], [u8; 256]) {
    let mut sbox = [0u8; 256];
    let mut inv = [0u8; 256];
    let mut p = 1u8;
    let mut q = 1u8;

    loop {
        // multiply p by 3
        p = p ^ (p << 1) ^ if p & 0x80 != 0 { 0x1b } else { 0 };
        // divide q by 3 (equals multiplication by 0xf6)
        q ^= q << 1;
        q ^= q << 2;
        q ^= q << 4;
        if q & 0x80 != 0 {
            q ^= 0x09;
        }
        // the affine transformation
        let x = q ^ q.rotate_left(1) ^ q.rotate_left(2) ^ q.rotate_left(3) ^ q.rotate_left(4);
        sbox[p as usize] = x ^ 0x63;
        if p == 1 {
            break;
        }
    }
    sbox[0] = 0x63;

    let mut i = 0;
    while i < 256 {
        inv[sbox[i] as usize] = i as u8;
        i += 1;
    }
    (sbox, inv)
}

/// `S[x]`.
static SBOX: [u8; 256] = gen_sboxes().0;

/// `Td4[x] = Si[x].[01]`: the inverse S-box.
static TD4: [u8; 256] = gen_sboxes().1;

/// The table `t` with every entry rotated right by `n` bits.
const fn rotr_table(t: [u32; 256], n: u32) -> [u32; 256] {
    let mut r = [0u32; 256];
    let mut x = 0;
    while x < 256 {
        r[x] = t[x].rotate_right(n);
        x += 1;
    }
    r
}

/// `Te0[x] = S[x].[02, 01, 01, 03]`.
const fn gen_te0() -> [u32; 256] {
    let sbox = gen_sboxes().0;
    let mut t = [0u32; 256];
    let mut x = 0;
    while x < 256 {
        let s = sbox[x];
        t[x] = u32::from_be_bytes([gmul(s, 2), s, s, gmul(s, 3)]);
        x += 1;
    }
    t
}

/// `Td0[x] = Si[x].[0e, 09, 0d, 0b]`.
const fn gen_td0() -> [u32; 256] {
    let inv = gen_sboxes().1;
    let mut t = [0u32; 256];
    let mut x = 0;
    while x < 256 {
        let s = inv[x];
        t[x] = u32::from_be_bytes([gmul(s, 0x0e), gmul(s, 0x09), gmul(s, 0x0d), gmul(s, 0x0b)]);
        x += 1;
    }
    t
}

/// `Te0`.
static TE0: [u32; 256] = gen_te0();
/// `Te1[x] = S[x].[03, 02, 01, 01]`.
static TE1: [u32; 256] = rotr_table(gen_te0(), 8);
/// `Te2[x] = S[x].[01, 03, 02, 01]`.
static TE2: [u32; 256] = rotr_table(gen_te0(), 16);
/// `Te3[x] = S[x].[01, 01, 03, 02]`.
static TE3: [u32; 256] = rotr_table(gen_te0(), 24);
/// `Td0`.
static TD0: [u32; 256] = gen_td0();
/// `Td1[x] = Si[x].[0b, 0e, 09, 0d]`.
static TD1: [u32; 256] = rotr_table(gen_td0(), 8);
/// `Td2[x] = Si[x].[0d, 0b, 0e, 09]`.
static TD2: [u32; 256] = rotr_table(gen_td0(), 16);
/// `Td3[x] = Si[x].[09, 0d, 0b, 0e]`.
static TD3: [u32; 256] = rotr_table(gen_td0(), 24);

/// `rijndael_ctx`: the key schedules of one key.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[allow(non_snake_case)] // the C field name
pub struct RijndaelCtx {
    /// `enc_only`: context contains only encrypt schedule.
    pub enc_only: i32,
    /// `Nr`: key-length-dependent number of rounds.
    pub Nr: i32,
    /// `ek`: encrypt key schedule.
    pub ek: [u32; 4 * (AES_MAXROUNDS + 1)],
    /// `dk`: decrypt key schedule.
    pub dk: [u32; 4 * (AES_MAXROUNDS + 1)],
}

impl Default for RijndaelCtx {
    fn default() -> Self {
        Self {
            enc_only: 0,
            Nr: 0,
            ek: [0; 4 * (AES_MAXROUNDS + 1)],
            dk: [0; 4 * (AES_MAXROUNDS + 1)],
        }
    }
}

/// `GETU32`: the big-endian word at the start of `pt`.
fn getu32(pt: &[u8]) -> u32 {
    u32::from_be_bytes([pt[0], pt[1], pt[2], pt[3]])
}

/// `SubWord`: the S-box on each byte of `w`.
fn sub_word(w: u32) -> u32 {
    let b = w.to_be_bytes();
    u32::from_be_bytes([
        SBOX[b[0] as usize],
        SBOX[b[1] as usize],
        SBOX[b[2] as usize],
        SBOX[b[3] as usize],
    ])
}

/// `rijndaelKeySetupEnc`: expand the cipher key into the encryption key schedule `rk`
/// (`4 * (Nr + 1)` words); the number of rounds for the key size.
#[allow(non_snake_case)] // the C name
pub fn rijndaelKeySetupEnc(rk: &mut [u32], cipherKey: &[u8], keyBits: i32) -> Result<i32, Errno> {
    let nk = match keyBits {
        128 => 4,
        192 => 6,
        256 => 8,
        _ => return Err(Errno::EINVAL),
    };
    let nr = nk + 6;

    for i in 0..nk {
        rk[i] = getu32(&cipherKey[4 * i..]);
    }
    for i in nk..4 * (nr + 1) {
        let mut temp = rk[i - 1];
        if i % nk == 0 {
            temp = sub_word(temp.rotate_left(8)) ^ RCON[i / nk - 1];
        } else if nk > 6 && i % nk == 4 {
            temp = sub_word(temp);
        }
        rk[i] = rk[i - nk] ^ temp;
    }
    Ok(nr as i32)
}

/// `rijndaelKeySetupDec`: expand the cipher key into the decryption key schedule.
#[allow(non_snake_case)] // the C name
pub fn rijndaelKeySetupDec(rk: &mut [u32], cipherKey: &[u8], keyBits: i32) -> Result<i32, Errno> {
    // expand the cipher key:
    let nr = rijndaelKeySetupEnc(rk, cipherKey, keyBits)? as usize;

    // invert the order of the round keys:
    let (mut i, mut j) = (0, 4 * nr);
    while i < j {
        for k in 0..4 {
            rk.swap(i + k, j + k);
        }
        i += 4;
        j -= 4;
    }
    // apply the inverse MixColumn transform to all round keys but the first and the last:
    for r in 1..nr {
        for w in &mut rk[4 * r..4 * r + 4] {
            *w = TD0[SBOX[(*w >> 24) as usize] as usize]
                ^ TD1[SBOX[((*w >> 16) & 0xff) as usize] as usize]
                ^ TD2[SBOX[((*w >> 8) & 0xff) as usize] as usize]
                ^ TD3[SBOX[(*w & 0xff) as usize] as usize];
        }
    }
    Ok(nr as i32)
}

/// `rijndaelEncrypt`: encrypts the block `pt` under the schedule `rk` of `Nr` rounds.
#[allow(non_snake_case)] // the C name
pub fn rijndaelEncrypt(rk: &[u32], Nr: i32, pt: &[u8; 16], ct: &mut [u8; 16]) {
    // map byte array block to cipher state and add initial round key:
    let mut s = [0u32; 4];
    for (j, w) in s.iter_mut().enumerate() {
        *w = getu32(&pt[4 * j..]) ^ rk[j];
    }

    // Nr - 1 full rounds:
    for r in 1..Nr as usize {
        let mut t = [0u32; 4];
        for j in 0..4 {
            t[j] = TE0[(s[j] >> 24) as usize]
                ^ TE1[((s[(j + 1) % 4] >> 16) & 0xff) as usize]
                ^ TE2[((s[(j + 2) % 4] >> 8) & 0xff) as usize]
                ^ TE3[(s[(j + 3) % 4] & 0xff) as usize]
                ^ rk[4 * r + j];
        }
        s = t;
    }

    // apply last round and map cipher state to byte array block:
    let rk = &rk[4 * Nr as usize..];
    for j in 0..4 {
        let w = (TE2[(s[j] >> 24) as usize] & 0xff000000)
            ^ (TE3[((s[(j + 1) % 4] >> 16) & 0xff) as usize] & 0x00ff0000)
            ^ (TE0[((s[(j + 2) % 4] >> 8) & 0xff) as usize] & 0x0000ff00)
            ^ (TE1[(s[(j + 3) % 4] & 0xff) as usize] & 0x000000ff)
            ^ rk[j];
        ct[4 * j..4 * j + 4].copy_from_slice(&w.to_be_bytes());
    }
}

/// `rijndaelDecrypt`: decrypts the block `ct` under the decryption schedule `rk`.
#[allow(non_snake_case)] // the C name
fn rijndaelDecrypt(rk: &[u32], Nr: i32, ct: &[u8; 16], pt: &mut [u8; 16]) {
    // map byte array block to cipher state and add initial round key:
    let mut s = [0u32; 4];
    for (j, w) in s.iter_mut().enumerate() {
        *w = getu32(&ct[4 * j..]) ^ rk[j];
    }

    // Nr - 1 full rounds:
    for r in 1..Nr as usize {
        let mut t = [0u32; 4];
        for j in 0..4 {
            t[j] = TD0[(s[j] >> 24) as usize]
                ^ TD1[((s[(j + 3) % 4] >> 16) & 0xff) as usize]
                ^ TD2[((s[(j + 2) % 4] >> 8) & 0xff) as usize]
                ^ TD3[(s[(j + 1) % 4] & 0xff) as usize]
                ^ rk[4 * r + j];
        }
        s = t;
    }

    // apply last round and map cipher state to byte array block:
    let rk = &rk[4 * Nr as usize..];
    for j in 0..4 {
        let w = (u32::from(TD4[(s[j] >> 24) as usize]) << 24)
            ^ (u32::from(TD4[((s[(j + 3) % 4] >> 16) & 0xff) as usize]) << 16)
            ^ (u32::from(TD4[((s[(j + 2) % 4] >> 8) & 0xff) as usize]) << 8)
            ^ u32::from(TD4[(s[(j + 1) % 4] & 0xff) as usize])
            ^ rk[j];
        pt[4 * j..4 * j + 4].copy_from_slice(&w.to_be_bytes());
    }
}

/// `rijndael_set_key_enc_only`: setup key context for encryption only.
pub fn rijndael_set_key_enc_only(
    ctx: &mut RijndaelCtx,
    key: &[u8],
    bits: i32,
) -> Result<(), Errno> {
    let rounds = rijndaelKeySetupEnc(&mut ctx.ek, key, bits)?;

    ctx.Nr = rounds;
    ctx.enc_only = 1;

    Ok(())
}

/// `rijndael_set_key`: setup key context for both encryption and decryption.
pub fn rijndael_set_key(ctx: &mut RijndaelCtx, key: &[u8], bits: i32) -> Result<(), Errno> {
    let rounds = rijndaelKeySetupEnc(&mut ctx.ek, key, bits)?;
    if rijndaelKeySetupDec(&mut ctx.dk, key, bits)? != rounds {
        return Err(Errno::EINVAL);
    }

    ctx.Nr = rounds;
    ctx.enc_only = 0;

    Ok(())
}

/// `rijndael_decrypt`.
pub fn rijndael_decrypt(ctx: &RijndaelCtx, src: &[u8; 16], dst: &mut [u8; 16]) {
    rijndaelDecrypt(&ctx.dk, ctx.Nr, src, dst);
}

/// `rijndael_encrypt`.
pub fn rijndael_encrypt(ctx: &RijndaelCtx, src: &[u8; 16], dst: &mut [u8; 16]) {
    rijndaelEncrypt(&ctx.ek, ctx.Nr, src, dst);
}
/* </CODE> */

/* <TESTS> */
#[cfg(test)]
mod tests {
    // Known-answer tests for the table-driven Rijndael: FIPS 197 appendices A.1 (key expansion),
    // B and C (the example vectors for 128, 192 and 256-bit keys), the generated tables, and a
    // reference-backed comparison of every table with the C file's.

    use super::*;
    use crate::crypto::testutil::{c_table, hex, hexn};

    fn key() -> [u8; 32] {
        let mut k = [0u8; 32];
        for (i, b) in k.iter_mut().enumerate() {
            *b = i as u8;
        }
        k
    }

    const PT: &str = "00112233445566778899aabbccddeeff";

    #[test]
    fn fips197_appendix_c() {
        let want = [
            (128, "69c4e0d86a7b0430d8cdb78070b4c55a"),
            (192, "dda97ca4864cdfe06eaf70a0ec0d7191"),
            (256, "8ea2b7ca516745bfeafc49904b496089"),
        ];
        for (bits, ct) in want {
            let mut ctx = RijndaelCtx::default();
            let k = key();
            assert_eq!(
                rijndael_set_key(&mut ctx, &k[..bits / 8], bits as i32),
                Ok(())
            );
            assert_eq!(ctx.Nr, bits as i32 / 32 + 6);
            assert_eq!(ctx.enc_only, 0);

            let pt: [u8; 16] = hexn(PT);
            let mut out = [0u8; 16];
            rijndael_encrypt(&ctx, &pt, &mut out);
            assert_eq!(out.to_vec(), hex(ct), "encrypt {bits}");
            let mut back = [0u8; 16];
            rijndael_decrypt(&ctx, &out, &mut back);
            assert_eq!(back, pt, "decrypt {bits}");
        }
    }

    #[test]
    fn fips197_appendix_b() {
        let k: [u8; 16] = hexn("2b7e151628aed2a6abf7158809cf4f3c");
        let pt: [u8; 16] = hexn("3243f6a8885a308d313198a2e0370734");
        let mut ctx = RijndaelCtx::default();
        assert_eq!(rijndael_set_key(&mut ctx, &k, 128), Ok(()));
        let mut out = [0u8; 16];
        rijndael_encrypt(&ctx, &pt, &mut out);
        assert_eq!(out.to_vec(), hex("3925841d02dc09fbdc118597196a0b32"));

        // Appendix A.1: the last round key of the expansion.
        assert_eq!(
            &ctx.ek[40..44],
            &[0xd014f9a8, 0xc9ee2589, 0xe13f0cc8, 0xb6630ca6]
        );
    }

    #[test]
    fn encrypt_only_context() {
        let k = key();
        let mut ctx = RijndaelCtx::default();
        assert_eq!(rijndael_set_key_enc_only(&mut ctx, &k[..16], 128), Ok(()));
        assert_eq!((ctx.Nr, ctx.enc_only), (10, 1));
        let pt: [u8; 16] = hexn(PT);
        let mut out = [0u8; 16];
        rijndael_encrypt(&ctx, &pt, &mut out);
        assert_eq!(out.to_vec(), hex("69c4e0d86a7b0430d8cdb78070b4c55a"));
    }

    #[test]
    fn bad_key_sizes_are_rejected() {
        let mut ctx = RijndaelCtx::default();
        for bits in [0, 64, 127, 129, 160, 224, 512] {
            assert_eq!(
                rijndael_set_key(&mut ctx, &[0; 64], bits),
                Err(Errno::EINVAL)
            );
            assert_eq!(
                rijndael_set_key_enc_only(&mut ctx, &[0; 64], bits),
                Err(Errno::EINVAL)
            );
        }
    }

    #[test]
    fn the_decrypt_schedule_is_the_reversed_inverse_mixed_encrypt_schedule() {
        let k = key();
        let mut ek = [0u32; 60];
        let mut dk = [0u32; 60];
        assert_eq!(rijndaelKeySetupEnc(&mut ek, &k, 256), Ok(14));
        assert_eq!(rijndaelKeySetupDec(&mut dk, &k, 256), Ok(14));
        // The first and last round keys swap places unchanged.
        assert_eq!(dk[..4], ek[56..60]);
        assert_eq!(dk[56..60], ek[..4]);
    }

    #[test]
    fn generated_tables_spot_checks() {
        assert_eq!(
            (SBOX[0x00], SBOX[0x01], SBOX[0x53], SBOX[0xff]),
            (0x63, 0x7c, 0xed, 0x16)
        );
        for x in 0..256 {
            assert_eq!(TD4[SBOX[x] as usize] as usize, x);
        }
        assert_eq!((TE0[0], TE0[1]), (0xc66363a5, 0xf87c7c84));
        assert_eq!(TD0[0], 0x51f4a750);
    }

    #[test]
    #[ignore = "reads the C tables from $OPENBSD_SRC (just test-ref)"]
    fn tables_match_the_c_file() {
        let f = "sys/crypto/rijndael.c";
        let check32 = |name: &str, table: &[u32; 256]| {
            let c = c_table(f, name);
            assert_eq!(c.len(), 256, "{name}");
            for (i, (a, b)) in c.iter().zip(table).enumerate() {
                assert_eq!(*a, u64::from(*b), "{name}[{i}]");
            }
        };
        check32("Te0", &TE0);
        check32("Te1", &TE1);
        check32("Te2", &TE2);
        check32("Te3", &TE3);
        check32("Td0", &TD0);
        check32("Td1", &TD1);
        check32("Td2", &TD2);
        check32("Td3", &TD3);

        let c = c_table(f, "Td4");
        assert_eq!(c.len(), 256);
        for (i, (a, b)) in c.iter().zip(TD4.iter()).enumerate() {
            assert_eq!(*a, u64::from(*b), "Td4[{i}]");
        }
        let c = c_table(f, "rcon");
        assert_eq!(c.len(), RCON.len());
        for (a, b) in c.iter().zip(RCON) {
            assert_eq!(*a, u64::from(b));
        }
    }
}
/* </TESTS> */
