/*	$OpenBSD: siop.out,v 1.9 2007/04/13 18:16:17 krw Exp $	*/
/* <LICENSES> */
/*
 * Copyright (c) 2026 Emilio Navarrete Lineros <enavarre@outlook.com>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

/*
 *	DO NOT EDIT - this file is automatically generated.
 *	created from siop.ss on Fri Apr 13 20:12:23 2007
 */
/*
;	$OpenBSD: siop.ss,v 1.10 2010/07/23 07:47:13 jsg Exp $
;	$NetBSD: siop.ss,v 1.20 2005/11/18 23:10:32 bouyer Exp $

;
;  Copyright (c) 2000 Manuel Bouyer.
;
;  Redistribution and use in source and binary forms, with or without
;  modification, are permitted provided that the following conditions
;  are met:
;  1. Redistributions of source code must retain the above copyright
;     notice, this list of conditions and the following disclaimer.
;  2. Redistributions in binary form must reproduce the above copyright
;     notice, this list of conditions and the following disclaimer in the
;     documentation and/or other materials provided with the distribution.
;
;  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
;  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
;  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
;  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
;  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
;  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
;  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
;  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
;  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
;  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
/* </LICENSES> */

/* <CODE> */
//! The SCRIPTS microcode of siop(4): the program the 53c8xx's SCRIPTS processor runs (the
//! scheduler, the select and reselect switches, the message and data phases), the
//! per-command and per-target fragments the driver copies and patches, and the offsets and
//! interrupt codes the driver shares with it.
//!
//! Upstream: sys/dev/microcode/siop/siop.out @ 3ce1f3f79392
//!
//! `siop.out` is generated: OpenBSD's `sys/dev/microcode/siop/Makefile` runs the SCRIPTS
//! assembler `ncr53cxxx` (`./ncr53cxxx siop.ss -p siop.out`) over the source `siop.ss`, and
//! `siop.c` includes the result. This file is that output transcribed by a script, table by
//! table and define by define, in the file's order, with every value unchanged; the
//! reference test (`just test-ref`) compares each table with `siop.out`. The licence above
//! is `siop.out`'s generated notice followed by `siop.ss`'s, the source it was made from.
//!
//! The tables are words in the CPU's byte order; the driver swaps them with `siop_htoc32`
//! when it copies them into host memory, or writes them with `bus_space_write_4` into the
//! chip's RAM.
//!
//! ## Deviations
//! - The C's names are kept as they are (`siop_script`, `A_int_done`, `Ent_reselect`,
//!   `E_abs_msgin_Used`), lower and mixed case included, so that siop.rs reads like siop.c.
//! - The `const u_int32_t` tables and the (never written) `u_int32_t E_*_Used[]` tables are
//!   `static`s of `u32`; every `#define` is a `u32` constant. Tables and defines stay
//!   interleaved in the generated file's order, and the rows keep its layout
//!   (`#[rustfmt::skip]`).

#![allow(non_upper_case_globals)] // the generated C names

/// `siop_script[]`.
#[rustfmt::skip] // the generated rows, as siop.out lays them out
pub static siop_script: [u32; 360] = [
    0x78340000, 0x00000000, /* 000 -   0 */
    0x78350000, 0x00000000, /* 008 -   8 */
    0x72370000, 0x00000000, /* 010 -  16 */
    0x80840020, 0x00000318, /* 018 -  24 */
    0x868b0000, 0x00000380, /* 020 -  32 */
    0x878b0000, 0x000002f8, /* 028 -  40 */
    0x808b0000, 0x00000408, /* 030 -  48 */
    0x818b0000, 0x000003a0, /* 038 -  56 */
    0x828b0000, 0x00000378, /* 040 -  64 */
    0x838b0000, 0x00000380, /* 048 -  72 */
    0x98080000, 0x0000ffff, /* 050 -  80 */
    0x741a4000, 0x00000000, /* 058 -  88 */
    0x980c0000, 0x0000ff83, /* 060 -  96 */
    0x80000000, 0x00000000, /* 068 - 104 */
    0x7810ff00, 0x00000000, /* 070 - 112 */
    0x7811ff00, 0x00000000, /* 078 - 120 */
    0x7812ff00, 0x00000000, /* 080 - 128 */
    0x7813ff00, 0x00000000, /* 088 - 136 */
    0x78340000, 0x00000000, /* 090 - 144 */
    0x78350000, 0x00000000, /* 098 - 152 */
    0x80000000, 0x00000000, /* 0a0 - 160 */
    0x80000000, 0x00000000, /* 0a8 - 168 */
    0x80000000, 0x00000000, /* 0b0 - 176 */
    0x80000000, 0x00000000, /* 0b8 - 184 */
    0x80000000, 0x00000000, /* 0c0 - 192 */
    0x80000000, 0x00000000, /* 0c8 - 200 */
    0x80000000, 0x00000000, /* 0d0 - 208 */
    0x80000000, 0x00000000, /* 0d8 - 216 */
    0x80000000, 0x00000000, /* 0e0 - 224 */
    0x80000000, 0x00000000, /* 0e8 - 232 */
    0x80000000, 0x00000000, /* 0f0 - 240 */
    0x80000000, 0x00000000, /* 0f8 - 248 */
    0x80000000, 0x00000000, /* 100 - 256 */
    0x80000000, 0x00000000, /* 108 - 264 */
    0x80000000, 0x00000000, /* 110 - 272 */
    0x80000000, 0x00000000, /* 118 - 280 */
    0x80000000, 0x00000000, /* 120 - 288 */
    0x80000000, 0x00000000, /* 128 - 296 */
    0x80000000, 0x00000000, /* 130 - 304 */
    0x80000000, 0x00000000, /* 138 - 312 */
    0x80000000, 0x00000000, /* 140 - 320 */
    0x80000000, 0x00000000, /* 148 - 328 */
    0x80000000, 0x00000000, /* 150 - 336 */
    0x80000000, 0x00000000, /* 158 - 344 */
    0x80000000, 0x00000000, /* 160 - 352 */
    0x80000000, 0x00000000, /* 168 - 360 */
    0x80000000, 0x00000000, /* 170 - 368 */
    0x80000000, 0x00000000, /* 178 - 376 */
    0x80000000, 0x00000000, /* 180 - 384 */
    0x80000000, 0x00000000, /* 188 - 392 */
    0x80000000, 0x00000000, /* 190 - 400 */
    0x80000000, 0x00000000, /* 198 - 408 */
    0x80000000, 0x00000000, /* 1a0 - 416 */
    0x80000000, 0x00000000, /* 1a8 - 424 */
    0x80000000, 0x00000000, /* 1b0 - 432 */
    0x80000000, 0x00000000, /* 1b8 - 440 */
    0x80000000, 0x00000000, /* 1c0 - 448 */
    0x80000000, 0x00000000, /* 1c8 - 456 */
    0x80000000, 0x00000000, /* 1d0 - 464 */
    0x80000000, 0x00000000, /* 1d8 - 472 */
    0x7810ff00, 0x00000000, /* 1e0 - 480 */
    0x7811ff00, 0x00000000, /* 1e8 - 488 */
    0x7812ff00, 0x00000000, /* 1f0 - 496 */
    0x7813ff00, 0x00000000, /* 1f8 - 504 */
    0x78360000, 0x00000000, /* 200 - 512 */
    0x78372000, 0x00000000, /* 208 - 520 */
    0x80000000, 0x00000000, /* 210 - 528 */
    0x54000000, 0xfffffe38, /* 218 - 536 */
    0x80000000, 0x00000000, /* 220 - 544 */
    0x740a8f00, 0x00000000, /* 228 - 552 */
    0x6a340000, 0x00000000, /* 230 - 560 */
    0x800c00ff, 0x00000000, /* 238 - 568 */
    0x800c00ff, 0x00000000, /* 240 - 576 */
    0x800c00ff, 0x00000000, /* 248 - 584 */
    0x800c00ff, 0x00000000, /* 250 - 592 */
    0x800c00ff, 0x00000000, /* 258 - 600 */
    0x800c00ff, 0x00000000, /* 260 - 608 */
    0x800c00ff, 0x00000000, /* 268 - 616 */
    0x800c00ff, 0x00000000, /* 270 - 624 */
    0x800c00ff, 0x00000000, /* 278 - 632 */
    0x800c00ff, 0x00000000, /* 280 - 640 */
    0x800c00ff, 0x00000000, /* 288 - 648 */
    0x800c00ff, 0x00000000, /* 290 - 656 */
    0x800c00ff, 0x00000000, /* 298 - 664 */
    0x800c00ff, 0x00000000, /* 2a0 - 672 */
    0x800c00ff, 0x00000000, /* 2a8 - 680 */
    0x98080000, 0x0000ff80, /* 2b0 - 688 */
    0x0f000001, 0x00000000, /* 2b8 - 696 */
    0x6c350700, 0x00000000, /* 2c0 - 704 */
    0x60000040, 0x00000000, /* 2c8 - 712 */
    0x97030000, 0x00000000, /* 2d0 - 720 */
    0x0f000001, 0x00000000, /* 2d8 - 728 */
    0x60000040, 0x00000000, /* 2e0 - 736 */
    0x6a370000, 0x00000000, /* 2e8 - 744 */
    0x90040020, 0x00000000, /* 2f0 - 752 */
    0x0f000001, 0x00000000, /* 2f8 - 760 */
    0x60000040, 0x00000000, /* 300 - 768 */
    0x6a360000, 0x00000000, /* 308 - 776 */
    0x90080000, 0x00000000, /* 310 - 784 */
    0x60000040, 0x00000000, /* 318 - 792 */
    0x7a340100, 0x00000000, /* 320 - 800 */
    0x60000008, 0x00000000, /* 328 - 808 */
    0x1f00003c, 0x0000003c, /* 330 - 816 */
    0x808c0000, 0x00000218, /* 338 - 824 */
    0x808c0002, 0xffffffd0, /* 340 - 832 */
    0x808c0001, 0x00000218, /* 348 - 840 */
    0x98040004, 0x0000ff01, /* 350 - 848 */
    0x88880000, 0x000001d0, /* 358 - 856 */
    0x74340100, 0x00000000, /* 360 - 864 */
    0x98040000, 0x0000ff04, /* 368 - 872 */
    0x72350000, 0x00000000, /* 370 - 880 */
    0x808c0000, 0xfffffcf0, /* 378 - 888 */
    0x98080000, 0x0000ff05, /* 380 - 896 */
    0x60000040, 0x00000000, /* 388 - 904 */
    0x80880000, 0xfffffc88, /* 390 - 912 */
    0x58000008, 0x00000000, /* 398 - 920 */
    0x60000040, 0x00000000, /* 3a0 - 928 */
    0x1e000054, 0x00000054, /* 3a8 - 936 */
    0x60000008, 0x00000000, /* 3b0 - 944 */
    0x80880000, 0xfffffc60, /* 3b8 - 952 */
    0x1a00005c, 0x0000005c, /* 3c0 - 960 */
    0x80880000, 0xfffffc50, /* 3c8 - 968 */
    0x1b000064, 0x00000064, /* 3d0 - 976 */
    0x80880000, 0xfffffc40, /* 3d8 - 984 */
    0x88880000, 0x000000b8, /* 3e0 - 992 */
    0x7a340200, 0x00000000, /* 3e8 - 1000 */
    0x1900006c, 0x0000006c, /* 3f0 - 1008 */
    0x7e350100, 0x00000000, /* 3f8 - 1016 */
    0x7e100800, 0x00000000, /* 400 - 1024 */
    0x7f110000, 0x00000000, /* 408 - 1032 */
    0x7f120000, 0x00000000, /* 410 - 1040 */
    0x7f130000, 0x00000000, /* 418 - 1048 */
    0x818b0000, 0xffffffc8, /* 420 - 1056 */
    0x88880000, 0x000000b8, /* 428 - 1064 */
    0x7c34fd00, 0x00000000, /* 430 - 1072 */
    0x80880000, 0xfffffbe0, /* 438 - 1080 */
    0x88880000, 0x00000058, /* 440 - 1088 */
    0x7a340200, 0x00000000, /* 448 - 1096 */
    0x1800006c, 0x0000006c, /* 450 - 1104 */
    0x7e350100, 0x00000000, /* 458 - 1112 */
    0x7e100800, 0x00000000, /* 460 - 1120 */
    0x7f110000, 0x00000000, /* 468 - 1128 */
    0x7f120000, 0x00000000, /* 470 - 1136 */
    0x7f130000, 0x00000000, /* 478 - 1144 */
    0x808b0000, 0xffffffc8, /* 480 - 1152 */
    0x88880000, 0x00000058, /* 488 - 1160 */
    0x7c34fd00, 0x00000000, /* 490 - 1168 */
    0x80880000, 0xfffffb80, /* 498 - 1176 */
    0x72100000, 0x00000000, /* 4a0 - 1184 */
    0x6a5c0000, 0x00000000, /* 4a8 - 1192 */
    0x72110000, 0x00000000, /* 4b0 - 1200 */
    0x6a5d0000, 0x00000000, /* 4b8 - 1208 */
    0x72120000, 0x00000000, /* 4c0 - 1216 */
    0x6a5e0000, 0x00000000, /* 4c8 - 1224 */
    0x72130000, 0x00000000, /* 4d0 - 1232 */
    0x6a5f0000, 0x00000000, /* 4d8 - 1240 */
    0x90080000, 0x00000000, /* 4e0 - 1248 */
    0x725c0000, 0x00000000, /* 4e8 - 1256 */
    0x6a100000, 0x00000000, /* 4f0 - 1264 */
    0x725d0000, 0x00000000, /* 4f8 - 1272 */
    0x6a110000, 0x00000000, /* 500 - 1280 */
    0x725e0000, 0x00000000, /* 508 - 1288 */
    0x6a120000, 0x00000000, /* 510 - 1296 */
    0x725f0000, 0x00000000, /* 518 - 1304 */
    0x6a130000, 0x00000000, /* 520 - 1312 */
    0x90080000, 0x00000000, /* 528 - 1320 */
    0x7c027f00, 0x00000000, /* 530 - 1328 */
    0x60000008, 0x00000000, /* 538 - 1336 */
    0x60000040, 0x00000000, /* 540 - 1344 */
    0x48000000, 0x00000000, /* 548 - 1352 */
    0x90080000, 0x00000000, /* 550 - 1360 */
    0x88880000, 0xffffffd0, /* 558 - 1368 */
    0x98080000, 0x0000ff00, /* 560 - 1376 */
    0x60000040, 0x00000000, /* 568 - 1384 */
    0x1f000044, 0x00000044, /* 570 - 1392 */
    0x98080000, 0x0000ff02, /* 578 - 1400 */
    0x60000040, 0x00000000, /* 580 - 1408 */
    0x1f00004c, 0x0000004c, /* 588 - 1416 */
    0x98080000, 0x0000ff03, /* 590 - 1424 */
    0x80000000, 0x00000000, /* 598 - 1432 */
];

/// `lun_switch[]`.
#[rustfmt::skip] // the generated rows, as siop.out lays them out
pub static lun_switch: [u32; 12] = [
    0x7803ff00, 0x00000000, /* 000 -   0 */
    0x7805ff00, 0x00000000, /* 008 -   8 */
    0x80080000, 0x00000000, /* 010 -  16 */
    0x88880000, 0xffffffe0, /* 018 -  24 */
    0x72350000, 0x00000000, /* 020 -  32 */
    0x98080000, 0x0000ff81, /* 028 -  40 */
];

/// `tag_switch[]`.
#[rustfmt::skip] // the generated rows, as siop.out lays them out
pub static tag_switch: [u32; 36] = [
    0x72360000, 0x00000000, /* 000 -   0 */
    0x800c0000, 0x00000000, /* 008 -   8 */
    0x800c0001, 0x00000000, /* 010 -  16 */
    0x800c0002, 0x00000000, /* 018 -  24 */
    0x800c0003, 0x00000000, /* 020 -  32 */
    0x800c0004, 0x00000000, /* 028 -  40 */
    0x800c0005, 0x00000000, /* 030 -  48 */
    0x800c0006, 0x00000000, /* 038 -  56 */
    0x800c0007, 0x00000000, /* 040 -  64 */
    0x800c0008, 0x00000000, /* 048 -  72 */
    0x800c0009, 0x00000000, /* 050 -  80 */
    0x800c000a, 0x00000000, /* 058 -  88 */
    0x800c000b, 0x00000000, /* 060 -  96 */
    0x800c000c, 0x00000000, /* 068 - 104 */
    0x800c000d, 0x00000000, /* 070 - 112 */
    0x800c000e, 0x00000000, /* 078 - 120 */
    0x800c000f, 0x00000000, /* 080 - 128 */
    0x98080000, 0x0000ff82, /* 088 - 136 */
];

/// `load_dsa[]`.
#[rustfmt::skip] // the generated rows, as siop.out lays them out
pub static load_dsa: [u32; 25] = [
    0x7810f000, 0x00000000, /* 000 -   0 */
    0x7811f100, 0x00000000, /* 008 -   8 */
    0x7812f200, 0x00000000, /* 010 -  16 */
    0x7813f300, 0x00000000, /* 018 -  24 */
    0x90080000, 0x00000000, /* 020 -  32 */
    0x88880000, 0xffffffd0, /* 028 -  40 */
    0x80080000, 0x00000000, /* 030 -  48 */
    0x88880000, 0xffffffc0, /* 038 -  56 */
    0x43000028, 0x00000000, /* 040 -  64 */
    0xc0000004, 0x00000000, 0x00000000, /* 048 -  72 */
    0x80080000, 0x00000000, /* 054 -  84 */
    0x80000000, 0x00000000, /* 05c -  92 */
];

/// `siop_led_on[]`.
#[rustfmt::skip] // the generated rows, as siop.out lays them out
pub static siop_led_on: [u32; 2] = [
    0x7c07fe00, 0x00000000, /* 000 -   0 */
];

/// `siop_led_off[]`.
#[rustfmt::skip] // the generated rows, as siop.out lays them out
pub static siop_led_off: [u32; 2] = [
    0x7a070100, 0x00000000, /* 000 -   0 */
];

/// `A_t_id`.
pub const A_t_id: u32 = 0x00000028;
/// `A_t_msg_in`.
pub const A_t_msg_in: u32 = 0x0000003c;
/// `A_t_ext_msg_in`.
pub const A_t_ext_msg_in: u32 = 0x00000044;
/// `A_t_ext_msg_data`.
pub const A_t_ext_msg_data: u32 = 0x0000004c;
/// `A_t_msg_out`.
pub const A_t_msg_out: u32 = 0x00000054;
/// `A_t_cmd`.
pub const A_t_cmd: u32 = 0x0000005c;
/// `A_t_status`.
pub const A_t_status: u32 = 0x00000064;
/// `A_t_data`.
pub const A_t_data: u32 = 0x0000006c;
/// `A_int_done`.
pub const A_int_done: u32 = 0x0000ff00;
/// `A_int_msgin`.
pub const A_int_msgin: u32 = 0x0000ff01;
/// `A_int_extmsgin`.
pub const A_int_extmsgin: u32 = 0x0000ff02;
/// `A_int_extmsgdata`.
pub const A_int_extmsgdata: u32 = 0x0000ff03;
/// `A_int_disc`.
pub const A_int_disc: u32 = 0x0000ff04;
/// `A_int_saveoffset`.
pub const A_int_saveoffset: u32 = 0x0000ff05;
/// `A_int_reseltarg`.
pub const A_int_reseltarg: u32 = 0x0000ff80;
/// `A_int_resellun`.
pub const A_int_resellun: u32 = 0x0000ff81;
/// `A_int_reseltag`.
pub const A_int_reseltag: u32 = 0x0000ff82;
/// `A_int_resfail`.
pub const A_int_resfail: u32 = 0x0000ff83;
/// `A_int_err`.
pub const A_int_err: u32 = 0x0000ffff;
/// `A_flag_sdp`.
pub const A_flag_sdp: u32 = 0x00000001;
/// `A_flag_data`.
pub const A_flag_data: u32 = 0x00000002;
/// `A_flag_data_mask`.
pub const A_flag_data_mask: u32 = 0x000000fd;
/// `Ent_waitphase`.
pub const Ent_waitphase: u32 = 0x00000020;
/// `Ent_send_msgout`.
pub const Ent_send_msgout: u32 = 0x00000398;
/// `Ent_msgout`.
pub const Ent_msgout: u32 = 0x000003a8;
/// `Ent_msgin`.
pub const Ent_msgin: u32 = 0x00000328;
/// `Ent_handle_msgin`.
pub const Ent_handle_msgin: u32 = 0x00000338;
/// `Ent_msgin_ack`.
pub const Ent_msgin_ack: u32 = 0x00000388;
/// `Ent_dataout`.
pub const Ent_dataout: u32 = 0x00000440;
/// `Ent_datain`.
pub const Ent_datain: u32 = 0x000003e0;
/// `Ent_cmdout`.
pub const Ent_cmdout: u32 = 0x000003c0;
/// `Ent_status`.
pub const Ent_status: u32 = 0x000003d0;
/// `Ent_disconnect`.
pub const Ent_disconnect: u32 = 0x00000530;
/// `Ent_reselect`.
pub const Ent_reselect: u32 = 0x000001e0;
/// `Ent_reselected`.
pub const Ent_reselected: u32 = 0x00000000;
/// `Ent_selected`.
pub const Ent_selected: u32 = 0x00000388;
/// `Ent_script_sched`.
pub const Ent_script_sched: u32 = 0x00000070;
/// `Ent_script_sched_slot0`.
pub const Ent_script_sched_slot0: u32 = 0x000000a0;
/// `Ent_get_extmsgdata`.
pub const Ent_get_extmsgdata: u32 = 0x00000580;
/// `Ent_resel_targ0`.
pub const Ent_resel_targ0: u32 = 0x00000238;
/// `Ent_msgin_space`.
pub const Ent_msgin_space: u32 = 0x00000598;
/// `Ent_lunsw_return`.
pub const Ent_lunsw_return: u32 = 0x000002b8;
/// `Ent_led_on1`.
pub const Ent_led_on1: u32 = 0x00000068;
/// `Ent_led_on2`.
pub const Ent_led_on2: u32 = 0x00000220;
/// `Ent_led_off`.
pub const Ent_led_off: u32 = 0x00000210;
/// `E_abs_script_sched_slot0`.
pub const E_abs_script_sched_slot0: u32 = 0x00000000;
/// `E_abs_script_sched_slot0_Used[]`.
#[rustfmt::skip] // the generated rows, as siop.out lays them out
pub static E_abs_script_sched_slot0_Used: [u32; 40] = [
    0x00000029,
    0x0000002b,
    0x0000002d,
    0x0000002f,
    0x00000031,
    0x00000033,
    0x00000035,
    0x00000037,
    0x00000039,
    0x0000003b,
    0x0000003d,
    0x0000003f,
    0x00000041,
    0x00000043,
    0x00000045,
    0x00000047,
    0x00000049,
    0x0000004b,
    0x0000004d,
    0x0000004f,
    0x00000051,
    0x00000053,
    0x00000055,
    0x00000057,
    0x00000059,
    0x0000005b,
    0x0000005d,
    0x0000005f,
    0x00000061,
    0x00000063,
    0x00000065,
    0x00000067,
    0x00000069,
    0x0000006b,
    0x0000006d,
    0x0000006f,
    0x00000071,
    0x00000073,
    0x00000075,
    0x00000077,
];

/// `E_abs_targ0`.
pub const E_abs_targ0: u32 = 0x00000000;
/// `E_abs_targ0_Used[]`.
#[rustfmt::skip] // the generated rows, as siop.out lays them out
pub static E_abs_targ0_Used: [u32; 15] = [
    0x0000008f,
    0x00000091,
    0x00000093,
    0x00000095,
    0x00000097,
    0x00000099,
    0x0000009b,
    0x0000009d,
    0x0000009f,
    0x000000a1,
    0x000000a3,
    0x000000a5,
    0x000000a7,
    0x000000a9,
    0x000000ab,
];

/// `E_abs_msgin`.
pub const E_abs_msgin: u32 = 0x00000000;
/// `E_abs_msgin_Used[]`.
#[rustfmt::skip] // the generated rows, as siop.out lays them out
pub static E_abs_msgin_Used: [u32; 3] = [
    0x000000af,
    0x000000b7,
    0x000000bf,
];

/// `Ent_lun_switch_entry`.
pub const Ent_lun_switch_entry: u32 = 0x00000018;
/// `Ent_resel_lun0`.
pub const Ent_resel_lun0: u32 = 0x00000028;
/// `Ent_restore_scntl3`.
pub const Ent_restore_scntl3: u32 = 0x00000000;
/// `E_abs_lunsw_return`.
pub const E_abs_lunsw_return: u32 = 0x00000000;
/// `E_abs_lunsw_return_Used[]`.
#[rustfmt::skip] // the generated rows, as siop.out lays them out
pub static E_abs_lunsw_return_Used: [u32; 1] = [
    0x00000005,
];

/// `Ent_tag_switch_entry`.
pub const Ent_tag_switch_entry: u32 = 0x00000000;
/// `Ent_resel_tag0`.
pub const Ent_resel_tag0: u32 = 0x00000008;
/// `E_abs_tag0`.
pub const E_abs_tag0: u32 = 0x00000000;
/// `E_abs_tag0_Used[]`.
#[rustfmt::skip] // the generated rows, as siop.out lays them out
pub static E_abs_tag0_Used: [u32; 16] = [
    0x00000003,
    0x00000005,
    0x00000007,
    0x00000009,
    0x0000000b,
    0x0000000d,
    0x0000000f,
    0x00000011,
    0x00000013,
    0x00000015,
    0x00000017,
    0x00000019,
    0x0000001b,
    0x0000001d,
    0x0000001f,
    0x00000021,
];

/// `Ent_rdsa0`.
pub const Ent_rdsa0: u32 = 0x00000000;
/// `Ent_rdsa1`.
pub const Ent_rdsa1: u32 = 0x00000008;
/// `Ent_rdsa2`.
pub const Ent_rdsa2: u32 = 0x00000010;
/// `Ent_rdsa3`.
pub const Ent_rdsa3: u32 = 0x00000018;
/// `Ent_ldsa_reload_dsa`.
pub const Ent_ldsa_reload_dsa: u32 = 0x00000028;
/// `Ent_ldsa_select`.
pub const Ent_ldsa_select: u32 = 0x00000038;
/// `Ent_ldsa_data`.
pub const Ent_ldsa_data: u32 = 0x0000005c;
/// `E_ldsa_abs_reselected`.
pub const E_ldsa_abs_reselected: u32 = 0x00000000;
/// `E_ldsa_abs_reselected_Used[]`.
#[rustfmt::skip] // the generated rows, as siop.out lays them out
pub static E_ldsa_abs_reselected_Used: [u32; 1] = [
    0x0000000d,
];

/// `E_ldsa_abs_reselect`.
pub const E_ldsa_abs_reselect: u32 = 0x00000000;
/// `E_ldsa_abs_reselect_Used[]`.
#[rustfmt::skip] // the generated rows, as siop.out lays them out
pub static E_ldsa_abs_reselect_Used: [u32; 1] = [
    0x00000011,
];

/// `E_ldsa_abs_selected`.
pub const E_ldsa_abs_selected: u32 = 0x00000000;
/// `E_ldsa_abs_selected_Used[]`.
#[rustfmt::skip] // the generated rows, as siop.out lays them out
pub static E_ldsa_abs_selected_Used: [u32; 1] = [
    0x00000016,
];

/// `E_ldsa_abs_data`.
pub const E_ldsa_abs_data: u32 = 0x00000000;
/// `E_ldsa_abs_data_Used[]`.
#[rustfmt::skip] // the generated rows, as siop.out lays them out
pub static E_ldsa_abs_data_Used: [u32; 1] = [
    0x00000013,
];

/// `E_ldsa_abs_slot`.
pub const E_ldsa_abs_slot: u32 = 0x00000000;
/// `E_ldsa_abs_slot_Used[]`.
#[rustfmt::skip] // the generated rows, as siop.out lays them out
pub static E_ldsa_abs_slot_Used: [u32; 1] = [
    0x00000014,
];
/* </CODE> */

/* <TESTS> */
#[cfg(test)]
mod tests {
    // Host tests for the siop microcode: the entry points and patch sites stay inside their
    // tables, and a reference test compares every table and define with `siop.out`.

    use std::vec::Vec;

    use super::*;
    use crate::crypto::testutil::c_table;
    use crate::reftest;

    /// The microcode file inside the reference tree.
    const SIOP_OUT: &str = "sys/dev/microcode/siop/siop.out";

    #[test]
    fn entry_points_and_patch_sites_are_inside_their_tables() {
        let script = siop_script.len() as u32 * 4;
        for ent in [
            Ent_waitphase,
            Ent_send_msgout,
            Ent_msgin,
            Ent_msgin_ack,
            Ent_reselect,
            Ent_script_sched,
            Ent_script_sched_slot0,
            Ent_get_extmsgdata,
            Ent_resel_targ0,
            Ent_msgin_space,
            Ent_lunsw_return,
            Ent_led_on1,
            Ent_led_on2,
            Ent_led_off,
        ] {
            assert!(ent < script && ent % 4 == 0, "{ent:#x}");
        }
        // 40 scheduler slots of two words each, all free (`JUMP foo, IF FALSE`).
        for slot in 0..40 {
            assert_eq!(
                siop_script[(Ent_script_sched_slot0 / 4) as usize + slot * 2],
                0x8000_0000
            );
        }
        assert!(
            E_abs_msgin_Used
                .iter()
                .all(|&w| w < siop_script.len() as u32)
        );
        assert!(Ent_lun_switch_entry / 4 < lun_switch.len() as u32);
        assert!((E_abs_lunsw_return_Used[0] as usize) < lun_switch.len());
        assert!(((Ent_resel_tag0 / 4) as usize + 15 * 2) < tag_switch.len());
        for used in [
            E_ldsa_abs_reselected_Used[0],
            E_ldsa_abs_reselect_Used[0],
            E_ldsa_abs_selected_Used[0],
            E_ldsa_abs_data_Used[0],
            E_ldsa_abs_slot_Used[0],
        ] {
            assert!((used as usize) < load_dsa.len());
        }
        // The register loads siop_morecbd patches are `MOVE data8 TO DSA0..3`.
        for (ent, reg) in [
            (Ent_rdsa0, 0x10),
            (Ent_rdsa1, 0x11),
            (Ent_rdsa2, 0x12),
            (Ent_rdsa3, 0x13),
        ] {
            assert_eq!(load_dsa[(ent / 4) as usize] >> 16, 0x7800 | reg);
        }
    }

    #[test]
    #[ignore = "reads the C reference (just test-ref)"]
    fn tables_and_defines_match_siop_out() {
        let tables: &[(&str, &[u32])] = &[
            ("siop_script", &siop_script),
            ("lun_switch", &lun_switch),
            ("tag_switch", &tag_switch),
            ("load_dsa", &load_dsa),
            ("siop_led_on", &siop_led_on),
            ("siop_led_off", &siop_led_off),
            (
                "E_abs_script_sched_slot0_Used",
                &E_abs_script_sched_slot0_Used,
            ),
            ("E_abs_targ0_Used", &E_abs_targ0_Used),
            ("E_abs_msgin_Used", &E_abs_msgin_Used),
            ("E_abs_lunsw_return_Used", &E_abs_lunsw_return_Used),
            ("E_abs_tag0_Used", &E_abs_tag0_Used),
            ("E_ldsa_abs_reselected_Used", &E_ldsa_abs_reselected_Used),
            ("E_ldsa_abs_reselect_Used", &E_ldsa_abs_reselect_Used),
            ("E_ldsa_abs_selected_Used", &E_ldsa_abs_selected_Used),
            ("E_ldsa_abs_data_Used", &E_ldsa_abs_data_Used),
            ("E_ldsa_abs_slot_Used", &E_ldsa_abs_slot_Used),
        ];
        for &(name, ours) in tables {
            let theirs: Vec<u64> = c_table(SIOP_OUT, name);
            let ours: Vec<u64> = ours.iter().map(|&w| u64::from(w)).collect();
            assert_eq!(ours, theirs, "{name}");
        }

        let defs = reftest::defines(SIOP_OUT);
        let ours: &[(&str, u32)] = &[
            ("A_t_id", A_t_id),
            ("A_t_msg_in", A_t_msg_in),
            ("A_t_ext_msg_in", A_t_ext_msg_in),
            ("A_t_ext_msg_data", A_t_ext_msg_data),
            ("A_t_msg_out", A_t_msg_out),
            ("A_t_cmd", A_t_cmd),
            ("A_t_status", A_t_status),
            ("A_t_data", A_t_data),
            ("A_int_done", A_int_done),
            ("A_int_msgin", A_int_msgin),
            ("A_int_extmsgin", A_int_extmsgin),
            ("A_int_extmsgdata", A_int_extmsgdata),
            ("A_int_disc", A_int_disc),
            ("A_int_saveoffset", A_int_saveoffset),
            ("A_int_reseltarg", A_int_reseltarg),
            ("A_int_resellun", A_int_resellun),
            ("A_int_reseltag", A_int_reseltag),
            ("A_int_resfail", A_int_resfail),
            ("A_int_err", A_int_err),
            ("A_flag_sdp", A_flag_sdp),
            ("A_flag_data", A_flag_data),
            ("A_flag_data_mask", A_flag_data_mask),
            ("Ent_waitphase", Ent_waitphase),
            ("Ent_send_msgout", Ent_send_msgout),
            ("Ent_msgout", Ent_msgout),
            ("Ent_msgin", Ent_msgin),
            ("Ent_handle_msgin", Ent_handle_msgin),
            ("Ent_msgin_ack", Ent_msgin_ack),
            ("Ent_dataout", Ent_dataout),
            ("Ent_datain", Ent_datain),
            ("Ent_cmdout", Ent_cmdout),
            ("Ent_status", Ent_status),
            ("Ent_disconnect", Ent_disconnect),
            ("Ent_reselect", Ent_reselect),
            ("Ent_reselected", Ent_reselected),
            ("Ent_selected", Ent_selected),
            ("Ent_script_sched", Ent_script_sched),
            ("Ent_script_sched_slot0", Ent_script_sched_slot0),
            ("Ent_get_extmsgdata", Ent_get_extmsgdata),
            ("Ent_resel_targ0", Ent_resel_targ0),
            ("Ent_msgin_space", Ent_msgin_space),
            ("Ent_lunsw_return", Ent_lunsw_return),
            ("Ent_led_on1", Ent_led_on1),
            ("Ent_led_on2", Ent_led_on2),
            ("Ent_led_off", Ent_led_off),
            ("E_abs_script_sched_slot0", E_abs_script_sched_slot0),
            ("E_abs_targ0", E_abs_targ0),
            ("E_abs_msgin", E_abs_msgin),
            ("Ent_lun_switch_entry", Ent_lun_switch_entry),
            ("Ent_resel_lun0", Ent_resel_lun0),
            ("Ent_restore_scntl3", Ent_restore_scntl3),
            ("E_abs_lunsw_return", E_abs_lunsw_return),
            ("Ent_tag_switch_entry", Ent_tag_switch_entry),
            ("Ent_resel_tag0", Ent_resel_tag0),
            ("E_abs_tag0", E_abs_tag0),
            ("Ent_rdsa0", Ent_rdsa0),
            ("Ent_rdsa1", Ent_rdsa1),
            ("Ent_rdsa2", Ent_rdsa2),
            ("Ent_rdsa3", Ent_rdsa3),
            ("Ent_ldsa_reload_dsa", Ent_ldsa_reload_dsa),
            ("Ent_ldsa_select", Ent_ldsa_select),
            ("Ent_ldsa_data", Ent_ldsa_data),
            ("E_ldsa_abs_reselected", E_ldsa_abs_reselected),
            ("E_ldsa_abs_reselect", E_ldsa_abs_reselect),
            ("E_ldsa_abs_selected", E_ldsa_abs_selected),
            ("E_ldsa_abs_data", E_ldsa_abs_data),
            ("E_ldsa_abs_slot", E_ldsa_abs_slot),
        ];
        // Every define of siop.out is listed above.
        assert_eq!(defs.len(), ours.len());
        for &(name, v) in ours {
            assert_eq!(reftest::int(&defs, name), Some(i64::from(v)), "{name}");
        }
    }
}
/* </TESTS> */
