/*	$OpenBSD: ukbdmap.c,v 1.51 2026/01/06 18:52:40 helg Exp $	*/
/* <LICENSES> */
/*
 * Copyright (c) 2026 Emilio Navarrete Lineros <enavarre@outlook.com>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

/*
 * THIS FILE IS AUTOMAGICALLY GENERATED.  DO NOT EDIT.
 *
 * generated by:
 *	OpenBSD: makemap.awk,v 1.18 2026/01/06 18:42:18 helg Exp 
 * generated from:
 */
/*	OpenBSD: wskbdmap_mfii.c,v 1.49 2025/11/09 16:21:56 matthieu Exp  */
/*	$NetBSD: wskbdmap_mfii.c,v 1.15 2000/05/19 16:40:04 drochner Exp $	*/

/*
 * PLEASE DO NOT FORGET TO REGEN
 *	sys/dev/usb/ukbdmap.c
 * AFTER ANY CHANGES TO THIS FILE!
 */

/*-
 * Copyright (c) 1997 The NetBSD Foundation, Inc.
 * All rights reserved.
 *
 * This code is derived from software contributed to The NetBSD Foundation
 * by Juergen Hannken-Illjes.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
/* </LICENSES> */

/* <CODE> */
//! The keyboard layouts of `ukbd(4)`, `dev/usb/ukbdmap.c`: for each layout `wskbd(4)` offers
//! a USB keyboard (`KB_US`, `KB_DE`, ... and their variants), the keysyms of the keys it
//! changes, by USB HID key code (usage page 7).
//!
//! Upstream: sys/dev/usb/ukbdmap.c @ 3ce1f3f79392
//!
//! The C file is generated (by `makemap.awk` from `dev/pckbc/wskbdmap_mfii.c`); so is this
//! one, from the C, keeping every line of the tables and their comments. A table is a list
//! of entries, each a key code (`KC(n)`, a keysym of group `KS_GROUP_Keycode`), an optional
//! command keysym (`KS_Cmd_*`) and up to four keysyms (normal, shifted, altgr, shift-altgr);
//! `ukbd_keydesctab` names each layout's table and the layout it is a delta over, which
//! `wskbdutil.rs`'s `wskbd_load_keymap` applies first.
//!
//! ## Deviations
//! - `WSKBD_NO_INTL_LAYOUTS` is not defined (GENERIC has every layout): the `#if` lines are
//!   kept as comments.
//! - The macro `KC(n)` is the `const fn` [`kc`], `KBD_MAP(name, base, map)` the `const fn`
//!   `kbd_map`; the tables are `&[KeysymT]` slices (`map_size` is their length) and
//!   `ukbd_keydesctab` has no `{0, 0, 0, 0}` terminator (`wsksymvar.rs`).
//! - The C's block comments are line comments.

use crate::dev::wscons::wsksymdef::*;
use crate::dev::wscons::wsksymvar::{KeysymT, WsconsKeydesc};

/// `KC(n)`: the keysym of key code `n` (`KS_KEYCODE(n)`).
const fn kc(n: u32) -> KeysymT {
    ks_keycode(n) as KeysymT
}

/// `KBD_MAP(name, base, map)`: layout `name`, a delta over `base`, with the keymap `map`.
const fn kbd_map(name: u32, base: u32, map: &'static [KeysymT]) -> WsconsKeydesc {
    WsconsKeydesc {
        name,
        base,
        map_size: map.len() as i32,
        map,
    }
}

/// `ukbd_keydesc_us`.
#[rustfmt::skip]
static UKBD_KEYDESC_US: &[KeysymT] = &[
    // pos      command            normal          shifted
    kc(4),      KS_a,
    kc(5),      KS_b,
    kc(6),      KS_c,
    kc(7),      KS_d,
    kc(8),      KS_e,
    kc(9),      KS_f,
    kc(10),     KS_g,
    kc(11),     KS_h,
    kc(12),     KS_i,
    kc(13),     KS_j,
    kc(14),     KS_k,
    kc(15),     KS_l,
    kc(16),     KS_m,
    kc(17),     KS_n,
    kc(18),     KS_o,
    kc(19),     KS_p,
    kc(20),     KS_q,
    kc(21),     KS_r,
    kc(22),     KS_s,
    kc(23),     KS_t,
    kc(24),     KS_u,
    kc(25),     KS_v,
    kc(26),     KS_w,
    kc(27),     KS_x,
    kc(28),     KS_y,
    kc(29),     KS_z,
    kc(30),     KS_1,           KS_exclam,
    kc(31),     KS_2,           KS_at,
    kc(32),     KS_3,           KS_numbersign,
    kc(33),     KS_4,           KS_dollar,
    kc(34),     KS_5,           KS_percent,
    kc(35),     KS_6,           KS_asciicircum,
    kc(36),     KS_7,           KS_ampersand,
    kc(37),     KS_8,           KS_asterisk,
    kc(38),     KS_9,           KS_parenleft,
    kc(39),     KS_0,           KS_parenright,
    kc(40),     KS_Return,
    kc(41),     KS_Cmd_Debugger,KS_Escape,
    kc(42),     KS_Cmd_ResetEmul,KS_Delete,
    kc(43),     KS_Tab,         KS_Backtab,
    kc(44),     KS_space,
    kc(45),     KS_minus,       KS_underscore,
    kc(46),     KS_equal,       KS_plus,
    kc(47),     KS_bracketleft, KS_braceleft,
    kc(48),     KS_bracketright,KS_braceright,
    kc(49),     KS_backslash,   KS_bar,
    kc(50),     KS_backslash,   KS_bar,
    kc(51),     KS_semicolon,   KS_colon,
    kc(52),     KS_apostrophe,  KS_quotedbl,
    kc(53),     KS_grave,       KS_asciitilde,
    kc(54),     KS_comma,       KS_less,
    kc(55),     KS_period,      KS_greater,
    kc(56),     KS_slash,       KS_question,
    kc(57),     KS_Caps_Lock,
    kc(58),     KS_Cmd_Screen0, KS_f1,
    kc(59),     KS_Cmd_Screen1, KS_f2,
    kc(60),     KS_Cmd_Screen2, KS_f3,
    kc(61),     KS_Cmd_Screen3, KS_f4,
    kc(62),     KS_Cmd_Screen4, KS_f5,
    kc(63),     KS_Cmd_Screen5, KS_f6,
    kc(64),     KS_Cmd_Screen6, KS_f7,
    kc(65),     KS_Cmd_Screen7, KS_f8,
    kc(66),     KS_Cmd_Screen8, KS_f9,
    kc(67),     KS_Cmd_Screen9, KS_f10,
    kc(68),     KS_Cmd_Screen10,KS_f11,
    kc(69),     KS_Cmd_Screen11,KS_f12,
    kc(70),     KS_Print_Screen,
    kc(71),     KS_Hold_Screen,
    kc(72),     KS_Pause, // Break
    kc(73),     KS_Insert,
    kc(74),     KS_Home,
    kc(75),     KS_Cmd_ScrollBack,KS_Prior,
    kc(76),     KS_Cmd_KbdReset,KS_KP_Delete,
    kc(77),     KS_End,
    kc(78),     KS_Cmd_ScrollFwd,KS_Next,
    kc(79),     KS_Right,
    kc(80),     KS_Left,
    kc(81),     KS_Down,
    kc(82),     KS_Up,
    kc(83),     KS_Num_Lock,
    kc(84),     KS_KP_Divide,
    kc(85),     KS_KP_Multiply,
    kc(86),     KS_KP_Subtract,
    kc(87),     KS_KP_Add,
    kc(88),     KS_KP_Enter,
    kc(89),     KS_KP_End,      KS_KP_1,
    kc(90),     KS_KP_Down,     KS_KP_2,
    kc(91),     KS_KP_Next,     KS_KP_3,
    kc(92),     KS_KP_Left,     KS_KP_4,
    kc(93),     KS_KP_Begin,    KS_KP_5,
    kc(94),     KS_KP_Right,    KS_KP_6,
    kc(95),     KS_KP_Home,     KS_KP_7,
    kc(96),     KS_KP_Up,       KS_KP_8,
    kc(97),     KS_KP_Prior,    KS_KP_9,
    kc(98),     KS_KP_Insert,   KS_KP_0,
    kc(99),     KS_KP_Delete,   KS_KP_Decimal,
    kc(101),    KS_Menu,
    kc(102),    KS_Cmd_Sleep,
    kc(104),    KS_f13,
    kc(105),    KS_f14,
    kc(106),    KS_f15,
    kc(107),    KS_f16,
    kc(108),    KS_f17,
    kc(109),    KS_f18,
    kc(110),    KS_f19,
    kc(111),    KS_f20,
    kc(112),    KS_f21,
    kc(113),    KS_f22,
    kc(114),    KS_f23,
    kc(115),    KS_f24,
    kc(116),    KS_Open,
    kc(117),    KS_Help,
    kc(118),    KS_Props,
    kc(119),    KS_Front,
    kc(120),    KS_Cmd,
    kc(121),    KS_Again,
    kc(122),    KS_Undo,
    kc(123),    KS_Cut,
    kc(124),    KS_Copy,
    kc(125),    KS_Paste,
    kc(126),    KS_Find,
    kc(127),    KS_AudioMute,
    kc(128),    KS_AudioRaise,
    kc(129),    KS_AudioLower,
    kc(224),    KS_Cmd1,        KS_Control_L,
    kc(225),    KS_Shift_L,
    kc(226),    KS_Cmd2,        KS_Alt_L,
    kc(227),    KS_Meta_L,
    kc(228),    KS_Cmd1,        KS_Control_R,
    kc(229),    KS_Shift_R,
    kc(230),    KS_Cmd2,        KS_Alt_R,       KS_Multi_key,
    kc(231),    KS_Meta_R,
    kc(232),    KS_Cmd_BrightnessUp,
    kc(233),    KS_Cmd_BrightnessDown,
    kc(234),    KS_Cmd_KbdBacklightToggle,
    kc(235),    KS_Cmd_KbdBacklightUp,
    kc(236),    KS_Cmd_KbdBacklightDown,
];

// #if !defined(WSKBD_NO_INTL_LAYOUTS)

/// `ukbd_keydesc_de`.
#[rustfmt::skip]
static UKBD_KEYDESC_DE: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(16),     KS_m,           KS_M,           KS_mu,
    kc(20),     KS_q,           KS_Q,           KS_at,
    kc(28),     KS_z,
    kc(29),     KS_y,
    kc(31),     KS_2,           KS_quotedbl,    KS_twosuperior,
    kc(32),     KS_3,           KS_section,     KS_threesuperior,
    kc(35),     KS_6,           KS_ampersand,
    kc(36),     KS_7,           KS_slash,       KS_braceleft,
    kc(37),     KS_8,           KS_parenleft,   KS_bracketleft,
    kc(38),     KS_9,           KS_parenright,  KS_bracketright,
    kc(39),     KS_0,           KS_equal,       KS_braceright,
    kc(45),     KS_ssharp,      KS_question,    KS_backslash,
    kc(46),     KS_dead_acute,  KS_dead_grave,
    kc(47),     KS_udiaeresis,
    kc(48),     KS_plus,        KS_asterisk,    KS_dead_tilde,
    kc(49),     KS_numbersign,  KS_apostrophe,
    kc(50),     KS_numbersign,  KS_apostrophe,
    kc(51),     KS_odiaeresis,
    kc(52),     KS_adiaeresis,
    kc(53),     KS_dead_circumflex,KS_dead_abovering,
    kc(54),     KS_comma,       KS_semicolon,
    kc(55),     KS_period,      KS_colon,
    kc(56),     KS_minus,       KS_underscore,
    kc(100),    KS_less,        KS_greater,     KS_bar,         KS_brokenbar,
    kc(230),    KS_Mode_switch, KS_Multi_key,
];

/// `ukbd_keydesc_de_apple`.
#[rustfmt::skip]
static UKBD_KEYDESC_DE_APPLE: &[KeysymT] = &[
    // pos         normal          shifted         altgr           shifted-altgr
    kc(15),     KS_l,           KS_L,           KS_at,
    kc(34),     KS_5,           KS_percent,     KS_bracketleft,
    kc(35),     KS_6,           KS_ampersand,   KS_bracketright,
    kc(36),     KS_7,           KS_slash,       KS_bar,         KS_backslash,
    kc(37),     KS_8,           KS_parenleft,   KS_braceleft,
    kc(38),     KS_9,           KS_parenright,  KS_braceright,
    kc(17),     KS_n,           KS_N,           KS_asciitilde,
];

/// `ukbd_keydesc_de_nodead`.
#[rustfmt::skip]
static UKBD_KEYDESC_DE_NODEAD: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(46),     KS_apostrophe,  KS_grave,
    kc(48),     KS_plus,        KS_asterisk,    KS_asciitilde,
    kc(53),     KS_asciicircum, KS_degree,
];

/// `ukbd_keydesc_dk`.
#[rustfmt::skip]
static UKBD_KEYDESC_DK: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(31),     KS_2,           KS_quotedbl,    KS_at,
    kc(32),     KS_3,           KS_numbersign,  KS_sterling,
    kc(33),     KS_4,           KS_currency,    KS_dollar,
    kc(35),     KS_6,           KS_ampersand,
    kc(36),     KS_7,           KS_slash,       KS_braceleft,
    kc(37),     KS_8,           KS_parenleft,   KS_bracketleft,
    kc(38),     KS_9,           KS_parenright,  KS_bracketright,
    kc(39),     KS_0,           KS_equal,       KS_braceright,
    kc(45),     KS_plus,        KS_question,
    kc(46),     KS_dead_acute,  KS_dead_grave,  KS_bar,
    kc(47),     KS_aring,
    kc(48),     KS_dead_diaeresis,KS_dead_circumflex,KS_dead_tilde,
    kc(49),     KS_apostrophe,  KS_asterisk,
    kc(50),     KS_apostrophe,  KS_asterisk,
    kc(51),     KS_ae,
    kc(52),     KS_oslash,
    kc(53),     KS_onehalf,     KS_paragraph,
    kc(54),     KS_comma,       KS_semicolon,
    kc(55),     KS_period,      KS_colon,
    kc(56),     KS_minus,       KS_underscore,
    kc(100),    KS_less,        KS_greater,     KS_backslash,
    kc(230),    KS_Mode_switch, KS_Multi_key,
];

/// `ukbd_keydesc_dk_nodead`.
#[rustfmt::skip]
static UKBD_KEYDESC_DK_NODEAD: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(46),     KS_apostrophe,  KS_grave,       KS_bar,
    kc(48),     KS_diaeresis,   KS_asciicircum, KS_asciitilde,
];

/// `ukbd_keydesc_sv`.
#[rustfmt::skip]
static UKBD_KEYDESC_SV: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(45),     KS_plus,        KS_question,    KS_backslash,
    kc(48),     KS_dead_diaeresis,KS_dead_circumflex,KS_dead_tilde,
    kc(51),     KS_odiaeresis,
    kc(52),     KS_adiaeresis,
    kc(53),     KS_section,     KS_onehalf,
    kc(100),    KS_less,        KS_greater,     KS_bar,
    kc(230),    KS_Mode_switch, KS_Multi_key,
];

/// `ukbd_keydesc_sv_nodead`.
#[rustfmt::skip]
static UKBD_KEYDESC_SV_NODEAD: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(46),     KS_apostrophe,  KS_grave,       KS_bar,
    kc(48),     KS_diaeresis,   KS_asciicircum, KS_asciitilde,
];

/// `ukbd_keydesc_no`.
#[rustfmt::skip]
static UKBD_KEYDESC_NO: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(46),     KS_backslash,   KS_dead_grave,  KS_dead_acute,
    kc(48),     KS_dead_diaeresis,KS_dead_circumflex,KS_dead_tilde,
    kc(51),     KS_oslash,
    kc(52),     KS_ae,
    kc(53),     KS_bar,         KS_paragraph,
    kc(100),    KS_less,        KS_greater,
];

/// `ukbd_keydesc_no_nodead`.
#[rustfmt::skip]
static UKBD_KEYDESC_NO_NODEAD: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(46),     KS_backslash,   KS_grave,       KS_acute,
    kc(48),     KS_diaeresis,   KS_asciicircum, KS_asciitilde,
];

/// `ukbd_keydesc_fr`.
#[rustfmt::skip]
static UKBD_KEYDESC_FR: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(4),      KS_q,
    kc(16),     KS_comma,       KS_question,
    kc(20),     KS_a,
    kc(26),     KS_z,
    kc(29),     KS_w,
    kc(30),     KS_ampersand,   KS_1,
    kc(31),     KS_eacute,      KS_2,           KS_asciitilde,
    kc(32),     KS_quotedbl,    KS_3,           KS_numbersign,
    kc(33),     KS_apostrophe,  KS_4,           KS_braceleft,
    kc(34),     KS_parenleft,   KS_5,           KS_bracketleft,
    kc(35),     KS_minus,       KS_6,           KS_bar,
    kc(36),     KS_egrave,      KS_7,           KS_grave,
    kc(37),     KS_underscore,  KS_8,           KS_backslash,
    kc(38),     KS_ccedilla,    KS_9,           KS_asciicircum,
    kc(39),     KS_agrave,      KS_0,           KS_at,
    kc(45),     KS_parenright,  KS_degree,      KS_bracketright,
    kc(46),     KS_equal,       KS_plus,        KS_braceright,
    kc(47),     KS_dead_circumflex,KS_dead_diaeresis,
    kc(48),     KS_dollar,      KS_sterling,    KS_currency,
    kc(49),     KS_asterisk,    KS_mu,
    kc(50),     KS_asterisk,    KS_mu,
    kc(51),     KS_m,
    kc(52),     KS_ugrave,      KS_percent,
    kc(53),     KS_twosuperior,
    kc(54),     KS_semicolon,   KS_period,
    kc(55),     KS_colon,       KS_slash,
    kc(56),     KS_exclam,      KS_section,
    kc(100),    KS_less,        KS_greater,
    kc(230),    KS_Mode_switch, KS_Multi_key,
];

/// `ukbd_keydesc_fr_apple`.
#[rustfmt::skip]
static UKBD_KEYDESC_FR_APPLE: &[KeysymT] = &[
    kc(5),      KS_b,           KS_B,           KS_ssharp,
    kc(8),      KS_e,           KS_E,           KS_ecircumflex, KS_Ecircumflex,
    kc(11),     KS_h,           KS_H,           KS_Igrave,      KS_Icircumflex,
    kc(12),     KS_i,           KS_I,           KS_icircumflex, KS_idiaeresis,
    kc(13),     KS_j,           KS_J,           KS_Idiaeresis,  KS_Iacute,
    kc(14),     KS_k,           KS_K,           KS_Egrave,      KS_Ediaeresis,
    kc(15),     KS_l,           KS_L,           KS_voidSymbol,  KS_bar,
    kc(16),     KS_comma,       KS_question,    KS_voidSymbol,  KS_questiondown,
    kc(17),     KS_n,           KS_N,           KS_asciitilde,
    kc(20),     KS_a,           KS_A,           KS_ae,          KS_AE,
    kc(21),     KS_r,           KS_R,           KS_registered,  KS_comma,
    kc(22),     KS_s,           KS_S,           KS_Ograve,
    kc(26),     KS_z,           KS_Z,           KS_Acircumflex, KS_Aring,
    kc(28),     KS_y,           KS_Y,           KS_Uacute,
    kc(31),     KS_eacute,      KS_2,           KS_ediaeresis,
    kc(32),     KS_quotedbl,    KS_3,
    kc(33),     KS_apostrophe,  KS_4,
    kc(34),     KS_parenleft,   KS_5,           KS_braceleft,   KS_bracketleft,
    kc(35),     KS_section,     KS_6,
    kc(36),     KS_egrave,      KS_7,           KS_guillemotleft,
                                                KS_guillemotright,
    kc(37),     KS_exclam,      KS_8,
    kc(38),     KS_ccedilla,    KS_9,           KS_Ccedilla,    KS_Aacute,
    kc(37),     KS_exclam,      KS_8,           KS_exclamdown,  KS_Ucircumflex,
    kc(39),     KS_agrave,      KS_0,           KS_oslash,      KS_Ooblique,
    kc(45),     KS_parenright,  KS_degree,      KS_braceright,  KS_bracketright,
    kc(46),     KS_minus,       KS_underscore,
    kc(47),     KS_dead_circumflex, KS_dead_diaeresis,
                                                KS_ocircumflex, KS_Ocircumflex,
    kc(48),     KS_dollar,      KS_asterisk,    KS_cent,        KS_yen,
    kc(50),     KS_grave,       KS_sterling,    KS_at,          KS_numbersign,
    kc(51),     KS_m,           KS_M,           KS_mu,          KS_Oacute,
    kc(52),     KS_ugrave,      KS_percent,     KS_Ugrave,
    kc(53),     KS_at,          KS_numbersign,
    kc(55),     KS_colon,       KS_slash,       KS_voidSymbol,  KS_backslash,
    kc(56),     KS_equal,       KS_plus,
    kc(103),    KS_KP_Equal,
    kc(231),    KS_Mode_switch, KS_Multi_key,
];

//
// fr-dvorak-be'po layout, simplified map, per http://www.clavier-dvorak.org/
// (the complete map is still a moving target)
//
/// `ukbd_keydesc_fr_dvorak_bepo`.
#[rustfmt::skip]
static UKBD_KEYDESC_FR_DVORAK_BEPO: &[KeysymT] = &[
                                                // oe ligature
                                                // euro currency
    kc(4),      KS_a,           KS_A,           KS_ae,          KS_AE,
    kc(5),      KS_k,           KS_K,           KS_asciitilde,
    kc(6),      KS_x,           KS_X,           KS_braceright,
    kc(7),      KS_i,           KS_I,           KS_dead_diaeresis,
    kc(8),      KS_p,           KS_P,           KS_ampersand,
    kc(9),      KS_e,           KS_E,
    kc(10),     KS_comma,       KS_semicolon,
    kc(11),     KS_c,
    kc(12),     KS_d,
    kc(13),     KS_t,
    kc(14),     KS_s,
    kc(15),     KS_r,
    kc(16),     KS_q,           KS_Q,
    kc(17),     KS_apostrophe,  KS_question,
    kc(18),     KS_l,
    kc(19),     KS_j,
    kc(20),     KS_b,           KS_B,           KS_bar,
    kc(21),     KS_o,           KS_O,
    kc(22),     KS_u,           KS_U,           KS_ugrave,      KS_Ugrave,
    kc(23),     KS_egrave,      KS_Egrave,      KS_dead_grave,
    kc(24),     KS_v,
    kc(25),     KS_period,      KS_colon, // ellipsis
    kc(26),     KS_eacute,      KS_Eacute,      KS_dead_acute,
    kc(27),     KS_y,           KS_Y,           KS_braceleft,
    kc(28),     KS_dead_circumflex,KS_exclam,
    kc(29),     KS_agrave,      KS_Agrave,      KS_backslash,
    kc(30),     KS_quotedbl,    KS_1,           KS_hyphen,
    kc(31),     KS_guillemotleft,KS_2,          KS_less,
    kc(32),     KS_guillemotright,KS_3,         KS_greater,
    kc(33),     KS_parenleft,   KS_4,           KS_bracketleft,
    kc(34),     KS_parenright,  KS_5,           KS_bracketright,
    kc(35),     KS_at,          KS_6,
    kc(36),     KS_plus,        KS_7,
    kc(37),     KS_minus,       KS_8,
    kc(38),     KS_slash,       KS_9,
    kc(39),     KS_asterisk,    KS_0,
    kc(44),     KS_space,       KS_nobreakspace,KS_underscore,
    kc(45),     KS_equal,       KS_asciicircum,
    kc(46),     KS_percent,     KS_grave,
    kc(47),     KS_z,
    kc(48),     KS_w,
    kc(49),     KS_ccedilla,    KS_Ccedilla,
    kc(50),     KS_ccedilla,    KS_Ccedilla,
    kc(51),     KS_n,
    kc(52),     KS_m,
    kc(53),     KS_dollar,      KS_numbersign,
    kc(54),     KS_g,           KS_G,           KS_mu,
    kc(55),     KS_h,
    kc(56),     KS_f,
    kc(100),    KS_egrave,      KS_Egrave,      KS_slash,
    kc(230),    KS_Mode_switch, KS_Multi_key,
];

/// `ukbd_keydesc_it`.
#[rustfmt::skip]
static UKBD_KEYDESC_IT: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(31),     KS_2,           KS_quotedbl,    KS_twosuperior,
    kc(32),     KS_3,           KS_sterling,    KS_threesuperior,
    kc(34),     KS_5,           KS_percent,
    kc(35),     KS_6,           KS_ampersand,
    kc(36),     KS_7,           KS_slash,
    kc(37),     KS_8,           KS_parenleft,
    kc(38),     KS_9,           KS_parenright,
    kc(39),     KS_0,           KS_equal,
    kc(45),     KS_apostrophe,  KS_question,
    kc(46),     KS_igrave,      KS_asciicircum,
    kc(47),     KS_egrave,      KS_eacute,      KS_braceleft,   KS_bracketleft,
    kc(48),     KS_plus,        KS_asterisk,    KS_braceright,  KS_bracketright,
    kc(49),     KS_ugrave,      KS_section,
    kc(50),     KS_ugrave,      KS_section,
    kc(51),     KS_ograve,      KS_Ccedilla,    KS_at,
    kc(52),     KS_agrave,      KS_degree,      KS_numbersign,
    kc(53),     KS_backslash,   KS_bar,
    kc(54),     KS_comma,       KS_semicolon,
    kc(55),     KS_period,      KS_colon,
    kc(56),     KS_minus,       KS_underscore,
    kc(100),    KS_less,        KS_greater,
    kc(230),    KS_Mode_switch, KS_Multi_key,
];

/// `ukbd_keydesc_uk`.
#[rustfmt::skip]
static UKBD_KEYDESC_UK: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(30),     KS_1,           KS_exclam,      KS_plusminus,   KS_exclamdown,
    kc(31),     KS_2,           KS_quotedbl,    KS_twosuperior, KS_cent,
    kc(32),     KS_3,           KS_sterling,    KS_threesuperior,
    kc(33),     KS_4,           KS_dollar,      KS_acute,       KS_currency,
    kc(34),     KS_5,           KS_percent,     KS_mu,          KS_yen,
    kc(35),     KS_6,           KS_asciicircum, KS_paragraph,
    kc(36),     KS_7,           KS_ampersand,   KS_periodcentered,KS_brokenbar,
    kc(37),     KS_8,           KS_asterisk,    KS_cedilla,     KS_ordfeminine,
    kc(38),     KS_9,           KS_parenleft,   KS_onesuperior, KS_diaeresis,
    kc(39),     KS_0,           KS_parenright,  KS_masculine,   KS_copyright,
    kc(45),     KS_minus,       KS_underscore,  KS_hyphen,      KS_ssharp,
    kc(46),     KS_equal,       KS_plus,        KS_onehalf,     KS_guillemotleft,
    kc(49),     KS_numbersign,  KS_asciitilde,  KS_sterling,    KS_thorn,
    kc(50),     KS_numbersign,  KS_asciitilde,  KS_sterling,    KS_thorn,
    kc(52),     KS_apostrophe,  KS_at,          KS_section,     KS_Agrave,
    kc(53),     KS_grave,       KS_grave,       KS_agrave,      KS_agrave,
    kc(100),    KS_backslash,   KS_bar,         KS_Udiaeresis,
];

/// `ukbd_keydesc_jp`.
#[rustfmt::skip]
static UKBD_KEYDESC_JP: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(31),     KS_2,           KS_quotedbl,
    kc(35),     KS_6,           KS_ampersand,
    kc(36),     KS_7,           KS_apostrophe,
    kc(37),     KS_8,           KS_parenleft,
    kc(38),     KS_9,           KS_parenright,
    kc(39),     KS_0,
    kc(45),     KS_minus,       KS_equal,
    kc(46),     KS_asciicircum, KS_asciitilde,
    kc(47),     KS_at,          KS_grave,
    kc(48),     KS_bracketleft, KS_braceleft,
    kc(49),     KS_bracketright,KS_braceright,
    kc(50),     KS_bracketright,KS_braceright,
    kc(51),     KS_semicolon,   KS_plus,
    kc(52),     KS_colon,       KS_asterisk,
    kc(53),     KS_Zenkaku_Hankaku, // replacegrave/tilde
    kc(135),    KS_backslash,   KS_underscore,
    kc(136),    KS_Hiragana_Katakana,
    kc(137),    KS_backslash,   KS_bar,
    kc(138),    KS_Henkan,
    kc(139),    KS_Muhenkan,
];

/// `ukbd_keydesc_es`.
#[rustfmt::skip]
static UKBD_KEYDESC_ES: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(30),     KS_1,           KS_exclam,      KS_bar,
    kc(31),     KS_2,           KS_quotedbl,    KS_at,
    kc(32),     KS_3,           KS_periodcentered,KS_numbersign,
    kc(33),     KS_4,           KS_dollar,      KS_asciitilde,
    kc(35),     KS_6,           KS_ampersand,
    kc(36),     KS_7,           KS_slash,
    kc(37),     KS_8,           KS_parenleft,
    kc(38),     KS_9,           KS_parenright,
    kc(39),     KS_0,           KS_equal,
    kc(45),     KS_apostrophe,  KS_question,
    kc(46),     KS_exclamdown,  KS_questiondown,
    kc(47),     KS_dead_grave,  KS_dead_circumflex,KS_bracketleft,
    kc(48),     KS_plus,        KS_asterisk,    KS_bracketright,
    kc(49),     KS_ccedilla,    KS_Ccedilla,    KS_braceright,
    kc(50),     KS_ccedilla,    KS_Ccedilla,    KS_braceright,
    kc(51),     KS_ntilde,
    kc(52),     KS_dead_acute,  KS_dead_diaeresis,KS_braceleft,
    kc(53),     KS_degree,      KS_ordfeminine, KS_backslash,
    kc(54),     KS_comma,       KS_semicolon,
    kc(55),     KS_period,      KS_colon,
    kc(56),     KS_minus,       KS_underscore,
    kc(100),    KS_less,        KS_greater,
    kc(230),    KS_Mode_switch, KS_Multi_key,
];

/// `ukbd_keydesc_lt`.
#[rustfmt::skip]
static UKBD_KEYDESC_LT: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(8),      KS_e,           KS_E,           KS_currency,
    kc(9),      KS_L7_scaron,   KS_L7_Scaron,
    kc(20),     KS_L7_aogonek,  KS_L7_Aogonek,
    kc(26),     KS_L7_zcaron,   KS_L7_Zcaron,
    kc(27),     KS_L7_umacron,  KS_L7_Umacron,
    kc(30),     KS_exclam,      KS_1,           KS_at,
    kc(31),     KS_minus,       KS_2,           KS_underscore,
    kc(32),     KS_slash,       KS_3,           KS_numbersign,
    kc(33),     KS_semicolon,   KS_4,           KS_dollar,
    kc(34),     KS_colon,       KS_5,           KS_paragraph,
    kc(35),     KS_comma,       KS_6,           KS_asciicircum,
    kc(36),     KS_period,      KS_7,           KS_ampersand,
    kc(37),     KS_equal,       KS_8,           KS_asterisk,
    kc(38),     KS_bracketleft, KS_9,           KS_parenleft,
    kc(39),     KS_bracketright,KS_0,           KS_parenright,
    kc(44),     KS_space,       KS_space,       KS_nobreakspace,
    kc(45),     KS_question,    KS_plus,        KS_apostrophe,
    kc(46),     KS_x,           KS_X,           KS_percent,
    kc(47),     KS_L7_iogonek,  KS_L7_Iogonek,  KS_braceleft,
    kc(48),     KS_w,           KS_W,           KS_braceright,
    kc(49),     KS_q,           KS_Q,           KS_bar,
    kc(50),     KS_q,           KS_Q,           KS_bar,
    kc(51),     KS_L7_uogonek,  KS_L7_Uogonek,
    kc(52),     KS_L7_edot,     KS_L7_Edot,     KS_quotedbl,
    kc(53),     KS_grave,       KS_asciitilde,
    kc(54),     KS_L7_ccaron,   KS_L7_Ccaron,   KS_L7_dbllow9quot,
    kc(55),     KS_f,           KS_F,           KS_L7_leftdblquot,
    kc(56),     KS_L7_eogonek,  KS_L7_Eogonek,  KS_backslash,
    kc(230),    KS_Mode_switch, KS_Multi_key,
];

/// `ukbd_keydesc_be`.
#[rustfmt::skip]
static UKBD_KEYDESC_BE: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(4),      KS_q,
    kc(16),     KS_comma,       KS_question,
    kc(20),     KS_a,
    kc(26),     KS_z,
    kc(29),     KS_w,
    kc(30),     KS_ampersand,   KS_1,           KS_bar,
    kc(31),     KS_eacute,      KS_2,           KS_at,
    kc(32),     KS_quotedbl,    KS_3,           KS_numbersign,
    kc(33),     KS_apostrophe,  KS_4,
    kc(34),     KS_parenleft,   KS_5,
    kc(35),     KS_section,     KS_6,           KS_asciicircum,
    kc(36),     KS_egrave,      KS_7,
    kc(37),     KS_exclam,      KS_8,
    kc(38),     KS_ccedilla,    KS_9,           KS_braceleft,
    kc(39),     KS_agrave,      KS_0,           KS_braceright,
    kc(45),     KS_parenright,  KS_degree,
    kc(46),     KS_minus,       KS_underscore,
    kc(47),     KS_dead_circumflex,KS_dead_diaeresis,KS_bracketleft,
    kc(48),     KS_dollar,      KS_asterisk,    KS_bracketright,
    kc(49),     KS_mu,          KS_sterling,    KS_grave,
    kc(50),     KS_mu,          KS_sterling,    KS_grave,
    kc(51),     KS_m,
    kc(52),     KS_ugrave,      KS_percent,     KS_acute,
    kc(53),     KS_twosuperior, KS_threesuperior,
    kc(54),     KS_semicolon,   KS_period,
    kc(55),     KS_colon,       KS_slash,
    kc(56),     KS_equal,       KS_plus,        KS_asciitilde,
    kc(100),    KS_less,        KS_greater,     KS_backslash,
    kc(230),    KS_Mode_switch, KS_Multi_key,
];

/// `ukbd_keydesc_us_dvorak`.
#[rustfmt::skip]
static UKBD_KEYDESC_US_DVORAK: &[KeysymT] = &[
    // pos      command            normal          shifted
    kc(5),      KS_x,
    kc(6),      KS_j,
    kc(7),      KS_e,
    kc(8),      KS_period,      KS_greater,
    kc(9),      KS_u,
    kc(10),     KS_i,
    kc(11),     KS_d,
    kc(12),     KS_c,
    kc(13),     KS_h,
    kc(14),     KS_t,
    kc(15),     KS_n,
    kc(17),     KS_b,
    kc(18),     KS_r,
    kc(19),     KS_l,
    kc(20),     KS_apostrophe,  KS_quotedbl,
    kc(21),     KS_p,
    kc(22),     KS_o,
    kc(23),     KS_y,
    kc(24),     KS_g,
    kc(25),     KS_k,
    kc(26),     KS_comma,       KS_less,
    kc(27),     KS_q,
    kc(28),     KS_f,
    kc(29),     KS_semicolon,   KS_colon,
    kc(45),     KS_bracketleft, KS_braceleft,
    kc(46),     KS_bracketright,KS_braceright,
    kc(47),     KS_slash,       KS_question,
    kc(48),     KS_equal,       KS_plus,
    kc(51),     KS_s,
    kc(52),     KS_minus,       KS_underscore,
    kc(54),     KS_w,
    kc(55),     KS_v,
    kc(56),     KS_z,
];

/// `ukbd_keydesc_us_colemak`.
#[rustfmt::skip]
static UKBD_KEYDESC_US_COLEMAK: &[KeysymT] = &[
    // pos      command            normal          shifted
    kc(7),      KS_s,
    kc(8),      KS_f,
    kc(9),      KS_t,
    kc(10),     KS_d,
    kc(12),     KS_u,
    kc(13),     KS_n,
    kc(14),     KS_e,
    kc(15),     KS_i,           KS_I,
    kc(17),     KS_k,
    kc(18),     KS_y,
    kc(19),     KS_semicolon,   KS_colon,
    kc(21),     KS_p,
    kc(22),     KS_r,
    kc(23),     KS_g,
    kc(24),     KS_l,
    kc(28),     KS_j,
    kc(51),     KS_o,
];

/// `ukbd_keydesc_swapctrlcaps`.
#[rustfmt::skip]
static UKBD_KEYDESC_SWAPCTRLCAPS: &[KeysymT] = &[
    // pos      command            normal          shifted
    kc(57),     KS_Cmd1,        KS_Control_L,
    kc(224),    KS_Caps_Lock,
];

/// `ukbd_keydesc_ru`.
#[rustfmt::skip]
static UKBD_KEYDESC_RU: &[KeysymT] = &[
    // pos      normal             shifted         altgr                   shift-altgr
    kc(4),      KS_a,           KS_A,           KS_Cyrillic_ef, KS_Cyrillic_EF,
    kc(5),      KS_b,           KS_B,           KS_Cyrillic_i,  KS_Cyrillic_I,
    kc(6),      KS_c,           KS_C,           KS_Cyrillic_es, KS_Cyrillic_ES,
    kc(7),      KS_d,           KS_D,           KS_Cyrillic_ve, KS_Cyrillic_VE,
    kc(8),      KS_e,           KS_E,           KS_Cyrillic_u,  KS_Cyrillic_U,
    kc(9),      KS_f,           KS_F,           KS_Cyrillic_a,  KS_Cyrillic_A,
    kc(10),     KS_g,           KS_G,           KS_Cyrillic_pe, KS_Cyrillic_PE,
    kc(11),     KS_h,           KS_H,           KS_Cyrillic_er, KS_Cyrillic_ER,
    kc(12),     KS_i,           KS_I,           KS_Cyrillic_sha,KS_Cyrillic_SHA,
    kc(13),     KS_j,           KS_J,           KS_Cyrillic_o,  KS_Cyrillic_O,
    kc(14),     KS_k,           KS_K,           KS_Cyrillic_el, KS_Cyrillic_EL,
    kc(15),     KS_l,           KS_L,           KS_Cyrillic_de, KS_Cyrillic_DE,
    kc(16),     KS_m,           KS_M,           KS_Cyrillic_ssighn,KS_Cyrillic_SSIGHN,
    kc(17),     KS_n,           KS_N,           KS_Cyrillic_te, KS_Cyrillic_TE,
    kc(18),     KS_o,           KS_O,           KS_Cyrillic_scha,KS_Cyrillic_SCHA,
    kc(19),     KS_p,           KS_P,           KS_Cyrillic_ze, KS_Cyrillic_ZE,
    kc(20),     KS_q,           KS_Q,           KS_Cyrillic_ishort,KS_Cyrillic_ISHORT,
    kc(21),     KS_r,           KS_R,           KS_Cyrillic_ka, KS_Cyrillic_KA,
    kc(22),     KS_s,           KS_S,           KS_Cyrillic_yeru,KS_Cyrillic_YERU,
    kc(23),     KS_t,           KS_T,           KS_Cyrillic_ie, KS_Cyrillic_IE,
    kc(24),     KS_u,           KS_U,           KS_Cyrillic_ge, KS_Cyrillic_GE,
    kc(25),     KS_v,           KS_V,           KS_Cyrillic_em, KS_Cyrillic_EM,
    kc(26),     KS_w,           KS_W,           KS_Cyrillic_tse,KS_Cyrillic_TSE,
    kc(27),     KS_x,           KS_X,           KS_Cyrillic_che,KS_Cyrillic_CHE,
    kc(28),     KS_y,           KS_Y,           KS_Cyrillic_en, KS_Cyrillic_EN,
    kc(29),     KS_z,           KS_Z,           KS_Cyrillic_ya, KS_Cyrillic_YA,
    kc(35),     KS_6,           KS_asciicircum, KS_6,           KS_comma,
    kc(36),     KS_7,           KS_ampersand,   KS_7,           KS_period,
    kc(47),     KS_bracketleft, KS_braceleft,   KS_Cyrillic_ha, KS_Cyrillic_HA,
    kc(48),     KS_bracketright,KS_braceright,  KS_Cyrillic_hsighn,KS_Cyrillic_HSIGHN,
    kc(51),     KS_semicolon,   KS_colon,       KS_Cyrillic_zhe,KS_Cyrillic_ZHE,
    kc(52),     KS_apostrophe,  KS_quotedbl,    KS_Cyrillic_e,  KS_Cyrillic_E,
    kc(54),     KS_comma,       KS_less,        KS_Cyrillic_be, KS_Cyrillic_BE,
    kc(55),     KS_period,      KS_greater,     KS_Cyrillic_yu, KS_Cyrillic_YU,
    kc(56),     KS_slash,       KS_question,    KS_Cyrillic_yo, KS_Cyrillic_YO,
    kc(230),    KS_Mode_switch, KS_Multi_key,
];

/// `ukbd_keydesc_ua`.
#[rustfmt::skip]
static UKBD_KEYDESC_UA: &[KeysymT] = &[
    // pos      normal             shifted         altgr                   shift-altgr
    kc(4),      KS_a,           KS_A,           KS_Cyrillic_ef, KS_Cyrillic_EF,
    kc(5),      KS_b,           KS_B,           KS_Cyrillic_i,  KS_Cyrillic_I,
    kc(6),      KS_c,           KS_C,           KS_Cyrillic_es, KS_Cyrillic_ES,
    kc(7),      KS_d,           KS_D,           KS_Cyrillic_ve, KS_Cyrillic_VE,
    kc(8),      KS_e,           KS_E,           KS_Cyrillic_u,  KS_Cyrillic_U,
    kc(9),      KS_f,           KS_F,           KS_Cyrillic_a,  KS_Cyrillic_A,
    kc(10),     KS_g,           KS_G,           KS_Cyrillic_pe, KS_Cyrillic_PE,
    kc(11),     KS_h,           KS_H,           KS_Cyrillic_er, KS_Cyrillic_ER,
    kc(12),     KS_i,           KS_I,           KS_Cyrillic_sha,KS_Cyrillic_SHA,
    kc(13),     KS_j,           KS_J,           KS_Cyrillic_o,  KS_Cyrillic_O,
    kc(14),     KS_k,           KS_K,           KS_Cyrillic_el, KS_Cyrillic_EL,
    kc(15),     KS_l,           KS_L,           KS_Cyrillic_de, KS_Cyrillic_DE,
    kc(16),     KS_m,           KS_M,           KS_Cyrillic_ssighn,KS_Cyrillic_SSIGHN,
    kc(17),     KS_n,           KS_N,           KS_Cyrillic_te, KS_Cyrillic_TE,
    kc(18),     KS_o,           KS_O,           KS_Cyrillic_scha,KS_Cyrillic_SCHA,
    kc(19),     KS_p,           KS_P,           KS_Cyrillic_ze, KS_Cyrillic_ZE,
    kc(20),     KS_q,           KS_Q,           KS_Cyrillic_ishort,KS_Cyrillic_ISHORT,
    kc(21),     KS_r,           KS_R,           KS_Cyrillic_ka, KS_Cyrillic_KA,
    kc(22),     KS_s,           KS_S,           KS_Cyrillic_yeru,KS_Cyrillic_YERU,
    kc(23),     KS_t,           KS_T,           KS_Cyrillic_ie, KS_Cyrillic_IE,
    kc(24),     KS_u,           KS_U,           KS_Cyrillic_ge, KS_Cyrillic_GE,
    kc(25),     KS_v,           KS_V,           KS_Cyrillic_em, KS_Cyrillic_EM,
    kc(26),     KS_w,           KS_W,           KS_Cyrillic_tse,KS_Cyrillic_TSE,
    kc(27),     KS_x,           KS_X,           KS_Cyrillic_che,KS_Cyrillic_CHE,
    kc(28),     KS_y,           KS_Y,           KS_Cyrillic_en, KS_Cyrillic_EN,
    kc(29),     KS_z,           KS_Z,           KS_Cyrillic_ya, KS_Cyrillic_YA,
    kc(35),     KS_6,           KS_asciicircum, KS_6,           KS_comma,
    kc(36),     KS_7,           KS_ampersand,   KS_7,           KS_period,
    kc(45),     KS_minus,       KS_underscore,  KS_Cyrillic_iukr,KS_Cyrillic_IUKR,
    kc(46),     KS_equal,       KS_plus,        KS_Cyrillic_yeukr,KS_Cyrillic_YEUKR,
    kc(47),     KS_bracketleft, KS_braceleft,   KS_Cyrillic_ha, KS_Cyrillic_HA,
    kc(48),     KS_bracketright,KS_braceright,  KS_Cyrillic_hsighn,KS_Cyrillic_HSIGHN,
    kc(49),     KS_backslash,   KS_bar,         KS_Cyrillic_yi, KS_Cyrillic_YI,
    kc(50),     KS_backslash,   KS_bar,         KS_Cyrillic_yi, KS_Cyrillic_YI,
    kc(51),     KS_semicolon,   KS_colon,       KS_Cyrillic_zhe,KS_Cyrillic_ZHE,
    kc(52),     KS_apostrophe,  KS_quotedbl,    KS_Cyrillic_e,  KS_Cyrillic_E,
    kc(53),     KS_grave,       KS_asciitilde,  KS_Cyrillic_gheukr,KS_Cyrillic_GHEUKR,
    kc(54),     KS_comma,       KS_less,        KS_Cyrillic_be, KS_Cyrillic_BE,
    kc(55),     KS_period,      KS_greater,     KS_Cyrillic_yu, KS_Cyrillic_YU,
    kc(56),     KS_slash,       KS_question,    KS_Cyrillic_yo, KS_Cyrillic_YO,
    kc(230),    KS_Mode_switch, KS_Multi_key,
];

/// `ukbd_keydesc_sg`.
#[rustfmt::skip]
static UKBD_KEYDESC_SG: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(8),      KS_e,           KS_E,           KS_currency,
    kc(28),     KS_z,
    kc(29),     KS_y,
    kc(30),     KS_1,           KS_plus,        KS_bar,
    kc(31),     KS_2,           KS_quotedbl,    KS_at,
    kc(32),     KS_3,           KS_asterisk,    KS_numbersign,
    kc(33),     KS_4,           KS_ccedilla,
    kc(35),     KS_6,           KS_ampersand,   KS_notsign,
    kc(36),     KS_7,           KS_slash,       KS_brokenbar,
    kc(37),     KS_8,           KS_parenleft,   KS_cent,
    kc(38),     KS_9,           KS_parenright,
    kc(39),     KS_0,           KS_equal,
    kc(45),     KS_apostrophe,  KS_question,    KS_dead_acute,
    kc(46),     KS_dead_circumflex,KS_dead_grave,KS_dead_tilde,
    kc(47),     KS_udiaeresis,  KS_egrave,      KS_bracketleft,
    kc(48),     KS_dead_diaeresis,KS_exclam,    KS_bracketright,
    kc(49),     KS_dollar,      KS_sterling,    KS_braceright,
    kc(50),     KS_dollar,      KS_sterling,    KS_braceright,
    kc(51),     KS_odiaeresis,  KS_eacute,
    kc(52),     KS_adiaeresis,  KS_agrave,      KS_braceleft,
    kc(53),     KS_section,     KS_degree,      KS_dead_abovering,
    kc(54),     KS_comma,       KS_semicolon,
    kc(55),     KS_period,      KS_colon,
    kc(56),     KS_minus,       KS_underscore,
    kc(100),    KS_less,        KS_greater,     KS_backslash,
    kc(230),    KS_Mode_switch, KS_Multi_key,
];

/// `ukbd_keydesc_sg_nodead`.
#[rustfmt::skip]
static UKBD_KEYDESC_SG_NODEAD: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(45),     KS_apostrophe,  KS_question,    KS_acute,
    kc(46),     KS_asciicircum, KS_grave,       KS_asciitilde,
    kc(48),     KS_diaeresis,   KS_exclam,      KS_bracketright,
];

/// `ukbd_keydesc_sf`.
#[rustfmt::skip]
static UKBD_KEYDESC_SF: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(47),     KS_egrave,      KS_udiaeresis,  KS_bracketleft,
    kc(51),     KS_eacute,      KS_odiaeresis,
    kc(52),     KS_agrave,      KS_adiaeresis,  KS_braceleft,
];

/// `ukbd_keydesc_pt`.
#[rustfmt::skip]
static UKBD_KEYDESC_PT: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(31),     KS_2,           KS_quotedbl,    KS_at,
    kc(32),     KS_3,           KS_numbersign,  KS_sterling,
    kc(35),     KS_6,           KS_ampersand,
    kc(36),     KS_7,           KS_slash,       KS_braceleft,
    kc(37),     KS_8,           KS_parenleft,   KS_bracketleft,
    kc(38),     KS_9,           KS_parenright,  KS_bracketright,
    kc(39),     KS_0,           KS_equal,       KS_braceright,
    kc(45),     KS_apostrophe,  KS_question,
    kc(46),     KS_less,        KS_greater,
    kc(47),     KS_plus,        KS_asterisk,
    kc(48),     KS_dead_acute,  KS_dead_grave,
    kc(49),     KS_dead_tilde,  KS_dead_circumflex,
    kc(50),     KS_dead_tilde,  KS_dead_circumflex,
    kc(51),     KS_ccedilla,    KS_Ccedilla,
    kc(52),     KS_masculine,   KS_ordfeminine,
    kc(53),     KS_backslash,   KS_bar,
    kc(54),     KS_comma,       KS_semicolon,
    kc(55),     KS_period,      KS_colon,
    kc(56),     KS_minus,       KS_underscore,
    kc(100),    KS_less,        KS_greater,
    kc(230),    KS_Mode_switch, KS_Multi_key,
];

/// `ukbd_keydesc_pt_apple`.
#[rustfmt::skip]
static UKBD_KEYDESC_PT_APPLE: &[KeysymT] = &[
    // pos         normal          shifted
    kc(46),     KS_plus,        KS_asterisk,
    kc(47),     KS_masculine,   KS_ordfeminine,
    kc(50),     KS_backslash,   KS_bar,
    kc(52),     KS_dead_tilde,  KS_dead_circumflex
];

/// `ukbd_keydesc_la`.
#[rustfmt::skip]
static UKBD_KEYDESC_LA: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(20),     KS_q,           KS_Q,           KS_at,
    kc(30),     KS_1,           KS_exclam,
    kc(31),     KS_2,           KS_quotedbl,
    kc(32),     KS_3,           KS_numbersign,
    kc(35),     KS_6,           KS_ampersand,
    kc(36),     KS_7,           KS_slash,
    kc(37),     KS_8,           KS_parenleft,
    kc(38),     KS_9,           KS_parenright,
    kc(39),     KS_0,           KS_equal,
    kc(45),     KS_apostrophe,  KS_question,    KS_backslash,
    kc(46),     KS_questiondown,KS_exclamdown,
    kc(47),     KS_dead_acute,  KS_dead_diaeresis,
    kc(48),     KS_plus,        KS_asterisk,    KS_asciitilde,
    kc(49),     KS_braceright,  KS_bracketright,KS_dead_grave,
    kc(50),     KS_braceright,  KS_bracketright,KS_dead_grave,
    kc(51),     KS_ntilde,
    kc(52),     KS_braceleft,   KS_bracketleft, KS_dead_circumflex,
    kc(53),     KS_bar,         KS_degree,      KS_notsign,
    kc(54),     KS_comma,       KS_semicolon,
    kc(55),     KS_period,      KS_colon,
    kc(56),     KS_minus,       KS_underscore,
    kc(100),    KS_less,        KS_greater,
    kc(230),    KS_Mode_switch, KS_Multi_key,
];

/// `ukbd_keydesc_br`.
#[rustfmt::skip]
static UKBD_KEYDESC_BR: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(30),     KS_1,           KS_exclam,      KS_onesuperior,
    kc(31),     KS_2,           KS_at,          KS_twosuperior,
    kc(32),     KS_3,           KS_numbersign,  KS_threesuperior,
    kc(33),     KS_4,           KS_dollar,      KS_sterling,
    kc(34),     KS_5,           KS_percent,     KS_cent,
    kc(35),     KS_6,           KS_dead_diaeresis,KS_notsign,
    kc(46),     KS_equal,       KS_plus,        KS_section,
    kc(47),     KS_dead_acute,  KS_dead_grave,
    kc(48),     KS_bracketleft, KS_braceleft,   KS_ordfeminine,
    kc(49),     KS_bracketright,KS_braceright,  KS_masculine,
    kc(50),     KS_bracketright,KS_braceright,  KS_masculine,
    kc(51),     KS_ccedilla,    KS_Ccedilla,
    kc(52),     KS_dead_tilde,  KS_dead_circumflex,
    kc(53),     KS_apostrophe,  KS_quotedbl,
    kc(56),     KS_semicolon,   KS_colon,
    kc(99),     KS_KP_Delete,   KS_KP_Decimal,
    kc(100),    KS_backslash,   KS_bar,
    kc(135),    KS_slash,       KS_question,    KS_degree,
];

/// `ukbd_keydesc_tr`.
#[rustfmt::skip]
static UKBD_KEYDESC_TR: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(12),     KS_L5_idotless, KS_I,
    kc(20),     KS_q,           KS_Q,           KS_at,
    kc(31),     KS_2,           KS_apostrophe,  KS_sterling,
    kc(32),     KS_3,           KS_asciicircum, KS_numbersign,
    kc(33),     KS_4,           KS_plus,        KS_dollar,
    kc(34),     KS_5,           KS_percent,     KS_onehalf,
    kc(35),     KS_6,           KS_ampersand,
    kc(36),     KS_7,           KS_slash,       KS_braceleft,
    kc(37),     KS_8,           KS_parenleft,   KS_bracketleft,
    kc(38),     KS_9,           KS_parenright,  KS_bracketright,
    kc(39),     KS_0,           KS_equal,       KS_braceright,
    kc(45),     KS_asterisk,    KS_question,    KS_backslash,
    kc(46),     KS_minus,       KS_underscore,
    kc(47),     KS_L5_gbreve,   KS_L5_Gbreve,   KS_dead_diaeresis,
    kc(48),     KS_udiaeresis,  KS_Udiaeresis,  KS_asciitilde,
    kc(49),     KS_comma,       KS_semicolon,   KS_dead_grave,
    kc(50),     KS_comma,       KS_semicolon,   KS_dead_grave,
    kc(51),     KS_L5_scedilla, KS_L5_Scedilla, KS_dead_acute,
    kc(52),     KS_i,           KS_L5_Idotabove,
    kc(53),     KS_quotedbl,    KS_eacute,
    kc(54),     KS_odiaeresis,  KS_Odiaeresis,
    kc(55),     KS_ccedilla,    KS_Ccedilla,
    kc(56),     KS_period,      KS_colon,
    kc(100),    KS_less,        KS_greater,     KS_bar,
    kc(230),    KS_Mode_switch, KS_Multi_key,
];

/// `ukbd_keydesc_tr_nodead`.
#[rustfmt::skip]
static UKBD_KEYDESC_TR_NODEAD: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(47),     KS_L5_gbreve,   KS_L5_Gbreve,
    kc(49),     KS_comma,       KS_semicolon,   KS_grave,
    kc(50),     KS_comma,       KS_semicolon,   KS_grave,
    kc(51),     KS_L5_scedilla, KS_L5_Scedilla, KS_apostrophe,
];

/// `ukbd_keydesc_pl`.
#[rustfmt::skip]
static UKBD_KEYDESC_PL: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(4),      KS_a,           KS_A,           KS_L2_aogonek,  KS_L2_Aogonek,
    kc(6),      KS_c,           KS_C,           KS_L2_cacute,   KS_L2_Cacute,
    kc(8),      KS_e,           KS_E,           KS_L2_eogonek,  KS_L2_Eogonek,
    kc(15),     KS_l,           KS_L,           KS_L2_lstroke,  KS_L2_Lstroke,
    kc(17),     KS_n,           KS_N,           KS_L2_nacute,   KS_L2_Nacute,
    kc(18),     KS_o,           KS_O,           KS_oacute,      KS_Oacute,
    kc(22),     KS_s,           KS_S,           KS_L2_sacute,   KS_L2_Sacute,
    kc(27),     KS_x,           KS_X,           KS_L2_zacute,   KS_L2_Zacute,
    kc(29),     KS_z,           KS_Z,           KS_L2_zdotabove,KS_L2_Zdotabove,
    kc(230),    KS_Mode_switch, KS_Multi_key,
];

/// `ukbd_keydesc_hu`.
#[rustfmt::skip]
static UKBD_KEYDESC_HU: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(5),      KS_b,           KS_B,           KS_braceleft,
    kc(6),      KS_c,           KS_C,           KS_ampersand,
    kc(9),      KS_f,           KS_F,           KS_bracketleft,
    kc(10),     KS_g,           KS_G,           KS_bracketright,
    kc(12),     KS_i,           KS_I,           KS_iacute,
    kc(13),     KS_j,           KS_J,           KS_iacute,
    kc(17),     KS_n,           KS_N,           KS_braceright,
    kc(20),     KS_q,           KS_Q,           KS_backslash,
    kc(25),     KS_v,           KS_V,           KS_at,
    kc(26),     KS_w,           KS_W,KS_bar,
    kc(27),     KS_x,           KS_X,           KS_numbersign,
    kc(28),     KS_z,           KS_Z,
    kc(29),     KS_y,           KS_Y,           KS_greater,
    kc(30),     KS_1,           KS_apostrophe,  KS_asciitilde,
    kc(31),     KS_2,           KS_quotedbl,
    kc(32),     KS_3,           KS_plus,        KS_asciicircum,
    kc(33),     KS_4,           KS_exclam,
    kc(34),     KS_5,           KS_percent,
    kc(35),     KS_6,           KS_slash,
    kc(36),     KS_7,           KS_equal,KS_grave,
    kc(37),     KS_8,           KS_parenleft,
    kc(38),     KS_9,           KS_parenright,  KS_acute,
    kc(39),     KS_odiaeresis,  KS_Odiaeresis,
    kc(45),     KS_udiaeresis,  KS_Udiaeresis,
    kc(46),     KS_oacute,      KS_Oacute,
    kc(47),     KS_odoubleacute,KS_Odoubleacute,KS_division,
    kc(48),     KS_uacute,      KS_Uacute,      KS_multiply,
    kc(49),     KS_udoubleacute,KS_Udoubleacute,KS_currency,
    kc(50),     KS_udoubleacute,KS_Udoubleacute,KS_currency,
    kc(51),     KS_eacute,      KS_Eacute,      KS_dollar,
    kc(52),     KS_aacute,      KS_Aacute,      KS_ssharp,
    kc(53),     KS_0,           KS_section,
    kc(54),     KS_comma,       KS_question,    KS_semicolon,
    kc(55),     KS_period,      KS_colon,
    kc(56),     KS_minus,       KS_underscore,  KS_asterisk,
    kc(100),    KS_iacute,      KS_Iacute,      KS_less,
    kc(230),    KS_Mode_switch, KS_Multi_key,
];

/// `ukbd_keydesc_si`.
#[rustfmt::skip]
static UKBD_KEYDESC_SI: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(5),      KS_b,           KS_B,           KS_braceleft,
    kc(9),      KS_f,           KS_F,           KS_bracketleft,
    kc(10),     KS_g,           KS_G,           KS_bracketright,
    kc(14),     KS_k,           KS_K,           KS_L2_lstroke,
    kc(15),     KS_l,           KS_L,           KS_L2_Lstroke,
    kc(16),     KS_m,           KS_M,           KS_section,
    kc(17),     KS_n,           KS_N,           KS_braceright,
    kc(20),     KS_q,           KS_Q,           KS_backslash,
    kc(25),     KS_v,           KS_V,           KS_at,
    kc(26),     KS_w,           KS_W,           KS_bar,
    kc(28),     KS_z,           KS_Z,
    kc(29),     KS_y,           KS_Y,
    kc(30),     KS_1,           KS_exclam,      KS_asciitilde,
    kc(31),     KS_2,           KS_quotedbl,    KS_L2_caron,
    kc(32),     KS_3,           KS_numbersign,  KS_asciicircum,
    kc(33),     KS_4,           KS_dollar,      KS_L2_breve,
    kc(34),     KS_5,           KS_percent,     KS_degree,
    kc(35),     KS_6,           KS_ampersand,   KS_L2_ogonek,
    kc(36),     KS_7,           KS_slash,       KS_grave,
    kc(37),     KS_8,           KS_parenleft,   KS_L2_dotabove,
    kc(38),     KS_9,           KS_parenright,  KS_acute,
    kc(39),     KS_0,           KS_equal,       KS_L2_dblacute,
    kc(45),     KS_apostrophe,  KS_question,    KS_diaeresis,
    kc(46),     KS_plus,        KS_asterisk,    KS_cedilla,
    kc(47),     KS_L2_scaron,   KS_L2_Scaron,   KS_division,
    kc(48),     KS_L2_dstroke,  KS_L2_Dstroke,  KS_multiply,
    kc(49),     KS_L2_zcaron,   KS_L2_Zcaron,   KS_currency,
    kc(50),     KS_L2_zcaron,   KS_L2_Zcaron,   KS_currency,
    kc(51),     KS_L2_ccaron,   KS_L2_Ccaron,
    kc(52),     KS_L2_cacute,   KS_L2_Cacute,   KS_ssharp,
    kc(53),     KS_cedilla,     KS_diaeresis,
    kc(54),     KS_comma,       KS_semicolon,   KS_less,
    kc(55),     KS_period,      KS_colon,       KS_greater,
    kc(56),     KS_minus,       KS_underscore,
    kc(100),    KS_less,        KS_greater,
    kc(230),    KS_Mode_switch, KS_Multi_key,
];

/// `ukbd_keydesc_cf`.
#[rustfmt::skip]
static UKBD_KEYDESC_CF: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(16),     KS_m,           KS_M,           KS_mu,
    kc(18),     KS_o,           KS_O,           KS_section,
    kc(19),     KS_p,           KS_P,           KS_paragraph,
    kc(30),     KS_1,           KS_exclam,      KS_plusminus,
    kc(31),     KS_2,           KS_quotedbl,    KS_at,
    kc(32),     KS_3,           KS_slash,       KS_sterling,
    kc(33),     KS_4,           KS_dollar,      KS_cent,
    kc(34),     KS_5,           KS_percent,     KS_diaeresis,
    kc(35),     KS_6,           KS_question,    KS_macron,
    kc(36),     KS_7,           KS_ampersand,   KS_brokenbar,
    kc(37),     KS_8,           KS_asterisk,    KS_twosuperior,
    kc(38),     KS_9,           KS_parenleft,   KS_threesuperior,
    kc(39),     KS_0,           KS_parenright,  KS_onequarter,
    kc(45),     KS_minus,       KS_underscore,  KS_onehalf,
    kc(46),     KS_equal,       KS_plus,        KS_threequarters,
    kc(47),     KS_dead_circumflex,KS_dead_circumflex,KS_bracketleft,
    kc(48),     KS_dead_cedilla,KS_dead_diaeresis,KS_bracketright,
    kc(49),     KS_less,        KS_greater,     KS_braceright,
    kc(50),     KS_less,        KS_greater,     KS_braceright,
    kc(51),     KS_semicolon,   KS_colon,       KS_asciitilde,
    kc(52),     KS_dead_grave,  KS_dead_grave,  KS_braceleft,
    kc(53),     KS_numbersign,  KS_bar,         KS_backslash,
    kc(54),     KS_comma,       KS_apostrophe,  KS_hyphen,
    kc(55),     KS_period,      KS_period,
    kc(56),     KS_eacute,      KS_Eacute,      KS_dead_acute,
    kc(100),    KS_guillemotleft,KS_guillemotright,KS_degree,
    kc(230),    KS_Mode_switch,KS_Multi_key,
];

/// `ukbd_keydesc_cf_nodead`.
#[rustfmt::skip]
static UKBD_KEYDESC_CF_NODEAD: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(47),     KS_asciicircum,KS_asciicircum,KS_bracketleft,
    kc(48),     KS_cedilla,     KS_diaeresis,   KS_bracketright,
    kc(52),     KS_grave,       KS_grave,       KS_braceleft,
    kc(56),     KS_eacute,      KS_Eacute,      KS_acute,
];

/// `ukbd_keydesc_lv`.
#[rustfmt::skip]
static UKBD_KEYDESC_LV: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(4),      KS_a,           KS_A,           KS_L7_amacron,  KS_L7_Amacron,
    kc(6),      KS_c,           KS_C,           KS_L7_ccaron,   KS_L7_Ccaron,
    kc(8),      KS_e,           KS_E,           KS_L7_emacron,  KS_L7_Emacron,
    kc(10),     KS_g,           KS_G,           KS_L7_gcedilla, KS_L7_Gcedilla,
    kc(12),     KS_i,           KS_I,           KS_L7_imacron,  KS_L7_Imacron,
    kc(14),     KS_k,           KS_K,           KS_L7_kcedilla, KS_L7_Kcedilla,
    kc(15),     KS_l,           KS_L,           KS_L7_lcedilla, KS_L7_Lcedilla,
    kc(17),     KS_n,           KS_N,           KS_L7_ncedilla, KS_L7_Ncedilla,
    kc(18),     KS_o,           KS_O,           KS_L7_omacron,  KS_L7_Omacron,
    kc(22),     KS_s,           KS_S,           KS_L7_scaron,   KS_L7_Scaron,
    kc(24),     KS_u,           KS_U,           KS_L7_umacron,  KS_L7_Umacron,
    kc(29),     KS_z,           KS_Z,           KS_L7_zcaron,   KS_L7_Zcaron,
    kc(230),    KS_Mode_switch, KS_Multi_key,
];

/// `ukbd_keydesc_nl`.
#[rustfmt::skip]
static UKBD_KEYDESC_NL: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(6),      KS_c,           KS_C,           KS_cent,
    kc(16),     KS_m,           KS_M,           KS_mu,
    kc(21),     KS_r,           KS_R,           KS_paragraph,
    kc(22),     KS_s,           KS_S,           KS_ssharp,
    kc(27),     KS_x,           KS_X,           KS_guillemotright,
    kc(29),     KS_z,           KS_Z,           KS_guillemotleft,
    kc(30),     KS_1,           KS_exclam,      KS_onesuperior,
    kc(31),     KS_2,           KS_quotedbl,    KS_twosuperior,
    kc(32),     KS_3,           KS_numbersign,  KS_threesuperior,
    kc(33),     KS_4,           KS_dollar,      KS_onequarter,
    kc(34),     KS_5,           KS_percent,     KS_onehalf,
    kc(35),     KS_6,           KS_ampersand,   KS_threequarters,
    kc(36),     KS_7,           KS_underscore,  KS_sterling,
    kc(37),     KS_8,           KS_parenleft,   KS_braceleft,
    kc(38),     KS_9,           KS_parenright,  KS_braceright,
    kc(39),     KS_0,           KS_apostrophe,
    kc(45),     KS_slash,       KS_question,    KS_backslash,
    kc(46),     KS_degree,      KS_dead_tilde,  KS_dead_cedilla,
    kc(47),     KS_dead_diaeresis,KS_dead_circumflex,
    kc(48),     KS_asterisk,    KS_bar,
    kc(49),     KS_less,        KS_greater,
    kc(50),     KS_less,        KS_greater,
    kc(51),     KS_plus,        KS_plusminus,
    kc(52),     KS_dead_acute,  KS_dead_grave,
    kc(53),     KS_at,          KS_section,     KS_notsign,
    kc(54),     KS_comma,       KS_semicolon,
    kc(55),     KS_period,      KS_colon,       KS_periodcentered,
    kc(56),     KS_minus,       KS_equal,
    kc(100),    KS_bracketright,KS_bracketleft, KS_brokenbar,
    kc(230),    KS_Mode_switch, KS_Multi_key,
];

/// `ukbd_keydesc_nl_nodead`.
#[rustfmt::skip]
static UKBD_KEYDESC_NL_NODEAD: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(46),     KS_degree,      KS_asciitilde,  KS_cedilla,
    kc(47),     KS_quotedbl,    KS_asciicircum,
    kc(52),     KS_apostrophe,  KS_grave,
];

/// `ukbd_keydesc_is`.
#[rustfmt::skip]
static UKBD_KEYDESC_IS: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
                                                // euro currency
    kc(8),      KS_e,           KS_E,
    kc(20),     KS_q,           KS_Q,           KS_at,
    kc(31),     KS_2,           KS_quotedbl,
    kc(35),     KS_6,           KS_ampersand,
    kc(36),     KS_7,           KS_slash,       KS_braceleft,
    kc(37),     KS_8,           KS_parenleft,   KS_bracketleft,
    kc(38),     KS_9,           KS_parenright,  KS_bracketright,
    kc(39),     KS_0,           KS_equal,       KS_braceright,
    kc(45),     KS_odiaeresis,  KS_Odiaeresis,  KS_backslash,
    kc(46),     KS_minus,       KS_underscore,
    kc(47),     KS_eth,
    kc(48),     KS_apostrophe,  KS_question,    KS_asciitilde,
    kc(49),     KS_plus,        KS_asterisk,    KS_grave,
    kc(50),     KS_plus,        KS_asterisk,    KS_grave,
    kc(51),     KS_ae,
    kc(52),     KS_dead_acute,  KS_dead_diaeresis,KS_dead_circumflex,
    kc(53),     KS_degree,      KS_diaeresis,
    kc(54),     KS_comma,       KS_semicolon,
    kc(55),     KS_period,      KS_colon,
    kc(56),     KS_thorn,
    kc(100),    KS_less,        KS_greater,     KS_bar,
    kc(230),    KS_Mode_switch, KS_Multi_key,
];

/// `ukbd_keydesc_is_nodead`.
#[rustfmt::skip]
static UKBD_KEYDESC_IS_NODEAD: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(52),     KS_acute,       KS_diaeresis,   KS_asciicircum,
];

/// `ukbd_keydesc_ee`.
#[rustfmt::skip]
static UKBD_KEYDESC_EE: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(22),     KS_s,           KS_S,           KS_L2_scaron,   KS_L2_Scaron,
    kc(29),     KS_z,           KS_Z,           KS_L2_zcaron,   KS_L2_Zcaron,
    kc(31),     KS_2,           KS_quotedbl,    KS_at,
    kc(32),     KS_3,           KS_numbersign,  KS_sterling,
    kc(33),     KS_4,           KS_currency,    KS_dollar,
    kc(35),     KS_6,           KS_ampersand,
    kc(36),     KS_7,           KS_slash,       KS_braceleft,
    kc(37),     KS_8,           KS_parenleft,   KS_bracketleft,
    kc(38),     KS_9,           KS_parenright,  KS_bracketright,
    kc(39),     KS_0,           KS_equal,       KS_braceright,
    kc(45),     KS_plus,        KS_question,    KS_backslash,
    kc(46),     KS_dead_acute,  KS_dead_grave,
    kc(47),     KS_udiaeresis,
    kc(48),     KS_otilde,      KS_Otilde,      KS_section,
    kc(49),     KS_apostrophe,  KS_asterisk,    KS_onehalf,
    kc(50),     KS_apostrophe,  KS_asterisk,    KS_onehalf,
    kc(51),     KS_odiaeresis,
    kc(52),     KS_adiaeresis,  KS_Adiaeresis,  KS_dead_circumflex,
    kc(53),     KS_dead_caron,  KS_dead_tilde,
    kc(54),     KS_comma,       KS_semicolon,
    kc(55),     KS_period,      KS_colon,
    kc(56),     KS_minus,       KS_underscore,
    kc(100),    KS_less,        KS_greater,     KS_bar,         KS_brokenbar,
    kc(230),    KS_Mode_switch, KS_Multi_key,
];

/// `ukbd_keydesc_ee_nodead`.
#[rustfmt::skip]
static UKBD_KEYDESC_EE_NODEAD: &[KeysymT] = &[
    // pos      normal             shifted         altgr           shift-altgr
    kc(46),     KS_apostrophe,  KS_grave,
    kc(52),     KS_adiaeresis,  KS_Adiaeresis,  KS_asciicircum,
    kc(53),     KS_L2_caron,    KS_asciitilde,
];

// #endif  /* WSKBD_NO_INTL_LAYOUTS */

/// `ukbd_keydesctab`: the layouts of a USB keyboard, each the keymap of an encoding or a
/// variant over its base (the C's `{0, 0, 0, 0}` terminator is the end of the slice).
pub static UKBD_KEYDESCTAB: [WsconsKeydesc; 55] = [
    kbd_map(KB_US, 0, UKBD_KEYDESC_US),
    // #if !defined(WSKBD_NO_INTL_LAYOUTS)
    kbd_map(KB_DE, KB_US, UKBD_KEYDESC_DE),
    kbd_map(KB_DE | KB_APPLE, KB_DE, UKBD_KEYDESC_DE_APPLE),
    kbd_map(KB_DE | KB_NODEAD, KB_DE, UKBD_KEYDESC_DE_NODEAD),
    kbd_map(KB_DE | KB_APPLE | KB_NODEAD, KB_DE | KB_APPLE, UKBD_KEYDESC_DE_NODEAD),
    kbd_map(KB_FR, KB_US, UKBD_KEYDESC_FR),
    kbd_map(KB_FR | KB_APPLE, KB_FR, UKBD_KEYDESC_FR_APPLE),
    kbd_map(KB_FR | KB_DVORAK, KB_US, UKBD_KEYDESC_FR_DVORAK_BEPO),
    kbd_map(KB_DK, KB_US, UKBD_KEYDESC_DK),
    kbd_map(KB_DK | KB_NODEAD, KB_DK, UKBD_KEYDESC_DK_NODEAD),
    kbd_map(KB_IT, KB_US, UKBD_KEYDESC_IT),
    kbd_map(KB_UK, KB_US, UKBD_KEYDESC_UK),
    kbd_map(KB_JP, KB_US, UKBD_KEYDESC_JP),
    kbd_map(KB_SV, KB_DK, UKBD_KEYDESC_SV),
    kbd_map(KB_SV | KB_NODEAD, KB_SV, UKBD_KEYDESC_SV_NODEAD),
    kbd_map(KB_NO, KB_DK, UKBD_KEYDESC_NO),
    kbd_map(KB_NO | KB_NODEAD, KB_NO, UKBD_KEYDESC_NO_NODEAD),
    kbd_map(KB_US | KB_DVORAK, KB_US, UKBD_KEYDESC_US_DVORAK),
    kbd_map(KB_US | KB_COLEMAK, KB_US, UKBD_KEYDESC_US_COLEMAK),
    kbd_map(KB_US | KB_SWAPCTRLCAPS, KB_US, UKBD_KEYDESC_SWAPCTRLCAPS),
    kbd_map(KB_UK | KB_SWAPCTRLCAPS, KB_UK, UKBD_KEYDESC_SWAPCTRLCAPS),
    kbd_map(KB_JP | KB_SWAPCTRLCAPS, KB_JP, UKBD_KEYDESC_SWAPCTRLCAPS),
    kbd_map(KB_FR | KB_SWAPCTRLCAPS, KB_FR, UKBD_KEYDESC_SWAPCTRLCAPS),
    kbd_map(KB_FR | KB_APPLE | KB_SWAPCTRLCAPS, KB_FR | KB_APPLE, UKBD_KEYDESC_SWAPCTRLCAPS),
    kbd_map(KB_FR | KB_DVORAK | KB_SWAPCTRLCAPS, KB_FR | KB_DVORAK, UKBD_KEYDESC_SWAPCTRLCAPS),
    kbd_map(KB_BE | KB_SWAPCTRLCAPS, KB_BE, UKBD_KEYDESC_SWAPCTRLCAPS),
    kbd_map(KB_US | KB_DVORAK | KB_SWAPCTRLCAPS, KB_US | KB_DVORAK, UKBD_KEYDESC_SWAPCTRLCAPS),
    kbd_map(KB_US | KB_COLEMAK | KB_SWAPCTRLCAPS, KB_US | KB_COLEMAK, UKBD_KEYDESC_SWAPCTRLCAPS),
    kbd_map(KB_ES, KB_US, UKBD_KEYDESC_ES),
    kbd_map(KB_BE, KB_US, UKBD_KEYDESC_BE),
    kbd_map(KB_RU, KB_US, UKBD_KEYDESC_RU),
    kbd_map(KB_UA, KB_US, UKBD_KEYDESC_UA),
    kbd_map(KB_SG, KB_US, UKBD_KEYDESC_SG),
    kbd_map(KB_SG | KB_NODEAD, KB_SG, UKBD_KEYDESC_SG_NODEAD),
    kbd_map(KB_SF, KB_SG, UKBD_KEYDESC_SF),
    kbd_map(KB_SF | KB_NODEAD, KB_SF, UKBD_KEYDESC_SG_NODEAD),
    kbd_map(KB_PT, KB_US, UKBD_KEYDESC_PT),
    kbd_map(KB_PT | KB_APPLE, KB_PT, UKBD_KEYDESC_PT_APPLE),
    kbd_map(KB_LT, KB_US, UKBD_KEYDESC_LT),
    kbd_map(KB_LA, KB_US, UKBD_KEYDESC_LA),
    kbd_map(KB_BR, KB_US, UKBD_KEYDESC_BR),
    kbd_map(KB_TR, KB_US, UKBD_KEYDESC_TR),
    kbd_map(KB_TR | KB_NODEAD, KB_TR, UKBD_KEYDESC_TR_NODEAD),
    kbd_map(KB_PL, KB_US, UKBD_KEYDESC_PL),
    kbd_map(KB_HU, KB_US, UKBD_KEYDESC_HU),
    kbd_map(KB_SI, KB_US, UKBD_KEYDESC_SI),
    kbd_map(KB_CF, KB_US, UKBD_KEYDESC_CF),
    kbd_map(KB_CF | KB_NODEAD, KB_CF, UKBD_KEYDESC_CF_NODEAD),
    kbd_map(KB_LV, KB_US, UKBD_KEYDESC_LV),
    kbd_map(KB_NL, KB_US, UKBD_KEYDESC_NL),
    kbd_map(KB_NL | KB_NODEAD, KB_NL, UKBD_KEYDESC_NL_NODEAD),
    kbd_map(KB_IS, KB_US, UKBD_KEYDESC_IS),
    kbd_map(KB_IS | KB_NODEAD, KB_IS, UKBD_KEYDESC_IS_NODEAD),
    kbd_map(KB_EE, KB_US, UKBD_KEYDESC_EE),
    kbd_map(KB_EE | KB_NODEAD, KB_EE, UKBD_KEYDESC_EE_NODEAD),
    // #endif  /* WSKBD_NO_INTL_LAYOUTS */
];
/* </CODE> */

/* <TESTS> */
#[cfg(test)]
mod tests {
// Host tests of the layout tables: their shape, and (reference-backed) every keysym of every
// table against the generated C.

use std::collections::BTreeMap;
use std::string::{String, ToString};
use std::vec::Vec;

use super::*;

/// Whether `k` is a key code (`KS_GROUP_Keycode`).
fn is_kc(k: KeysymT) -> bool {
    ks_group(u32::from(k)) == KS_GROUP_Keycode
}

#[test]
fn tables_are_entries_of_a_key_code_and_at_most_four_keysyms() {
    for kd in &UKBD_KEYDESCTAB {
        assert_eq!(kd.map_size as usize, kd.map.len());
        assert!(kd.map_size > 0);
        assert!(is_kc(kd.map[0]), "layout {:#x} starts with a key code", kd.name);
        let mut n = 0;
        for &k in &kd.map[1..] {
            if is_kc(k) {
                n = 0;
            } else {
                n += 1;
                assert!(n <= 5, "layout {:#x}: command + four keysyms at most", kd.name);
            }
        }
    }
}

#[test]
fn every_base_is_a_layout_and_names_are_unique() {
    let names: Vec<u32> = UKBD_KEYDESCTAB.iter().map(|k| k.name).collect();
    for (i, kd) in UKBD_KEYDESCTAB.iter().enumerate() {
        assert!(!names[..i].contains(&kd.name), "{:#x} twice", kd.name);
        assert!(kd.base == 0 || names.contains(&kd.base), "{:#x}", kd.base);
    }
    assert_eq!(UKBD_KEYDESCTAB[0].name, KB_US);
    assert_eq!(UKBD_KEYDESCTAB[0].base, 0);
    assert_eq!(kc(4), 0xe004);
}

/// The tokens of a C initialiser body: `KC(n)` and keysym names, comments dropped.
fn c_tokens(body: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut s = body;
    while let Some(i) = s.find("/*") {
        let j = s[i..].find("*/").map_or(s.len(), |j| i + j + 2);
        out.extend(tokens_of(&s[..i]));
        s = &s[j..];
    }
    out.extend(tokens_of(s));
    out
}

fn tokens_of(s: &str) -> Vec<String> {
    s.split(',')
        .map(str::trim)
        .filter(|t| !t.is_empty())
        .map(String::from)
        .collect()
}

/// Every table and the layout list against `ukbdmap.c`: the same keysyms, keysym by keysym,
/// with `KS_*` and `KB_*` evaluated from `wsksymdef.h`.
#[test]
#[ignore = "needs OPENBSD_SRC"]
fn tables_match_the_c() {
    let path = crate::reftest::openbsd_src().join("sys/dev/usb/ukbdmap.c");
    let text = std::fs::read_to_string(path).unwrap();
    let defs = crate::reftest::defines("sys/dev/wscons/wsksymdef.h");
    let val = |tok: &str| -> u32 {
        if let Some(n) = tok.strip_prefix("KC(").and_then(|t| t.strip_suffix(')')) {
            return ks_keycode(n.parse().unwrap());
        }
        let mut v = 0;
        for part in tok.split('|') {
            let part = part.trim();
            v |= if part == "0" {
                0
            } else {
                crate::reftest::int(&defs, part).unwrap_or_else(|| panic!("{part}")) as u32
            };
        }
        v
    };

    // The arrays, by name.
    let mut tables: BTreeMap<String, Vec<u32>> = BTreeMap::new();
    let mut rest = &text[..];
    while let Some(i) = rest.find("static const keysym_t ") {
        let after = &rest[i + "static const keysym_t ".len()..];
        let name = &after[..after.find('[').unwrap()];
        let open = after.find('{').unwrap();
        let close = after.find("};").unwrap();
        let body = &after[open + 1..close];
        tables.insert(name.into(), c_tokens(body).iter().map(|t| val(t)).collect());
        rest = &after[close..];
    }
    assert_eq!(tables.len(), 45);

    // The layout list.
    let start = text.find("ukbd_keydesctab[] = {").unwrap();
    let list = &text[start..start + text[start..].find("};").unwrap()];
    let mut entries = Vec::new();
    for chunk in list.split("KBD_MAP(").skip(1) {
        let args = &chunk[..chunk.find(')').unwrap()];
        let args: Vec<&str> = args.split(',').map(str::trim).collect();
        entries.push((val(args[0]), val(args[1]), args[2].to_string()));
    }
    assert_eq!(entries.len(), UKBD_KEYDESCTAB.len());
    for ((name, base, map), kd) in entries.iter().zip(&UKBD_KEYDESCTAB) {
        assert_eq!((kd.name, kd.base), (*name, *base), "{map}");
        let ours: Vec<u32> = kd.map.iter().map(|&k| u32::from(k)).collect();
        assert_eq!(&ours, &tables[map], "{map}");
    }
}
}
/* </TESTS> */
