/*	$OpenBSD: efi_machdep.c,v 1.6 2023/01/14 12:11:11 kettenis Exp $	*/
/* <LICENSES> */
/*
 * Copyright (c) 2026 Emilio Navarrete Lineros <enavarre@outlook.com>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

/*
 * Copyright (c) 2017 Mark Kettenis <kettenis@openbsd.org>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
/* </LICENSES> */

/* <CODE> */
//! efi(4) on arm64: the UEFI runtime services, mapped into a pmap of their own, and the
//! time-of-day clock they provide (`GetTime`/`SetTime`). Under QEMU with EDK2 this is the
//! machine's clock: the firmware keeps the PL031 for itself and disables its device-tree node,
//! so plrtc(4) does not attach.
//!
//! Upstream: sys/arch/arm64/dev/efi_machdep.c @ 3ce1f3f79392
//!
//! ## Deviations
//! - The system table's address and the memory map come from the boot protocol through
//!   `machdep.rs` (`SYSTEM_TABLE`, `efi_mmap`, `MMAP_DESC_SIZE`) instead of efiboot's
//!   `openbsd,uefi-*` properties in `/chosen`.
//! - `efi_enter_check` (a `setjmp` on `efi_jmpbuf`) and the runtime-service call that follows
//!   it are `efi_call`: an assembly trampoline (`efi_rs_call`) saves the callee-saved
//!   registers, the stack pointer and the return address in `efi_jmpbuf`, loads the service
//!   from its slot of the runtime services table (so that load is covered too, as in C) and
//!   calls it; `efi_fault`, the `pcb_onfault` target, restores them and returns "faulted",
//!   which `efi_call` turns into `efi_leave` and `EFAULT`. A fault outside such a call (the
//!   `FirmwareVendor` and configuration-table reads of `efi_attach`) returns through
//!   whatever `efi_jmpbuf` holds, as the C's `longjmp` does.
//! - `pmap_create` makes a three-level pmap and the C then sets `have_4_level_pt`, so the
//!   union `pm_vp` reads the same table as level 0; here `pm_vp` is an enum
//!   (`include/pmap.rs`, deviations), switched to `PmVp::L0` over the same table.
//! - The chip handle is `malloc`ed (`include/efivar.rs`, deviations).
//! - `efi_cd` (generated by `config(8)` in C, used by `dev/efi/efi.c`) is defined here.
//! - The `smbios` attach arguments carry the parent's node, DMA tag and cells where the C
//!   leaves them uninitialised; no smbios(4) driver is configured.
//! - A memory map without a descriptor size maps nothing (the C would divide by zero).

use core::arch::global_asm;
use core::cell::UnsafeCell;
use core::ffi::c_void;
use core::mem::offset_of;
use core::ptr;
use core::sync::atomic::{AtomicU64, Ordering};

use crate::arch::arm64::arm64::cpufunc::cpu_setttb;
use crate::arch::arm64::arm64::fpu::{fpu_kernel_enter, fpu_kernel_exit};
use crate::arch::arm64::arm64::machdep::{MMAP_DESC_SIZE, SYSTEM_TABLE, efi_mmap};
use crate::arch::arm64::arm64::pmap::{pmap_create, pmap_enter, pmap_kernel};
use crate::arch::arm64::include::_types::Label;
use crate::arch::arm64::include::armreg::{read_specialreg, tcr_t0sz, write_specialreg};
use crate::arch::arm64::include::bus::{BUS_SPACE_MAP_CACHEABLE, BUS_SPACE_MAP_LINEAR};
use crate::arch::arm64::include::cpu::{curcpu, intr_disable, intr_restore};
use crate::arch::arm64::include::efivar::EfiSoftc;
use crate::arch::arm64::include::fdt::FdtAttachArgs;
use crate::arch::arm64::include::param::PAGE_SIZE;
use crate::arch::arm64::include::pmap::{PMAP_DEVICE, PmVp};
use crate::arch::arm64::include::vmparam::USER_SPACE_BITS;
use crate::dev::clock_subr::TodrChipHandle;
use crate::dev::efi::efi::{
    EFI_ACPI_20_TABLE_GUID, EFI_MEMORY_RO, EFI_MEMORY_RP, EFI_MEMORY_RUNTIME, EFI_MEMORY_WB,
    EFI_MEMORY_XP, EFI_SUCCESS, EfiConfigurationTable, EfiMemoryDescriptor, EfiRuntimeServices,
    EfiRuntimeServicesCode, EfiStatus, EfiSystemTable, EfiTime, SMBIOS_TABLE_GUID,
    SMBIOS3_TABLE_GUID, efi_guidcmp,
};
use crate::dev::ofw::fdt::FdtReg;
use crate::kassert;
use crate::kern::clock_subr::{clock_secs_to_ymdhms, clock_ymdhms_to_secs};
use crate::kern::kern_malloc::malloc;
use crate::kern::kern_time::todr_attach;
use crate::kern::subr_autoconf::config_found;
use crate::kern::subr_prf::{Str, panic, printf};
use crate::machine::bus::bus_space_map;
use crate::sys::device::{CfMatch, Cfattach, Cfdriver, DV_DULL, Device};
use crate::sys::errno::Errno;
use crate::sys::malloc::{M_DEVBUF, M_NOWAIT, M_ZERO};
use crate::sys::mman::{PROT_EXEC, PROT_READ, PROT_WRITE};
use crate::sys::time::{ClockYmdhms, POSIX_BASE_YEAR, Timeval};
use crate::sys::types::{Paddr, Vaddr};
use crate::uvm::uvm_pmap::PMAP_WIRED;

/// `EFI_SPACE_BITS`: we need a large address space to allow identity mapping of physical
/// memory on some machines.
const EFI_SPACE_BITS: u64 = 48;

/// `label_t efi_jmpbuf`: where `efi_rs_call` saves the registers `efi_fault` restores.
#[repr(transparent)]
pub struct EfiJmpbuf(UnsafeCell<Label>);

// SAFETY: only written by `efi_rs_call` and read by `efi_fault`, on the CPU that runs a
// runtime service with interrupts disabled (`efi_enter`).
unsafe impl Sync for EfiJmpbuf {}

/// What `efi_rs_call` returns: the service's status, and whether `efi_fault` cut it short.
#[repr(C)]
struct EfiCallResult {
    /// The service's `EFI_STATUS` (0 when it faulted).
    status: u64,
    /// 1 when the call faulted.
    faulted: u64,
}

/// `efi_acpi_table`: the ACPI 2.0 table's address, 0 if the firmware has none.
pub static EFI_ACPI_TABLE: AtomicU64 = AtomicU64::new(0);
/// `efi_smbios_table`: the SMBIOS (or SMBIOS 3) table's address, 0 if none.
pub static EFI_SMBIOS_TABLE: AtomicU64 = AtomicU64::new(0);

/// `efi_ca`.
pub static EFI_CA: Cfattach = Cfattach {
    ca_devsize: size_of::<EfiSoftc>(),
    ca_match: Some(efi_match),
    ca_attach: efi_attach,
    ca_detach: None,
    ca_activate: None,
};

/// `efi_cd` (see the module's deviations).
pub static EFI_CD: Cfdriver = Cfdriver::new(b"efi", DV_DULL, 0);

/// `efi_jmpbuf`.
pub static EFI_JMPBUF: EfiJmpbuf = EfiJmpbuf(UnsafeCell::new(Label { val: [0; 13] }));

// efi_rs_call(slot, a0, a1, label): saves x19-x30 and sp in `label`, then calls the
// function whose address is at `slot` with (a0, a1). efi_fault: the pcb_onfault target,
// restores them from efi_jmpbuf and returns { 0, 1 } from efi_rs_call.
global_asm!(
    ".text",
    ".balign 4",
    ".global efi_rs_call",
    ".type efi_rs_call, %function",
    "efi_rs_call:",
    "    mov x9, sp",
    "    stp x19, x20, [x3, #0]",
    "    stp x21, x22, [x3, #16]",
    "    stp x23, x24, [x3, #32]",
    "    stp x25, x26, [x3, #48]",
    "    stp x27, x28, [x3, #64]",
    "    stp x29, x30, [x3, #80]",
    "    str x9, [x3, #96]",
    "    stp x29, x30, [sp, #-16]!",
    "    mov x29, sp",
    "    ldr x16, [x0]",
    "    mov x0, x1",
    "    mov x1, x2",
    "    blr x16",
    "    mov x1, #0",
    "    ldp x29, x30, [sp], #16",
    "    ret",
    ".size efi_rs_call, . - efi_rs_call",
    "",
    ".global efi_fault",
    ".type efi_fault, %function",
    "efi_fault:",
    "    adrp x3, {jmpbuf}",
    "    add x3, x3, :lo12:{jmpbuf}",
    "    ldp x19, x20, [x3, #0]",
    "    ldp x21, x22, [x3, #16]",
    "    ldp x23, x24, [x3, #32]",
    "    ldp x25, x26, [x3, #48]",
    "    ldp x27, x28, [x3, #64]",
    "    ldp x29, x30, [x3, #80]",
    "    ldr x9, [x3, #96]",
    "    mov sp, x9",
    "    mov x0, #0",
    "    mov x1, #1",
    "    ret",
    ".size efi_fault, . - efi_fault",
    jmpbuf = sym EFI_JMPBUF,
);

unsafe extern "C" {
    /// See the `global_asm!` above.
    fn efi_rs_call(slot: usize, a0: usize, a1: usize, label: *mut Label) -> EfiCallResult;
    /// `efi_fault`: `longjmp(&efi_jmpbuf)`, as a `pcb_onfault` target.
    fn efi_fault();
}

/// `(struct efi_softc *)self`.
fn softc(dev: &Device) -> &'static EfiSoftc {
    // SAFETY: `efi_ca` makes `EfiSoftc`s; `config_make_softc`'s allocation lives as long as
    // the device, which is never detached.
    unsafe { &*ptr::from_ref(dev.softc::<EfiSoftc>()) }
}

/// `efi_match`: the `efi` pseudo-node mainbus offers when booted through UEFI.
pub fn efi_match(_parent: Option<&Device>, _match: &CfMatch, aux: *mut c_void) -> i32 {
    // SAFETY: mainbus hands its children `struct fdt_attach_args`.
    let faa = unsafe { &*aux.cast::<FdtAttachArgs<'_>>() };

    i32::from(faa.fa_name == b"efi")
}

/// `efi_attach`.
pub fn efi_attach(_parent: Option<&Device>, self_: &Device, aux: *mut c_void) {
    let sc = softc(self_);
    // SAFETY: as in `efi_match`.
    let faa = unsafe { &*aux.cast::<FdtAttachArgs<'_>>() };

    let system_table = SYSTEM_TABLE.load(Ordering::Relaxed);
    kassert!(system_table != 0);

    // SAFETY: the firmware's system table, read-only memory nothing else maps.
    let ioh = match unsafe {
        bus_space_map(
            faa.fa_iot,
            system_table as usize,
            size_of::<EfiSystemTable>(),
            BUS_SPACE_MAP_LINEAR | BUS_SPACE_MAP_CACHEABLE,
        )
    } {
        Ok(ioh) => ioh,
        Err(_) => {
            printf(format_args!(": can't map system table\n"));
            return;
        }
    };

    let stp = (faa.fa_iot._space_vaddr)(faa.fa_iot, ioh).cast::<EfiSystemTable>();
    // SAFETY: the mapping above covers the whole table, in write-back memory the firmware
    // no longer changes.
    let st = unsafe { &*stp };
    sc.sc_rs.set(st.RuntimeServices);

    let major = st.Hdr.Revision >> 16;
    let minor = st.Hdr.Revision & 0xffff;
    printf(format_args!(": UEFI {}.{}", major, minor / 10));
    if minor % 10 != 0 {
        printf(format_args!(".{}", minor % 10));
    }
    printf(format_args!("\n"));

    // Early implementations can be buggy.
    if major < 2 || (major == 2 && minor < 10) {
        return;
    }

    efi_map_runtime(sc);

    // Activate our pmap such that we can access the FirmwareVendor and ConfigurationTable
    // fields.
    efi_enter(sc);
    if !st.FirmwareVendor.is_null() {
        printf(format_args!("{}: ", Str(&sc.sc_dev.dv_xname.get())));
        let mut i = 0;
        loop {
            // SAFETY: a NUL-terminated string of the runtime memory `sc_pm` maps at its
            // physical address, which is active between efi_enter and efi_leave.
            let c = unsafe { ptr::read_volatile(st.FirmwareVendor.add(i)) };
            if c == 0 {
                break;
            }
            printf(format_args!("{}", char::from(c as u8)));
            i += 1;
        }
        printf(format_args!(" rev 0x{:x}\n", st.FirmwareRevision));
    }
    for i in 0..st.NumberOfTableEntries {
        // SAFETY: `NumberOfTableEntries` entries of runtime memory, mapped as above.
        let ct: EfiConfigurationTable = unsafe { ptr::read_volatile(st.ConfigurationTable.add(i)) };

        if efi_guidcmp(&EFI_ACPI_20_TABLE_GUID, &ct.VendorGuid) {
            EFI_ACPI_TABLE.store(ct.VendorTable as u64, Ordering::Relaxed);
        }
        if efi_guidcmp(&SMBIOS_TABLE_GUID, &ct.VendorGuid) {
            EFI_SMBIOS_TABLE.store(ct.VendorTable as u64, Ordering::Relaxed);
        }
        if efi_guidcmp(&SMBIOS3_TABLE_GUID, &ct.VendorGuid) {
            EFI_SMBIOS_TABLE.store(ct.VendorTable as u64, Ordering::Relaxed);
        }
    }
    efi_leave(sc);

    let smbios = EFI_SMBIOS_TABLE.load(Ordering::Relaxed);
    if smbios != 0 {
        let reg = [FdtReg {
            addr: smbios,
            size: 0,
        }];
        let mut fa = FdtAttachArgs {
            fa_name: b"smbios",
            fa_node: 0,
            fa_iot: faa.fa_iot,
            fa_dmat: faa.fa_dmat,
            fa_reg: &reg,
            fa_intr: &[],
            fa_acells: faa.fa_acells,
            fa_scells: faa.fa_scells,
        };
        let _ = config_found(self_, ptr::from_mut(&mut fa).cast(), None);
    }

    let mut time = EfiTime::default();
    let status = match efi_call(
        sc,
        offset_of!(EfiRuntimeServices, GetTime),
        ptr::from_mut(&mut time) as usize,
        0,
    ) {
        Ok(status) => status,
        Err(_) => return,
    };
    if status != EFI_SUCCESS {
        return;
    }

    // EDK II implementations provide an implementation of GetTime() that returns a fixed
    // compiled-in time on hardware without a (supported) RTC.  So only use this interface
    // as a last resort.
    let Some(mem) = malloc(size_of::<TodrChipHandle>(), M_DEVBUF, M_NOWAIT | M_ZERO) else {
        panic(format_args!("couldn't allocate todr_handle"));
    };
    let handle = mem.cast::<TodrChipHandle>().as_ptr();
    // SAFETY: a fresh allocation of the handle's size, malloc(9)-aligned, never freed: it
    // becomes `&'static`.
    let handle: &'static TodrChipHandle = unsafe {
        ptr::write(
            handle,
            TodrChipHandle {
                cookie: ptr::from_ref(sc).cast_mut().cast::<c_void>(),
                bus_cookie: ptr::null_mut(),
                todr_quality: -1000,
                todr_gettime: efi_gettime,
                todr_settime: efi_settime,
                todr_setwen: None,
            },
        );
        &*handle
    };
    sc.sc_todr.set(handle);
    todr_attach(handle);
}

/// `efi_map_runtime`: we don't really want some random executable non-OpenBSD code lying
/// around in kernel space.  So create a separate pmap and only activate it when we call
/// runtime services.
pub fn efi_map_runtime(sc: &EfiSoftc) {
    let pm = pmap_create();
    pm.pm_privileged.set(true);
    pm.have_4_level_pt.set(true);
    // The union pm_vp: the table pmap_create made is now read as level 0.
    if let PmVp::L1(l1) = pm.pm_vp.get() {
        pm.pm_vp.set(PmVp::L0(l1.cast()));
    }
    sc.sc_pm.set(pm);

    let map = efi_mmap();
    let desc_size = MMAP_DESC_SIZE.load(Ordering::Relaxed) as usize;
    if desc_size == 0 {
        return;
    }

    for i in 0..map.len() / desc_size {
        let Some(desc) = EfiMemoryDescriptor::read_at(map, i * desc_size) else {
            break;
        };
        if desc.Attribute & EFI_MEMORY_RUNTIME == 0 {
            continue;
        }

        let mut va = desc.VirtualStart as usize;
        let mut pa = desc.PhysicalStart as usize;
        let mut prot = PROT_READ | PROT_WRITE;

        // If the virtual address is still zero, use an identity mapping.
        if va == 0 {
            va = pa;
        }

        // Normal memory is expected to be "write back" cacheable.  Everything else is
        // mapped as device memory.
        if desc.Attribute & EFI_MEMORY_WB == 0 {
            pa |= PMAP_DEVICE as usize;
        }

        // Only make pages marked as runtime service code executable.  This violates the
        // standard but it seems we can get away with it.
        if desc.Type == EfiRuntimeServicesCode {
            prot |= PROT_EXEC;
        }

        if desc.Attribute & EFI_MEMORY_RP != 0 {
            prot &= !PROT_READ;
        }
        if desc.Attribute & EFI_MEMORY_XP != 0 {
            prot &= !PROT_EXEC;
        }
        if desc.Attribute & EFI_MEMORY_RO != 0 {
            prot &= !PROT_WRITE;
        }

        for _ in 0..desc.NumberOfPages {
            // A wired mapping without PMAP_CANFAIL: pmap_enter panics rather than fail.
            let _ = pmap_enter(pm, Vaddr::new(va), Paddr::new(pa), prot, prot | PMAP_WIRED);
            va += PAGE_SIZE;
            pa += PAGE_SIZE;
        }
    }
}

/// `efi_enter`: switches the lower half to the runtime services' pmap, with interrupts
/// disabled and the FPU usable, and arms `efi_fault`.
pub fn efi_enter(sc: &EfiSoftc) {
    // SAFETY: `sc_pm` is the pmap `efi_map_runtime` made, never destroyed.
    let pm = unsafe { &*sc.sc_pm.get() };

    sc.sc_psw.set(intr_disable());
    // SAFETY: the kernel runs in the upper half (TTBR1); the lower half goes to the kernel's
    // empty table while its walk is widened, then to the runtime services' level-0 table,
    // with interrupts disabled until efi_leave puts the current pmap back.
    unsafe {
        write_specialreg!("ttbr0_el1", pmap_kernel().pm_pt0pa.get());
        core::arch::asm!("isb", options(nomem, nostack, preserves_flags));
    }
    let mut tcr = read_specialreg!("tcr_el1");
    tcr &= !tcr_t0sz(0x3f);
    tcr |= tcr_t0sz(64 - EFI_SPACE_BITS);
    // SAFETY: as above.
    unsafe {
        write_specialreg!("tcr_el1", tcr);
        cpu_setttb(pm.pm_asid.load(Ordering::Relaxed), pm.pm_pt0pa.get());
    }

    fpu_kernel_enter();

    // SAFETY: `ci_curpcb` is the running thread's pcb, alive while it runs.
    if let Some(pcb) = unsafe { curcpu().ci_curpcb.get().as_ref() } {
        pcb.pcb_onfault.set(efi_fault as *const () as usize);
    }
}

/// `efi_leave`: undoes `efi_enter`.
pub fn efi_leave(sc: &EfiSoftc) {
    let ci = curcpu();
    // SAFETY: `ci_curpm` is the pmap the CPU ran on before efi_enter, alive while active.
    let pm = unsafe { &*ci.ci_curpm.get() };

    // SAFETY: as in `efi_enter`.
    if let Some(pcb) = unsafe { ci.ci_curpcb.get().as_ref() } {
        pcb.pcb_onfault.set(0);
    }

    fpu_kernel_exit();

    // SAFETY: as in `efi_enter`, back to the user address space width and the current pmap;
    // the interrupt state is the one efi_enter saved on this CPU.
    unsafe {
        write_specialreg!("ttbr0_el1", pmap_kernel().pm_pt0pa.get());
        core::arch::asm!("isb", options(nomem, nostack, preserves_flags));
    }
    let mut tcr = read_specialreg!("tcr_el1");
    tcr &= !tcr_t0sz(0x3f);
    tcr |= tcr_t0sz(64 - u64::from(USER_SPACE_BITS));
    // SAFETY: as above.
    unsafe {
        write_specialreg!("tcr_el1", tcr);
        cpu_setttb(pm.pm_asid.load(Ordering::Relaxed), pm.pm_pt0pa.get());
        intr_restore(sc.sc_psw.get());
    }
}

/// `efi_enter_check(sc)`, the runtime service at byte `slot` of the runtime services table
/// called with `(a0, a1)`, and `efi_leave(sc)`: the service's status, or `EFAULT` when it
/// faulted (see the module's deviations).
fn efi_call(sc: &EfiSoftc, slot: usize, a0: usize, a1: usize) -> Result<EfiStatus, Errno> {
    efi_enter(sc);
    // SAFETY: `sc_rs` is the firmware's runtime services table, mapped by `sc_pm`, which
    // efi_enter just activated; a fault in the load or the call comes back through
    // efi_fault, which efi_enter armed, with the registers efi_rs_call saved.
    let r = unsafe { efi_rs_call(sc.sc_rs.get() as usize + slot, a0, a1, EFI_JMPBUF.0.get()) };
    efi_leave(sc);
    if r.faulted != 0 {
        return Err(Errno::EFAULT);
    }
    Ok(r.status as EfiStatus)
}

/// The efi softc a chip handle's cookie names.
fn handle_softc(handle: &TodrChipHandle) -> &'static EfiSoftc {
    // SAFETY: efi_attach sets the cookie to its softc, which lives as long as the device.
    unsafe { &*handle.cookie.cast::<EfiSoftc>() }
}

/// `efi_gettime`.
pub fn efi_gettime(handle: &TodrChipHandle, tv: &mut Timeval) -> Result<(), Errno> {
    let sc = handle_softc(handle);
    let mut time = EfiTime::default();

    let status = efi_call(
        sc,
        offset_of!(EfiRuntimeServices, GetTime),
        ptr::from_mut(&mut time) as usize,
        0,
    )?;
    if status != EFI_SUCCESS {
        return Err(Errno::EIO);
    }

    let dt = ClockYmdhms {
        dt_year: time.Year,
        dt_mon: time.Month,
        dt_day: time.Day,
        dt_hour: time.Hour,
        dt_min: time.Minute,
        dt_sec: time.Second,
        ..ClockYmdhms::default()
    };

    if dt.dt_sec > 59
        || dt.dt_min > 59
        || dt.dt_hour > 23
        || dt.dt_day > 31
        || dt.dt_day == 0
        || dt.dt_mon > 12
        || dt.dt_mon == 0
        || i32::from(dt.dt_year) < POSIX_BASE_YEAR
    {
        return Err(Errno::EINVAL);
    }

    tv.tv_sec = clock_ymdhms_to_secs(&dt);
    tv.tv_usec = 0;
    Ok(())
}

/// `efi_settime`.
pub fn efi_settime(handle: &TodrChipHandle, tv: &mut Timeval) -> Result<(), Errno> {
    let sc = handle_softc(handle);

    let dt = clock_secs_to_ymdhms(tv.tv_sec);

    let mut time = EfiTime {
        Year: dt.dt_year,
        Month: dt.dt_mon,
        Day: dt.dt_day,
        Hour: dt.dt_hour,
        Minute: dt.dt_min,
        Second: dt.dt_sec,
        Nanosecond: 0,
        TimeZone: 0,
        Daylight: 0,
        ..EfiTime::default()
    };

    let status = efi_call(
        sc,
        offset_of!(EfiRuntimeServices, SetTime),
        ptr::from_mut(&mut time) as usize,
        0,
    )?;
    if status != EFI_SUCCESS {
        return Err(Errno::EIO);
    }
    Ok(())
}
/* </CODE> */
