/*	$OpenBSD: toeplitz.h,v 1.11 2023/05/17 10:22:17 dlg Exp $ */
/* $OpenBSD: toeplitz.c,v 1.11 2025/07/07 02:28:50 jsg Exp $ */
/* <LICENSES> */
/*
 * Copyright (c) 2026 Emilio Navarrete Lineros <enavarre@outlook.com>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

/*
 * Copyright (c) 2019 David Gwynne <dlg@openbsd.org>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
/*
 * Copyright (c) 2009 The DragonFly Project.  All rights reserved.
 *
 * This code is derived from software contributed to The DragonFly Project
 * by Sepherosa Ziehau <sepherosa@gmail.com>
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name of The DragonFly Project nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific, prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */
/*
 * Copyright (c) 2019 David Gwynne <dlg@openbsd.org>
 * Copyright (c) 2020 Theo Buehler <tb@openbsd.org>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
/* </LICENSES> */

/* <CODE> */
//! Symmetric Toeplitz hashing: `<net/toeplitz.h>` and `net/toeplitz.c`.
//!
//! Upstream: sys/net/toeplitz.h @ 3ce1f3f79392
//! Upstream: sys/net/toeplitz.c @ 3ce1f3f79392
//!
//! The Toeplitz hash of a 16-bit number, considered as a column vector over the field with two
//! elements, is a matrix multiplication with a 16x16 circulant Toeplitz matrix generated by a
//! 16-bit key. The hash is linear, so the hash of `a ^ b` is the hash of `a` xor the hash of
//! `b`, and a flow's addresses and ports are xor-ed together before hashing: both directions
//! of a flow hash to the same value (hence "symmetric"). The matrix is invertible exactly when
//! the key has odd parity, and the system key is drawn as such.
//!
//! [`StoeplitzCache`] holds the products of the key's first eight columns with every byte
//! value, so a 16-bit hash is two table lookups. The system cache, [`stoeplitz_cache`], is
//! filled by [`stoeplitz_init`] from `main()` and serves `pf`'s state hashing and the
//! receive-side scaling keys that drivers program into hardware ([`stoeplitz_to_key`]).
//!
//! Status: `toeplitz.h` `ported`, `toeplitz.c` `ported`.
//!
//! ## Deviations
//! - `const struct stoeplitz_cache *const stoeplitz_cache` (a pointer to the static
//!   `stoeplitz_syskey_cache`) is the function [`stoeplitz_cache`], returning
//!   `&'static StoeplitzCache` from a `StaticCell` that only [`stoeplitz_init`] writes, once,
//!   from `main()` on the boot CPU before any reader exists. `stoeplitz_keyseed` is an
//!   `AtomicU16`, under its C name (`docs/C_TO_RUST.md`: a global beside an uppercase constant
//!   of the same spelling, `STOEPLITZ_KEYSEED`).
//! - The macros `stoeplitz_n16(n)`, `stoeplitz_n32(n)`, `stoeplitz_h16(h)`,
//!   `stoeplitz_h32(h)`, `stoeplitz_h64(h)`, `stoeplitz_port(p)`, `stoeplitz_ip4(...)`,
//!   `stoeplitz_ip4port(...)`, `stoeplitz_ip6(...)`, `stoeplitz_ip6port(...)` and
//!   `stoeplitz_eaddr(ea)` are functions of the same names over the system cache.
//! - `stoeplitz_hash_ip6`, `stoeplitz_hash_ip6port` and their macros (C `#ifdef INET6`) are
//!   always compiled, not gated by the `inet6` feature: `sys/netinet6` compiles
//!   unconditionally and `in6_pcb.c`'s `in6_pcb_newflow` calls `stoeplitz_ip6port`. They take
//!   the sixteen bytes of each `struct in6_addr` (`&[u8; 16]`, the callers pass `s6_addr`);
//!   `s6_addr32[i]` is the native-order word at byte `4 * i`, as the C's union reads it.
//! - `stoeplitz_to_key(void *key, size_t klen)` takes `&mut [u8]`; its `KASSERT` is
//!   `kassert!`. `stoeplitz_hash_eaddr` takes `&[u8; 6]` and reads the C's `uint16_t *` view as
//!   native-order words.
//! - `stoeplitz_cache_init` computes the columns `skey << b | skey >> (NBSK - b)` as
//!   `skey.rotate_left(b)`: the C's shift by 16 for `b == 0` is defined only because `skey` is
//!   promoted to `int`, and the expression is a 16-bit rotation.
//! - `stoeplitz_hash_h16` keeps the C's two byte-order variants, chosen by
//!   `BYTE_ORDER == BIG_ENDIAN` (a constant, so the other arm compiles away).

use core::sync::atomic::{AtomicU16, Ordering};

use libkern::StaticCell;

use crate::dev::rnd::arc4random;
use crate::kassert;
use crate::sys::endian::{BIG_ENDIAN, BYTE_ORDER, htons, swap16};

/// `STOEPLITZ_KEYSEED`: the system key before [`stoeplitz_init`] draws a random one.
pub const STOEPLITZ_KEYSEED: StoeplitzKey = 0x6d5a;

/// `NBBY`: bits in a byte (`<sys/select.h>`'s, here for the cache's eight columns).
const NBBY: u32 = u8::BITS;

/// `stoeplitz_key`: the 16-bit key that generates the Toeplitz matrix.
pub type StoeplitzKey = u16;

/// `struct stoeplitz_cache`: the products of the key's first eight matrix columns with every
/// byte value.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct StoeplitzCache {
    /// `H * val` for each byte `val`.
    pub bytes: [u16; 256],
}

impl StoeplitzCache {
    /// An all-zero cache, as the C's static is before `stoeplitz_cache_init`.
    pub const fn new() -> Self {
        Self { bytes: [0; 256] }
    }
}

impl Default for StoeplitzCache {
    fn default() -> Self {
        Self::new()
    }
}

/// `stoeplitz_keyseed`: the system key, [`STOEPLITZ_KEYSEED`] until [`stoeplitz_init`].
#[allow(non_upper_case_globals)] // the C name; `STOEPLITZ_KEYSEED` is the constant
static stoeplitz_keyseed: AtomicU16 = AtomicU16::new(STOEPLITZ_KEYSEED);

/// `stoeplitz_syskey_cache`: the cache of the system key. Written only by [`stoeplitz_init`],
/// once, from `main()` on the boot CPU before any reader; read through [`stoeplitz_cache`].
static STOEPLITZ_SYSKEY_CACHE: StaticCell<StoeplitzCache> = StaticCell::new(StoeplitzCache::new());

/// `stoeplitz_cache_entry`: `H * byte`.
#[inline]
pub const fn stoeplitz_cache_entry(scache: &StoeplitzCache, byte: u8) -> u16 {
    scache.bytes[byte as usize]
}

/// `stoeplitz_hash_n16`: hashes a `u16` in network byte order.
#[inline]
pub const fn stoeplitz_hash_n16(scache: &StoeplitzCache, n16: u16) -> u16 {
    let hi = stoeplitz_cache_entry(scache, (n16 >> 8) as u8);
    let lo = stoeplitz_cache_entry(scache, n16 as u8);
    hi ^ swap16(lo)
}

/// `stoeplitz_hash_n32`: hashes a `u32` in network byte order (its two halves xor-ed).
#[inline]
pub const fn stoeplitz_hash_n32(scache: &StoeplitzCache, n32: u32) -> u16 {
    stoeplitz_hash_n16(scache, (n32 ^ (n32 >> 16)) as u16)
}

/// `stoeplitz_hash_h16`: hashes a `u16` in host byte order; the result is that of
/// [`stoeplitz_hash_n16`] on the value in network order.
#[inline]
pub const fn stoeplitz_hash_h16(scache: &StoeplitzCache, h16: u16) -> u16 {
    let lo = stoeplitz_cache_entry(scache, h16 as u8);
    let hi = stoeplitz_cache_entry(scache, (h16 >> 8) as u8);
    if BYTE_ORDER == BIG_ENDIAN {
        hi ^ swap16(lo)
    } else {
        swap16(hi) ^ lo
    }
}

/// `stoeplitz_hash_h32`: hashes a `u32` in host byte order.
#[inline]
pub const fn stoeplitz_hash_h32(scache: &StoeplitzCache, h32: u32) -> u16 {
    stoeplitz_hash_h16(scache, (h32 ^ (h32 >> 16)) as u16)
}

/// `stoeplitz_hash_h64`: hashes a `u64` in host byte order.
#[inline]
pub const fn stoeplitz_hash_h64(scache: &StoeplitzCache, h64: u64) -> u16 {
    stoeplitz_hash_h32(scache, (h64 ^ (h64 >> 32)) as u32)
}

/// `stoeplitz_cache`: the system cache, filled by [`stoeplitz_init`] at boot (all zeroes, so
/// every hash 0, before).
#[inline]
pub fn stoeplitz_cache() -> &'static StoeplitzCache {
    // SAFETY: the only `&mut` to the cell is taken by `stoeplitz_init`, which `main()` calls
    // once on the boot CPU before sockets, pf or any driver exist to call here.
    unsafe { STOEPLITZ_SYSKEY_CACHE.get() }
}

/// `stoeplitz_n16(n16)`: [`stoeplitz_hash_n16`] with the system cache.
#[inline]
pub fn stoeplitz_n16(n16: u16) -> u16 {
    stoeplitz_hash_n16(stoeplitz_cache(), n16)
}

/// `stoeplitz_n32(n32)`: [`stoeplitz_hash_n32`] with the system cache.
#[inline]
pub fn stoeplitz_n32(n32: u32) -> u16 {
    stoeplitz_hash_n32(stoeplitz_cache(), n32)
}

/// `stoeplitz_h16(h16)`: [`stoeplitz_hash_h16`] with the system cache.
#[inline]
pub fn stoeplitz_h16(h16: u16) -> u16 {
    stoeplitz_hash_h16(stoeplitz_cache(), h16)
}

/// `stoeplitz_h32(h32)`: [`stoeplitz_hash_h32`] with the system cache.
#[inline]
pub fn stoeplitz_h32(h32: u32) -> u16 {
    stoeplitz_hash_h32(stoeplitz_cache(), h32)
}

/// `stoeplitz_h64(h64)`: [`stoeplitz_hash_h64`] with the system cache.
#[inline]
pub fn stoeplitz_h64(h64: u64) -> u16 {
    stoeplitz_hash_h64(stoeplitz_cache(), h64)
}

/// `stoeplitz_port(p)`: hashes a port in network byte order.
#[inline]
pub fn stoeplitz_port(p: u16) -> u16 {
    stoeplitz_n16(p)
}

/// `stoeplitz_ip4(sa4, da4)`: [`stoeplitz_hash_ip4`] with the system cache.
#[inline]
pub fn stoeplitz_ip4(sa4: u32, da4: u32) -> u16 {
    stoeplitz_hash_ip4(stoeplitz_cache(), sa4, da4)
}

/// `stoeplitz_ip4port(sa4, da4, sp, dp)`: [`stoeplitz_hash_ip4port`] with the system cache.
#[inline]
pub fn stoeplitz_ip4port(sa4: u32, da4: u32, sp: u16, dp: u16) -> u16 {
    stoeplitz_hash_ip4port(stoeplitz_cache(), sa4, da4, sp, dp)
}

/// `stoeplitz_ip6(sa6, da6)`: [`stoeplitz_hash_ip6`] with the system cache.
#[inline]
pub fn stoeplitz_ip6(sa6: &[u8; 16], da6: &[u8; 16]) -> u16 {
    stoeplitz_hash_ip6(stoeplitz_cache(), sa6, da6)
}

/// `stoeplitz_ip6port(sa6, da6, sp, dp)`: [`stoeplitz_hash_ip6port`] with the system cache.
#[inline]
pub fn stoeplitz_ip6port(sa6: &[u8; 16], da6: &[u8; 16], sp: u16, dp: u16) -> u16 {
    stoeplitz_hash_ip6port(stoeplitz_cache(), sa6, da6, sp, dp)
}

/// `stoeplitz_eaddr(ea)`: [`stoeplitz_hash_eaddr`] with the system cache.
#[inline]
pub fn stoeplitz_eaddr(ea: &[u8; 6]) -> u16 {
    stoeplitz_hash_eaddr(stoeplitz_cache(), ea)
}

/// `parity`: the count (mod 2) of ones in the binary representation of `n16`.
pub fn parity(n16: u16) -> i32 {
    let mut n16 = n16;
    n16 = ((n16 & 0xaaaa) >> 1) ^ (n16 & 0x5555);
    n16 = ((n16 & 0xcccc) >> 2) ^ (n16 & 0x3333);
    n16 = ((n16 & 0xf0f0) >> 4) ^ (n16 & 0x0f0f);
    n16 = ((n16 & 0xff00) >> 8) ^ (n16 & 0x00ff);
    i32::from(n16)
}

/// `stoeplitz_random_seed`: a key drawn uniformly at random among those of parity 1, the ones
/// whose Toeplitz matrix is invertible.
pub fn stoeplitz_random_seed() -> StoeplitzKey {
    let mut seed = (arc4random() & u32::from(u16::MAX)) as StoeplitzKey;
    if parity(seed) == 0 {
        seed ^= 1;
    }
    seed
}

/// `stoeplitz_init`: draws the system key and fills the system cache. Called once, from
/// `main()`, on the boot CPU.
pub fn stoeplitz_init() {
    let seed = stoeplitz_random_seed();
    stoeplitz_keyseed.store(seed, Ordering::Relaxed);
    // SAFETY: `main()` calls this once on the boot CPU before anything that reads the cache
    // (`stoeplitz_cache`) exists, so no other reference to it is live.
    stoeplitz_cache_init(unsafe { STOEPLITZ_SYSKEY_CACHE.get_mut() }, seed);
}

/// `stoeplitz_cache_init`: fills `scache` for the key `skey`.
///
/// The first eight columns H of the Toeplitz matrix T generate the remaining eight with the
/// byteswap J = `swap16`: T = [H JH]. Thus the hash of n = [hi lo] is
/// (H * hi) ^ swap16(H * lo), and H * val is cached for every byte value.
pub fn stoeplitz_cache_init(scache: &mut StoeplitzCache, skey: StoeplitzKey) {
    // Calculate the first eight columns H of the Toeplitz matrix T.
    let mut column = [0u16; NBBY as usize];
    for (b, col) in (0..NBBY).zip(column.iter_mut()) {
        // skey << b | skey >> (NBSK - b), in 16 bits.
        *col = skey.rotate_left(b);
    }

    // Cache the results of H * val for all possible values of a byte.
    for (val, entry) in scache.bytes.iter_mut().enumerate() {
        let mut res = 0u16;
        for (b, col) in (0..NBBY).zip(column.iter()) {
            let shift = NBBY - b - 1;
            if val & (1 << shift) != 0 {
                res ^= *col;
            }
        }
        *entry = res;
    }
}

/// `stoeplitz_hash_ip4`: hashes an IPv4 address pair (`in_addr_t`, network order); symmetric
/// in the two addresses.
pub fn stoeplitz_hash_ip4(scache: &StoeplitzCache, faddr: u32, laddr: u32) -> u16 {
    stoeplitz_hash_n32(scache, faddr ^ laddr)
}

/// `stoeplitz_hash_ip4port`: hashes an IPv4 address and port pair (network order); the same
/// for both directions of a flow.
pub fn stoeplitz_hash_ip4port(
    scache: &StoeplitzCache,
    faddr: u32,
    laddr: u32,
    fport: u16,
    lport: u16,
) -> u16 {
    stoeplitz_hash_n32(scache, faddr ^ laddr ^ u32::from(fport) ^ u32::from(lport))
}

/// The xor of the eight `s6_addr32` words of two IPv6 addresses.
fn in6_xor(faddr6: &[u8; 16], laddr6: &[u8; 16]) -> u32 {
    let word = |a: &[u8; 16], i: usize| u32::from_ne_bytes([a[i], a[i + 1], a[i + 2], a[i + 3]]);
    (0..16)
        .step_by(4)
        .fold(0, |n32, i| n32 ^ word(faddr6, i) ^ word(laddr6, i))
}

/// `stoeplitz_hash_ip6`: hashes an IPv6 address pair (the bytes of each `struct in6_addr`).
pub fn stoeplitz_hash_ip6(scache: &StoeplitzCache, faddr6: &[u8; 16], laddr6: &[u8; 16]) -> u16 {
    stoeplitz_hash_n32(scache, in6_xor(faddr6, laddr6))
}

/// `stoeplitz_hash_ip6port`: hashes an IPv6 address and port pair (network order).
pub fn stoeplitz_hash_ip6port(
    scache: &StoeplitzCache,
    faddr6: &[u8; 16],
    laddr6: &[u8; 16],
    fport: u16,
    lport: u16,
) -> u16 {
    let n32 = in6_xor(faddr6, laddr6) ^ u32::from(fport) ^ u32::from(lport);
    stoeplitz_hash_n32(scache, n32)
}

/// `stoeplitz_hash_eaddr`: hashes an Ethernet address.
pub fn stoeplitz_hash_eaddr(scache: &StoeplitzCache, ea: &[u8; 6]) -> u16 {
    let ea16 = |i: usize| u16::from_ne_bytes([ea[2 * i], ea[2 * i + 1]]);
    stoeplitz_hash_n16(scache, ea16(0) ^ ea16(1) ^ ea16(2))
}

/// `stoeplitz_to_key`: fills `key` (an even number of bytes) with the system key, for a
/// driver's receive-side scaling hash key.
pub fn stoeplitz_to_key(key: &mut [u8]) {
    let skey = htons(stoeplitz_keyseed.load(Ordering::Relaxed));

    kassert!(key.len().is_multiple_of(2));

    for k in key.as_chunks_mut::<2>().0 {
        *k = [(skey >> 8) as u8, skey as u8];
    }
}
/* </CODE> */

/* <TESTS> */
#[cfg(test)]
mod tests {
    use super::*;
    use crate::sys::endian::htonl;

    /// The hash as the matrix product it is: column `j` of the circulant matrix is the key rotated
    /// left by `j`, and bit `15 - j` of `n` selects it. Independent of the byte cache.
    fn toeplitz_ref(skey: StoeplitzKey, n: u16) -> u16 {
        (0..16)
            .filter(|j| n & (0x8000 >> j) != 0)
            .fold(0, |acc, j| acc ^ skey.rotate_left(j))
    }

    fn cache(skey: StoeplitzKey) -> StoeplitzCache {
        let mut scache = StoeplitzCache::new();
        stoeplitz_cache_init(&mut scache, skey);
        scache
    }

    #[test]
    fn known_answers() {
        let sc = cache(STOEPLITZ_KEYSEED);
        // The first column is the key; the last is the key rotated right by one.
        assert_eq!(stoeplitz_hash_n16(&sc, 0x8000), 0x6d5a);
        assert_eq!(stoeplitz_hash_n16(&sc, 0x0001), 0x36ad);
        assert_eq!(stoeplitz_hash_n16(&sc, 0x0080), 0x5a6d); // column 8: swap16 of the key
        assert_eq!(stoeplitz_hash_n16(&sc, 0x8001), 0x6d5a ^ 0x36ad);
        assert_eq!(stoeplitz_cache_entry(&sc, 0x80), 0x6d5a);
        assert_eq!(stoeplitz_cache_entry(&sc, 0x01), 0x6d5a_u16.rotate_left(7));
    }

    #[test]
    fn cache_matches_the_matrix_product() {
        for skey in [STOEPLITZ_KEYSEED, 0x0001, 0xfffe, 0x1234, 0x8000] {
            let sc = cache(skey);
            for n in (0..=u16::MAX).step_by(7) {
                assert_eq!(
                    stoeplitz_hash_n16(&sc, n),
                    toeplitz_ref(skey, n),
                    "{skey:#x} {n:#x}"
                );
            }
        }
    }

    #[test]
    fn host_and_network_order_agree() {
        let sc = cache(STOEPLITZ_KEYSEED);
        for h in [0u16, 1, 0x1234, 0xbeef, u16::MAX] {
            assert_eq!(
                stoeplitz_hash_h16(&sc, h),
                stoeplitz_hash_n16(&sc, htons(h))
            );
        }
        for h in [0u32, 0x0a00_0202, 0xdead_beef] {
            assert_eq!(
                stoeplitz_hash_h32(&sc, h),
                stoeplitz_hash_n32(&sc, htonl(h))
            );
        }
        let h64 = 0x0123_4567_89ab_cdef_u64;
        assert_eq!(
            stoeplitz_hash_h64(&sc, h64),
            stoeplitz_hash_h32(&sc, (h64 ^ (h64 >> 32)) as u32)
        );
    }

    #[test]
    fn symmetric_and_linear() {
        let sc = cache(0x4d2b);
        let (a, b) = (htonl(0x0a00_020f), htonl(0xc0a8_0101));
        let (p, q) = (htons(12345), htons(80));
        assert_eq!(stoeplitz_hash_ip4(&sc, a, b), stoeplitz_hash_ip4(&sc, b, a));
        assert_eq!(
            stoeplitz_hash_ip4port(&sc, a, b, p, q),
            stoeplitz_hash_ip4port(&sc, b, a, q, p)
        );
        assert_eq!(
            stoeplitz_hash_ip4port(&sc, a, b, p, q),
            stoeplitz_hash_ip4(&sc, a, b) ^ stoeplitz_hash_n16(&sc, p ^ q)
        );
        let (x, y) = ([0x20u8; 16], {
            let mut y = [0u8; 16];
            y[15] = 1;
            y
        });
        assert_eq!(
            stoeplitz_hash_ip6(&sc, &x, &y),
            stoeplitz_hash_ip6(&sc, &y, &x)
        );
        assert_eq!(
            stoeplitz_hash_ip6port(&sc, &x, &y, p, q),
            stoeplitz_hash_ip6port(&sc, &y, &x, q, p)
        );
        assert_eq!(stoeplitz_hash_ip6(&sc, &x, &x), 0);
        let ea = [0x52, 0x54, 0x00, 0x12, 0x34, 0x56];
        let ea16 = |i: usize| u16::from_ne_bytes([ea[2 * i], ea[2 * i + 1]]);
        assert_eq!(
            stoeplitz_hash_eaddr(&sc, &ea),
            stoeplitz_hash_n16(&sc, ea16(0)) ^ stoeplitz_hash_n16(&sc, ea16(1) ^ ea16(2))
        );
    }

    #[test]
    fn odd_parity_keys_are_invertible() {
        for n in [0u16, 1, 3, 0x8000, 0x6d5a, u16::MAX] {
            assert_eq!(parity(n), (n.count_ones() & 1) as i32, "{n:#x}");
        }
        for _ in 0..8 {
            assert_eq!(parity(stoeplitz_random_seed()), 1);
        }
        // An odd-parity key permutes the 16-bit values; an even-parity one does not.
        for (skey, bijective) in [(STOEPLITZ_KEYSEED, true), (0x6d5b, false)] {
            let sc = cache(skey);
            let mut seen = [false; 1 << 16];
            for n in 0..=u16::MAX {
                seen[usize::from(stoeplitz_hash_n16(&sc, n))] = true;
            }
            assert_eq!(seen.iter().all(|&s| s), bijective, "{skey:#x}");
        }
    }

    #[test]
    fn key_bytes() {
        let mut key = [0u8; 40];
        stoeplitz_to_key(&mut key);
        let seed = stoeplitz_keyseed.load(Ordering::Relaxed);
        for pair in key.as_chunks::<2>().0 {
            assert_eq!(*pair, htons(seed).to_be_bytes());
        }
    }

    #[test]
    #[ignore = "needs OPENBSD_SRC (just test-ref)"]
    fn values_match_the_c_header() {
        let defs = crate::reftest::defines("sys/net/toeplitz.h");
        crate::reftest::assert_defines!(defs; STOEPLITZ_KEYSEED);
    }
}
/* </TESTS> */
